//
// structured configuration; see #13752
//

#pragma once

#define DIGIPOT_I2C
#define DIGIPOT_I2C_ADDRESS_A 0x2C
#define DIGIPOT_I2C_ADDRESS_B 0x2D

#undef  DIGIPOT_I2C_NUM_CHANNELS
#define DIGIPOT_I2C_NUM_CHANNELS 5

#undef  DIGIPOT_I2C_MOTOR_CURRENTS
#define DIGIPOT_I2C_MOTOR_CURRENTS { 1.4, 1.4, 1.2, 1.0, 1.0 }

#define LIN_ADVANCE
#define LIN_ADVANCE_K 0.22

#define CASE_LIGHT_ENABLE
#define CASE_LIGHT_DEFAULT_ON true
#define CASE_LIGHT_DEFAULT_BRIGHTNESS 255

#undef X_HOME_BUMP_MM
#undef Y_HOME_BUMP_MM
#undef Z_HOME_BUMP_MM
#undef HOMING_BUMP_DIVISOR
#define X_HOME_BUMP_MM 4
#define Y_HOME_BUMP_MM 4
#define Z_HOME_BUMP_MM 2
#define HOMING_BUMP_DIVISOR { 5, 5, 10 }

#undef  MICROSTEP_MODES
#define MICROSTEP_MODES { 32, 32, 32, 32, 32 }

#define MINIMUM_STEPPER_DIR_DELAY 1000

#define MINIMUM_STEPPER_PULSE 4

#define MAXIMUM_STEPPER_RATE 250000

#define EMERGENCY_PARSER

#define ADAPTIVE_STEP_SMOOTHING
