#!/usr/bin/env bash
#
# firstpush
#
# Push a branch to 'origin' and open the
# commit log to watch Travis CI progress.
#

[[ $# == 0 ]] || { echo "usage: `basename $0`" 1>&2 ; exit 1; }

MFINFO=$(mfinfo) || exit 1
IFS=' ' read -a INFO <<< "$MFINFO"
FORK=${INFO[1]}
REPO=${INFO[2]}
BRANCH=${INFO[5]}

git push --set-upstream origin HEAD:$BRANCH

OPEN=$(echo $(which gnome-open xdg-open open) | awk '{ print $1 }')
URL="https://github.com/$FORK/$REPO/commits/$BRANCH"

if [ -z "$OPEN" ]; then
  echo "Can't find a tool to open the URL:"
  echo $URL
else
  echo "Viewing commits on $BRANCH..."
  "$OPEN" "$URL"
fi
