#!/usr/bin/env bash
#
# mfhelp
#

cat <<THIS
Marlin Firmware Commands:

  firstpush ... Push and set-upstream the current branch to 'origin'
  ghpc ........ Push the current branch to its upstream branch
  ghtp ........ Set the transfer protolcol for all your remotes
  mfadd ....... Fetch a remote branch from any Marlin fork
  mfclean ..... Attempt to clean up merged and deleted branches
  mfdoc ....... Build the website, serve locally, and browse
  mffp ........ Push new commits directly to MarlinFirmware
  mfinfo ...... Provide branch information (for the other scripts)
  mfinit ...... Create an 'upstream' remote for 'MarlinFirmare'
  mfnew ....... Create a new branch based on 'bugfix-...'
  mfpr ........ Push the current branch and open the PR form
  mfpub ....... Build and publish the marlinfw.org website
  mfqp ........ Commit changes, do an interactive rebase, and push
  mfrb ........ Interactively rebase the current branch on 'bugfix-...'
  mftest ...... Run a platform test locally with PlatformIO
  mfup ........ Fetch the latest 'upstream' and rebase on it

  Enter [command] --help for more information.

THIS
