#!/usr/bin/env bash
#
# mfinfo
#
# Provide the following info about the working directory:
#
#   - Remote (upstream) Org name (MarlinFirmware)
#   - Remote (origin) Org name (your Github username)
#   - Repo Name (Marlin, MarlinDev, MarlinDocumentation)
#   - PR Target branch (bugfix-1.1.x, bugfix-2.0.x, or master)
#   - Branch Arg (the branch argument or current branch)
#   - Current Branch
#

usage() {
  echo "Usage: `basename $0` [1|2] [branch]" 1>&2
}

CURR=$(git branch 2>/dev/null | grep ^* | sed 's/\* //g')
[[ -z $CURR ]] && { echo "No git repository here!" 1>&2 ; exit 1; }
[[ $CURR == "(no"* ]] && { echo "Git is busy with merge, rebase, etc." 1>&2 ; exit 1; }

REPO=$(git remote get-url upstream 2>/dev/null | sed -E 's/.*\/(.*)\.git/\1/')
[[ -z $REPO ]] && { echo "`basename $0`: No 'upstream' remote found. (Did you run mfinit?)" 1>&2 ; exit 1; }

ORG=$(git remote get-url upstream 2>/dev/null | sed -E 's/.*[\/:](.*)\/.*$/\1/')
[[ $ORG == MarlinFirmware ]] || { echo "`basename $0`: Not a Marlin repository." 1>&2 ; exit 1; }

case "$REPO" in
  Marlin              ) TARG=bugfix-1.1.x ;
                        [[ $# > 0 ]] && [[ $1 == 2 ]] && TARG=bugfix-2.0.x
                        ;;
  MarlinDocumentation ) TARG=master ;;
esac

FORK=$(git remote get-url origin 2>/dev/null | sed -E 's/.*[\/:](.*)\/.*$/\1/')

# BRANCH can be given as the last argument
case "$#" in
  0 ) BRANCH=$CURR ;;
  1 )
    case "$1" in
      1|2) BRANCH=$CURR ;;
      *) BRANCH=$1 ;;
    esac
    ;;
  2 )
    case "$1" in
      1|2) BRANCH=$2 ;;
      *) usage ; exit 1 ;;
    esac
    ;;
esac

echo "$ORG $FORK $REPO $TARG $BRANCH $CURR"
