#!/usr/bin/env bash
#
# mfpr [1|2]
#
# Make a PR against bugfix-1.1.x or bugfix-2.0.x
#

[[ $# < 2 && $1 != "-h" && $1 != "--help" ]] || { echo "usage: `basename $0` [branch]" 1>&2 ; exit 1; }

MFINFO=$(mfinfo "$@") || exit 1
IFS=' ' read -a INFO <<< "$MFINFO"
ORG=${INFO[0]}
FORK=${INFO[1]}
REPO=${INFO[2]}
TARG=${INFO[3]}
BRANCH=${INFO[4]}
OLDBRANCH=${INFO[5]}

[[ $BRANCH == $TARG ]] && { echo "Can't create a PR from the PR Target ($BRANCH). Make a copy first." 1>&2 ; exit 1; }

[[ $BRANCH != $OLDBRANCH ]] && { git checkout $BRANCH || exit 1; }

# See if it's been pushed yet
if [ -z "$(git branch -vv | grep ^\* | grep \\[origin)" ]; then firstpush; fi

which xdg-open >/dev/null && TOOL=xdg-open
which gnome-open >/dev/null && TOOL=gnome-open
which open >/dev/null && TOOL=open
URL="https://github.com/$ORG/$REPO/compare/$TARG...$FORK:$BRANCH?expand=1"

if [ -z "$OPEN" ]; then
  echo "Can't find a tool to open the URL:"
  echo $URL
else
  echo "Opening a New PR Form..."
  "$OPEN" "$URL"
fi

[[ $BRANCH != $OLDBRANCH ]] && git checkout $OLDBRANCH
