#!/usr/bin/env bash
#
# mfrb
# MF Rebase manually to re-message, merge, drop, etc.
#
# Does "git rebase -i" against the repo's "target" branch
#
# Usually `git rebase -i upstream/bugfix-2.1.x`
#

MFINFO=$(mfinfo "$@") || exit 1
IFS=' ' read -a INFO <<< "$MFINFO"
TARG=${INFO[3]}
CURR=${INFO[5]}

IND=6
while [ $IND -lt ${#INFO[@]} ]; do
  ARG=${INFO[$IND]}
  case "$ARG" in
    -q|--quick ) QUICK=1 ;;
     -h|--help ) USAGE=1 ;;
             * ) USAGE=1 ; echo "unknown option: $ARG" ;;
  esac
  let IND+=1
done

[[ $USAGE == 1 ]] && { echo "usage: `basename $0` [1|2]" 1>&2 ; exit 1 ; }

[[ $QUICK ]] || git fetch upstream
git rebase upstream/$TARG && git rebase -i upstream/$TARG
