#!/usr/bin/env bash
#
#  mftest                             Select a test to apply and build
#  mftest -b [#]                      Build the auto-detected environment
#  mftest -u [#]                      Upload the auto-detected environment
#  mftest [name] [index] [-y]         Set config options and optionally build a test
#

MFINFO=$(mfinfo) || exit 1
[[ -d Marlin/src ]] || { echo "Please 'cd' up to repo root." ; exit 1 ; }

TESTPATH=buildroot/tests

STATE_FILE=$( echo ./.pio/.mftestrc )
SED=$(which gsed || which sed)

shopt -s extglob nocasematch

# Matching patterns
ISNUM='^[0-9]+$'
ISCMD='^(restore|opt|exec|use|pins|env)_'
ISEXEC='^exec_'
ISCONT='\\ *$'

# Get the environment and test number from the command
TESTENV=${1:-'-'}
CHOICE=${2:-0}
AUTOENV=0

# Allow shorthand for test name
case $TESTENV in
    tree) pio run -d . -e include_tree ; exit 1 ;;
     due) TESTENV='DUE' ;;
     esp) TESTENV='esp32' ;;
    lin*) TESTENV='linux_native' ;;
 lpc?(8)) TESTENV='LPC1768' ;;
    lpc9) TESTENV='LPC1769' ;;
    m128) TESTENV='mega1280' ;;
    m256) TESTENV='mega2560' ;;
    mega) TESTENV='mega2560' ;;
     stm) TESTENV='STM32F103RE' ;;
      f1) TESTENV='STM32F103RE' ;;
      f4) TESTENV='STM32F4' ;;
      f7) TESTENV='STM32F7' ;;
      s6) TESTENV='FYSETC_S6' ;;
  teensy) TESTENV='teensy31' ;;
     t31) TESTENV='teensy31' ;;
     t32) TESTENV='teensy31' ;;
     t35) TESTENV='teensy35' ;;
     t36) TESTENV='teensy35' ;;

-h|--help)  echo -e "$(basename $0) : Marlin Firmware test, build, and upload\n"
            echo "Usage: $(basename $0) ................. Select env and test to apply / run"
            echo "       $(basename $0) [-y] env ........ Select a test for env to apply / run"
            echo "       $(basename $0) [-y] env test ... Apply / run the specified env test"
            echo "       $(basename $0) -b [variant] .... Auto-build the specified variant"
            echo "       $(basename $0) -u [variant] .... Auto-build and upload the specified variant"
            echo
            echo "env shortcuts: tree due esp lin lpc|lpc8 lpc9 m128 m256|mega stm|f1 f4 f7 s6 teensy|t31|t32 t35|t36"
            exit
            ;;

          # Build with the last-built env
      -r) [[ -f "$STATE_FILE" ]] || { echo "No previous (-r) build state found." ; exit 1 ; }
          read TESTENV <"$STATE_FILE"
          pio run -d . -e $TESTENV
          exit
          ;;

   -[bu]) MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//' )
          [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1 ; }
          BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
          BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
          BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
          [[ -z $BNUM ]] && { echo "Error - Can't find $MB in boards list." ; exit 1 ; }
          readarray -t ENVS <<< $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E '#include.+//.+env:.+' | grep -oE 'env:[^ ]+' | $SED -E 's/env://' )
          [[ -z $ENVS ]] && { echo "Error - Can't find target(s) for $MB ($BNUM)." ; exit 1 ; }
          ECOUNT=${#ENVS[*]}

          if [[ $ECOUNT == 1 ]]; then
            TARGET=$ENVS
          else
            if [[ $CHOICE == 0 ]]; then
              #
              # List env names and numbers. Get selection.
              #
              echo "Available targets for \"$BDESC\" | $MB ($BNUM):"

              IND=0 ; for ENV in "${ENVS[@]}"; do let IND++ ; echo " $IND) $ENV" ; done

              if [[ $ECOUNT > 1 ]]; then
                for (( ; ; ))
                do
                  read -p "Select a target for '$MB' (1-$ECOUNT) : " CHOICE
                  [[ -z "$CHOICE" ]] && { echo '(canceled)' ; exit 1 ; }
                  [[ $CHOICE =~ $ISNUM ]] && ((CHOICE >= 1 && CHOICE <= ECOUNT)) && break
                  echo ">>> Invalid environment choice '$CHOICE'."
                done
                echo
              fi
            else
              echo "Detected \"$BDESC\" | $MB ($BNUM)."
              [[ $CHOICE > $ECOUNT ]] && { echo "Environment selection out of range." ; exit 1 ; }
            fi
            TARGET="${ENVS[$CHOICE-1]}"
            echo "Selected $TARGET"
          fi

          echo "$TARGET" >"$STATE_FILE"

          if [[ $TESTENV == "-u" ]]; then
            echo "Build/Uploading environment $TARGET for board $MB ($BNUM)..." ; echo
            pio run -t upload -e $TARGET
          else
            echo "Building environment $TARGET for board $MB ($BNUM)..." ; echo
            pio run -e $TARGET
          fi
          exit
          ;;

          # The -y flag may come first
      -y) TESTENV=${2:-'-'} ; CHOICE=${3:-0} ;;

  -[a-z]) echo "Unknown flag $TESTENV" ; exit 1 ;;
       -) ;;
esac

#
# List available tests and ask for selection
#

if [[ $TESTENV == '-' ]]; then
  IND=0
  NAMES=()
  for FILE in $( ls -1 $TESTPATH/*-tests )
  do
    let IND++
    TNAME=${FILE/-tests/}
    TNAME=${TNAME/$TESTPATH\//}
    NAMES+=($TNAME)
    (( IND < 10 )) && echo -n " "
    echo " $IND) $TNAME"
  done

  echo
  for (( ; ; ))
  do
    read -p "Select a test to apply (1-$IND) : " NAMEIND
    [[ -z "$NAMEIND" ]] && { echo '(canceled)' ; exit 1 ; }
    [[ $NAMEIND =~ $ISNUM ]] && ((NAMEIND >= 1 && NAMEIND <= IND)) && { TESTENV=${NAMES[$NAMEIND-1]} ; echo ; break ; }
    echo "Invalid selection."
  done
fi

# Get the contents of the test file
OUT=$( cat $TESTPATH/$TESTENV-tests 2>/dev/null ) || { echo "Can't find test '$TESTENV'." ; exit 1 ; }

# Count up the number of tests
TESTCOUNT=$( awk "/$ISEXEC/{a++}END{print a}" <<<"$OUT" )

# User entered a number?
(( CHOICE && CHOICE > TESTCOUNT )) && { echo "Invalid test selection '$CHOICE' (1-$TESTCOUNT)." ; exit 1 ; }

if [[ $CHOICE == 0 ]]; then
  #
  # List test descriptions with numbers and get selection
  #
  echo "Available '$TESTENV' tests:" ; echo "$OUT" | {
    IND=0
    while IFS= read -r LINE
    do
      if [[ $LINE =~ $ISEXEC ]]; then
        DESC=$( "$SED" -E 's/^.+"(.*)".*$/\1/g' <<<"$LINE" )
        (( ++IND < 10 )) && echo -n " "
        echo " $IND) $DESC"
      fi
    done
  }
  CHOICE=1
  if [[ $TESTCOUNT > 1 ]]; then
    for (( ; ; ))
    do
      read -p "Select a '$TESTENV' test (1-$TESTCOUNT) : " CHOICE
      [[ -z "$CHOICE" ]] && { echo '(canceled)' ; exit 1 ; }
      [[ $CHOICE =~ $ISNUM ]] && ((CHOICE >= 1 && CHOICE <= TESTCOUNT)) && break
      echo ">>> Invalid test selection '$CHOICE'."
    done
  fi
fi

#
# Run the specified test lines
#
echo "$OUT" | {
  IND=0
  GOTX=0
  CMD=""
  while IFS= read -r LINE
  do
    if [[ $LINE =~ $ISCMD || $GOTX == 1 ]]; then
      ((!IND)) && let IND++
      if [[ $LINE =~ $ISEXEC ]]; then
        ((IND++ > CHOICE)) && break
      else
        ((!HEADER)) && {
          HEADER=1
          echo -e "\n#\n# Test $TESTENV ($CHOICE) $DESC\n#"
        }
        ((IND == CHOICE)) && {
          GOTX=1
          [[ $CMD == "" ]] && CMD="$LINE" || CMD=$( echo -e "$CMD$LINE" | $SED -e 's/\\//g' )
          [[ $LINE =~ $ISCONT ]] || { echo $CMD ; eval "$CMD" ; CMD="" ; }
        }
      fi
    fi
  done
}

# Make clear it's a TEST
opt_set CUSTOM_MACHINE_NAME "\"$TESTENV-tests ($CHOICE)\""

# Get a -y parameter the lazy way
[[ "$2" == "-y" || "$3" == "-y" ]] && BUILD_YES='Y'

# Build the test too?
if [[ $BUILD_YES != 'Y' ]]; then
  echo
  read -p "Build $TESTENV test #$CHOICE (y/N) ? " BUILD_YES
fi

[[ $BUILD_YES == 'Y' || $BUILD_YES == 'Yes' ]] && {
  pio run -d . -e $TESTENV
  echo "$TESTENV" >"$STATE_FILE"
}
