#!/usr/bin/env bash
#
# Build tests for STM32F407ZG BigTreeTech SKR Pro
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_PRO_V1_1
opt_set SERIAL_PORT 1
exec_test $1 $2 "BigTreeTech SKR Pro Default Configuration"

restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_PRO_V1_1
opt_set SERIAL_PORT -1
opt_set EXTRUDERS 3
opt_set TEMP_SENSOR_1 1
opt_set TEMP_SENSOR_2 1
opt_set E0_AUTO_FAN_PIN PC10
opt_set E1_AUTO_FAN_PIN PC11
opt_set E2_AUTO_FAN_PIN PC12
exec_test $1 $2 "BigTreeTech SKR Pro 3 Extruders with Auto-Fan"

# clean up
restore_configs
