#!/usr/bin/env bash
#
# Build tests for STM32F407ZG BigTreeTech SKR Pro
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BIGTREE_SKR_PRO_V1_1
opt_set SERIAL_PORT 1
exec_test $1 $2 "BigTreeTech SKR Pro Default Configuration"

# clean up
restore_configs
