#!/usr/bin/env bash
#
# Build tests for STM32F1 Bigtreetech
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BIGTREE_SKR_E3_DIP
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
