#!/usr/bin/env bash
#
# Build tests for STM32F407VET6 BigTreeTech BTT002
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_BTT002_V1_0
opt_set SERIAL_PORT 1
exec_test $1 $2 "BigTreeTech BTT002 Default Configuration"

# clean up
restore_configs
