#!/usr/bin/env bash

# exit on first failure
set -e

restore_configs
opt_set MOTHERBOARD BOARD_RAMPS4DUE_EFB
opt_enable S_CURVE_ACCELERATION
opt_set E0_AUTO_FAN_PIN 8
opt_set EXTRUDER_AUTO_FAN_SPEED 100
exec_test $1 $2 "RAMPS4DUE_EFB S_CURVE_ACCELERATION"
