#!/usr/bin/env bash
#
# Build tests for Linux x86_64
#

# exit on first failure
set -e

restore_configs
opt_set MOTHERBOARD BOARD_LINUX_RAMPS
opt_set TEMP_SENSOR_BED 1
opt_enable PIDTEMPBED EEPROM_SETTINGS
exec_test $1 $2 "Linux with EEPROM"

# cleanup
restore_configs
