#!/usr/bin/env bash
#
# Build tests for STM32F070CB Malyan M300
#

# exit on first failure
set -e

use_example_configs "delta/Malyan M300"
opt_disable AUTO_BED_LEVELING_3POINT
exec_test $1 $2 "Malyan M300 (delta)"

# cleanup
restore_configs
