#!/usr/bin/env bash
#
# Build tests for STM32F070CB Malyan M300
#

# exit on first failure
set -e

use_example_configs Malyan/M200
opt_set MOTHERBOARD BOARD_MALYAN_M300
exec_test $1 $2 "Malyan M300"

# cleanup
restore_configs
