#!/usr/bin/env bash
#
# Build tests for AVR ATmega1280
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
