#!/usr/bin/env bash
#
# Build tests for AVR ATmega1280
#

# exit on first failure
set -e

#
# Build with the default configurations
#
#restore_configs
#exec_test $1 $2 "Default Configuration"

#
# Test MESH_BED_LEVELING feature, with LCD
#
restore_configs
opt_enable SPINDLE_FEATURE MESH_BED_LEVELING G26_MESH_VALIDATION MESH_G28_REST_ORIGIN LCD_BED_LEVELING MESH_EDIT_MENU ULTIMAKERCONTROLLER
exec_test $1 $2 "Spindle, MESH_BED_LEVELING, and LCD"


# clean up
restore_configs
