#!/usr/bin/env bash
#
# Build tests for STM32F1 genericSTM32F103VE
#

# exit on first failure
set -e

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO
exec_test $1 $2 "Default Configuration"

# cleanup
restore_configs
