#!/usr/bin/env bash
#
# Build tests for AVR ATmega2560 RAMBo
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_EINSY_RAMBO
opt_set X_DRIVER_TYPE TMC2130
opt_set Y_DRIVER_TYPE TMC2130
opt_set Z_DRIVER_TYPE TMC2130
opt_set E0_DRIVER_TYPE TMC2130
exec_test $1 $2 "Default Configuration"

#
# Full size Rambo Dual Endstop CNC
#
restore_configs
opt_set MOTHERBOARD BOARD_RAMBO
opt_set EXTRUDERS 0
opt_set TEMP_SENSOR_0 999
opt_set DUMMY_THERMISTOR_999_VALUE 170
opt_enable USE_XMAX_PLUG
opt_enable USE_YMAX_PLUG
opt_enable USE_ZMAX_PLUG
opt_enable S_CURVE_ACCELEARATION
opt_disable MIN_SOFTWARE_ENDSTOP_Z
opt_disable MAX_SOFTWARE_ENDSTOPS
opt_enable EEPROM_SETTINGS
opt_enable SD_SUPPORT
opt_enable REVERSE_ENCODER_DIRECTION
opt_enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
opt_enable X_DUAL_STEPPER_DRIVERS
opt_enable X_DUAL_ENDSTOPS
opt_enable Y_DUAL_STEPPER_DRIVERS
opt_enable Y_DUAL_ENDSTOPS
opt_enable ADAPTIVE_STEP_SMOOTHING
opt_set DIGIPOT_MOTOR_CURRENT '{ 120, 120, 120, 120, 120 }'
opt_enable CNC_COORDINATE_SYSTEMS
opt_enable GCODE_MOTION_MODES

exec_test $1 $2 "Rambo CNC Configuration"

# clean up
restore_configs
