#!/usr/bin/env bash
#
# Build tests for rumba32_f446ve
#

# exit on first failure
set -e

# Build examples
restore_configs
opt_set MOTHERBOARD BOARD_RUMBA32_AUS3D
opt_set SERIAL_PORT -1
opt_set X_DRIVER_TYPE TMC2130
exec_test $1 $2 "rumba32_f446ve Default Config with TMC2130"

# cleanup
restore_configs
