#!/usr/bin/env bash
#
# Build tests for STM32F407VET6
#

# exit on first failure
set -e

use_example_configs STM32/Black_STM32F407VET6
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "Full-featured Sample Black STM32F407VET6 config"

# cleanup
restore_configs
