#!/usr/bin/env bash
#
# Build tests for STM32F7
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_REMRAM_V1
opt_set SERIAL_PORT 1
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
