#!/usr/bin/env bash
#
# Build tests for STM32F070CB Malyan M200 V2
#

# exit on first failure
set -e

use_example_configs Malyan/M200
opt_set MOTHERBOARD BOARD_MALYAN_M200_V2
exec_test $1 $2 "Malyan M200 v2"

# cleanup
restore_configs
