#!/usr/bin/env bash
#
# Build tests for STM32F103RC FYSETC
#

# exit on first failure
set -e

#
# Build with the default configurations
#
use_example_configs "FYSETC/Cheetah 1.2/base"
exec_test $1 $2 "Cheetah 1.2 Configuration"

# clean up
restore_configs
