#!/usr/bin/env bash
#
# Build tests for STM32F103VET6
#

# exit on first failure
set -e

use_example_configs Alfawise/U20
opt_set MOTHERBOARD BOARD_LONGER3D_LK
opt_set SERIAL_PORT 1
exec_test $1 $2 "Full-featured U20 config"

# cleanup
restore_configs
