#!/usr/bin/env bash
#
# Build tests for AVR ATmega 644p
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_SANGUINOLOLU_12
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
