@echo off

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\LCD Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\CrealityV4X\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\SKR_E3_Mini\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Pre-Compiled Binaries\EZBoard Pre-Compiled Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\TH3D_EZBoardLite\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\TH3D_EZBoardLite_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\MKS_Robin_Mini\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Anet_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\AnyCubic_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Creality_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\ADIM_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Alfawise_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Artillery_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Creality_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Sovol_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Sunlu_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Wanhao_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\MKS_SGen_L_V2_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\Board Configuration Files\Kingroon_V1_2\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_STL_Pack.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_STL_Pack.zip" "D:\Work\GitHub\UnifiedFirmware\STL Files"