/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2026 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// Tiny digits for UBL mesh map labels. Generated by buildroot/share/fonts/genTFTdigits.py

#include "../../../../inc/MarlinConfigPre.h"

#if ALL(TFT_COLOR_UI, AUTO_BED_LEVELING_UBL)
  #include "../../ui_common.h"   // HAS_TFT_TINY_FONT depends on the layout
#endif

#if HAS_TFT_TINY_FONT

// NotoSans Medium Digits 13pt, digit height: 11px, range: 0x002b-0x0039
extern const uint8_t NotoSans_Medium_Digits[308] = {
  130,11,43,0,57,0,10,255, // unifont_t
  // 0x002b  +
  7,7,14,7,0,1,2,0,3,0,3,64,127,248,3,0,3,0,1,0,
  // 0x002c  , (unused)
  255,
  // 0x002d  -
  4,2,2,4,0,2,190,0,
  // 0x002e  .
  2,3,3,4,1,255,144,224,0,
  // 0x002f  / (unused)
  255,
  // 0x0030  0
  7,11,22,7,0,255,1,64,31,240,56,52,112,40,112,44,112,44,112,44,48,56,56,116,15,224,0,0,
  // 0x0031  1
  4,9,9,7,1,0,31,187,75,11,11,11,11,11,11,
  // 0x0032  2
  7,10,20,7,0,0,1,64,63,240,16,52,0,52,0,112,0,208,3,128,14,0,56,0,127,252,
  // 0x0033  3
  7,11,22,7,0,255,5,64,63,240,16,52,0,52,5,224,15,224,0,56,0,40,16,116,127,224,0,0,
  // 0x0034  4
  7,10,20,7,0,0,0,16,0,240,2,240,7,112,12,112,52,112,112,176,191,252,0,112,0,112,
  // 0x0035  5
  6,11,22,7,1,255,21,64,191,192,208,0,208,0,250,64,86,208,0,224,0,160,65,208,255,64,0,0,
  // 0x0036  6
  7,11,22,7,0,255,0,80,11,240,44,0,52,0,55,224,121,120,112,44,48,44,56,56,15,224,0,0,
  // 0x0037  7
  7,10,20,7,0,0,21,80,127,252,0,56,0,112,0,224,1,192,2,128,3,64,11,0,13,0,
  // 0x0038  8
  7,11,22,7,0,255,1,64,46,240,52,52,52,52,30,224,15,208,52,52,112,44,52,56,31,224,0,0,
  // 0x0039  9
  7,11,22,7,0,255,1,0,47,224,52,52,112,40,112,60,62,188,6,104,0,52,0,176,63,128,0,0,
};

#endif // HAS_TFT_TINY_FONT
