#ifndef LANGUAGE_H
#define LANGUAGE_H

// NOTE: IF YOU CHANGE THIS FILE / MERGE THIS FILE WITH CHANGES
//
//   ==> ALWAYS TRY TO COMPILE MARLIN WITH/WITHOUT "ULTIPANEL" / "ULTRALCD" / "SDSUPPORT" #define IN "Configuration.h" 
//   ==> ALSO TRY ALL AVAILABLE "LANGUAGE_CHOICE" OPTIONS

// Languages
// 1  English
// 2  Polish
// 3  French
// 4  German
// 5  Spanish
// 6  Russian
// 7  Italian
// 8  Portuguese
// 9  Finnish
// 10 Aragonese
// 11 Dutch

#ifndef LANGUAGE_CHOICE
	#define LANGUAGE_CHOICE 1  // Pick your language from the list above
#endif

#define PROTOCOL_VERSION "1.0"

#if defined(WITBOX)
	#define MACHINE_NAME "bq Witbox"
	#define FIRMWARE_URL "http://www.bqreaders.com/descargas-witbox.html"
	#define FIRMWARE_VER "v1.4.2"
#elif defined(CUSTOM_MENDEL_NAME)
	#define MACHINE_NAME CUSTOM_MENDEL_NAME
#else
	// Default firmware set to Mendel
	#define MACHINE_NAME "Mendel"
	#define FIRMWARE_URL "https://github.com/ErikZalm/Marlin/"
#endif

#ifndef MACHINE_UUID
   #define MACHINE_UUID "00000000-0000-0000-0000-000000000000"
#endif


#define STRINGIFY_(n) #n
#define STRINGIFY(n) STRINGIFY_(n)


// Common LCD messages
/* nothing here as of yet */

// Common serial messages
#define MSG_MARLIN "Marlin"

// Serial Console Messages

#define MSG_Enqueing "enqueing \""
#define MSG_POWERUP "PowerUp"
#define MSG_EXTERNAL_RESET " External Reset"
#define MSG_BROWNOUT_RESET " Brown out Reset"
#define MSG_WATCHDOG_RESET " Watchdog Reset"
#define MSG_SOFTWARE_RESET " Software Reset"
#define MSG_AUTHOR " | Author: "
#define MSG_CONFIGURATION_VER " Last Updated: "
#define MSG_FREE_MEMORY " Free Memory: "
#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
#define MSG_OK "ok"
#define MSG_FILE_SAVED "Done saving file."
#define MSG_ERR_LINE_NO "Line Number is not Last Line Number+1, Last Line: "
#define MSG_ERR_CHECKSUM_MISMATCH "checksum mismatch, Last Line: "
#define MSG_ERR_NO_CHECKSUM "No Checksum with line number, Last Line: "
#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "No Line Number with checksum, Last Line: "
#define MSG_FILE_PRINTED "Done printing file"
#define MSG_BEGIN_FILE_LIST "Begin file list"
#define MSG_END_FILE_LIST "End file list"
#define MSG_M104_INVALID_EXTRUDER "M104 Invalid extruder "
#define MSG_M105_INVALID_EXTRUDER "M105 Invalid extruder "
#define MSG_M200_INVALID_EXTRUDER "M200 Invalid extruder "
#define MSG_M218_INVALID_EXTRUDER "M218 Invalid extruder "
#define MSG_ERR_NO_THERMISTORS "No thermistors - no temperature"
#define MSG_M109_INVALID_EXTRUDER "M109 Invalid extruder "
#define MSG_HEATING "Heating..."
#define MSG_HEATING_COMPLETE "Heating done."
#define MSG_BED_HEATING "Bed Heating."
#define MSG_BED_DONE "Bed done."
#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
#define MSG_COUNT_X " Count X: "
#define MSG_ERR_KILLED "Printer halted. kill() called!"
#define MSG_ERR_STOPPED "Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"
#define MSG_RESEND "Resend: "
#define MSG_UNKNOWN_COMMAND "Unknown command: \""
#define MSG_ACTIVE_EXTRUDER "Active Extruder: "
#define MSG_INVALID_EXTRUDER "Invalid extruder"
#define MSG_X_MIN "x_min: "
#define MSG_X_MAX "x_max: "
#define MSG_Y_MIN "y_min: "
#define MSG_Y_MAX "y_max: "
#define MSG_Z_MIN "z_min: "
#define MSG_Z_MAX "z_max: "
#define MSG_M119_REPORT "Reporting endstop status"
#define MSG_ENDSTOP_HIT "TRIGGERED"
#define MSG_ENDSTOP_OPEN "open"
#define MSG_HOTEND_OFFSET "Hotend offsets:"

#define MSG_SD_CANT_OPEN_SUBDIR "Cannot open subdir"
#define MSG_SD_INIT_FAIL "SD init fail"
#define MSG_SD_VOL_INIT_FAIL "volume.init failed"
#define MSG_SD_OPENROOT_FAIL "openRoot failed"
#define MSG_SD_CARD_OK "SD card ok"
#define MSG_SD_WORKDIR_FAIL "workDir open failed"
#define MSG_SD_OPEN_FILE_FAIL "open failed, File: "
#define MSG_SD_FILE_OPENED "File opened: "
#define MSG_SD_SIZE " Size: "
#define MSG_SD_FILE_SELECTED "File selected"
#define MSG_SD_WRITE_TO_FILE "Writing to file: "
#define MSG_SD_PRINTING_BYTE "SD printing byte "
#define MSG_SD_NOT_PRINTING "Not SD printing"
#define MSG_SD_ERR_WRITE_TO_FILE "error writing to file"
#define MSG_SD_CANT_ENTER_SUBDIR "Cannot enter subdir: "

#define MSG_STEPPER_TOO_HIGH "Steprate too high: "
#define MSG_ENDSTOPS_HIT "endstops hit: "
#define MSG_ERR_COLD_EXTRUDE_STOP " cold extrusion prevented"
#define MSG_ERR_LONG_EXTRUDE_STOP " too long extrusion prevented"
#define MSG_BABYSTEPPING_X "Babystepping X"
#define MSG_BABYSTEPPING_Y "Babystepping Y"
#define MSG_BABYSTEPPING_Z "Babystepping Z"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE "Error in menu structure"

#if LANGUAGE_CHOICE == 1

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " ready."
	#define MSG_SD_INSERTED "Card inserted"
	#define MSG_SD_REMOVED "Card removed"
	#define MSG_MAIN "Main"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART "Autostart"
	#define MSG_DISABLE_STEPPERS "Disable steppers"
	#define MSG_AUTO_HOME "Auto home"
	#define MSG_SET_ORIGIN "Set origin"
	#define MSG_PREHEAT_PLA "Preheat PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Preheat PLA conf"
	#define MSG_PREHEAT_ABS "Preheat ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Preheat ABS conf"
	#define MSG_COOLDOWN "Cooldown"
	#define MSG_SWITCH_PS_ON "Switch power on"
	#define MSG_SWITCH_PS_OFF "Switch power off"
	#define MSG_EXTRUDE "Extrude"
	#define MSG_RETRACT "Retract"
	#define MSG_MOVE_AXIS "Move axis"
	#define MSG_MOVE_X "Move X"
	#define MSG_MOVE_Y "Move Y"
	#define MSG_MOVE_Z "Move Z"
	#define MSG_MOVE_E "Extruder"
	#define MSG_MOVE_01MM "Move 0.1mm"
	#define MSG_MOVE_1MM "Move 1mm"
	#define MSG_MOVE_10MM "Move 10mm"
	#define MSG_SPEED "Speed"
	#define MSG_NOZZLE "Temperature"
	#define MSG_NOZZLE1 "Nozzle2"
	#define MSG_NOZZLE2 "Nozzle3"
	#define MSG_BED "Bed"
	#define MSG_FAN_SPEED "Fan speed"
	#define MSG_FLOW "Flow"
	#define MSG_CONTROL "Control"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Fact"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "On "
	#define MSG_OFF "Off"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Accel"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "A-retract"
	#define MSG_XSTEPS "Xsteps/mm"
	#define MSG_YSTEPS "Ysteps/mm"
	#define MSG_ZSTEPS "Zsteps/mm"
	#define MSG_ESTEPS "Esteps/mm"
	#define MSG_RECTRACT "Rectract"
	#define MSG_TEMPERATURE "Temperature"
	#define MSG_MOTION "Motion"
	#define MSG_CONTRAST "LCD contrast"
	#define MSG_STORE_EPROM "Store memory"
	#define MSG_LOAD_EPROM "Load memory"
	#define MSG_RESTORE_FAILSAFE "Restore failsafe"
	#define MSG_REFRESH "Refresh"
	#define MSG_WATCH "Info screen"
	#define MSG_PREPARE "Prepare"
	#define MSG_TUNE "Tune"
	#define MSG_PAUSE_PRINT "Pause print"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_RESUME_PRINT "Resume print"
	#define MSG_STOP_PRINT "Stop print"
	#define MSG_CARD_MENU "Print from SD"
	#define MSG_NO_CARD "No SD card"
	#define MSG_DWELL "Sleep..."
	#define MSG_USERWAIT "Wait for user..."
	#define MSG_RESUMING "Resuming print"
	#define MSG_NO_MOVE "No move."
	#define MSG_KILLED "KILLED. "
	#define MSG_STOPPED "STOPPED. "
	#define MSG_CONTROL_RETRACT  "Retract mm"
	#define MSG_CONTROL_RETRACTF "Retract  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Hop mm"
	#define MSG_CONTROL_RETRACT_RECOVER "UnRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "UnRet  F"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Change filament"
	#define MSG_INIT_SDCARD "Init. SD card"
	#define MSG_CNG_SDCARD "Change SD card"
	#define MSG_ZPROBE_OUT "Z probe out. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Endstop abort"
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"

		#define MSG_WELLCOME "bq Hephestos"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 2


// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " gotowy."
	#define MSG_SD_INSERTED "Karta wlozona"
	#define MSG_SD_REMOVED "Karta usunieta"
	#define MSG_MAIN "Menu glowne"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART "Autostart"
	#define MSG_DISABLE_STEPPERS "Wylacz silniki"
	#define MSG_AUTO_HOME "Auto. poz. zerowa"
	#define MSG_SET_ORIGIN "Ustaw punkt zero"
	#define MSG_PREHEAT_PLA "Rozgrzej PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Ustaw. rozg. PLA"
	#define MSG_PREHEAT_ABS "Rozgrzej ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Ustaw. rozg. ABS"
	#define MSG_COOLDOWN "Chlodzenie"
	#define MSG_SWITCH_PS_ON "Wlacz zasilacz"
	#define MSG_SWITCH_PS_OFF "Wylacz zasilacz"
	#define MSG_EXTRUDE "Ekstruzja"
	#define MSG_RETRACT "Cofanie"
	#define MSG_MOVE_AXIS "Ruch osi"
	#define MSG_MOVE_X "Przesun w X"
	#define MSG_MOVE_Y "Przesun w Y"
	#define MSG_MOVE_Z "Przesun w Z"
	#define MSG_MOVE_E "Ekstruzja (os E)"
	#define MSG_MOVE_01MM "Przesuwaj co .1mm"
	#define MSG_MOVE_1MM "Przesuwaj co 1mm"
	#define MSG_MOVE_10MM "Przesuwaj co 10mm"
	#define MSG_SPEED "Predkosc"
	#define MSG_NOZZLE "Dysza"
	#define MSG_NOZZLE1 "Dysza 2"
	#define MSG_NOZZLE2 "Dysza 3"
	#define MSG_BED "Loze"
	#define MSG_FAN_SPEED "Obroty wiatraka"
	#define MSG_FLOW "Przeplyw"
	#define MSG_CONTROL "Kontrola"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Mnoznik"
	#define MSG_AUTOTEMP "Auto. temperatura"
	#define MSG_ON "Wl. "
	#define MSG_OFF "Wyl."
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Przyspieszenie"
	#define MSG_VXY_JERK "Zryw Vxy"
	#define MSG_VZ_JERK "Zryw Vz"
	#define MSG_VE_JERK "Zryw Ve"
	#define MSG_VMAX "Vmax"
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "Vskok min"
	#define MSG_AMAX "Amax"
	#define MSG_A_RETRACT "A-wycofanie"
	#define MSG_XSTEPS "krokiX/mm"
	#define MSG_YSTEPS "krokiY/mm"
	#define MSG_ZSTEPS "krokiZ/mm"
	#define MSG_ESTEPS "krokiE/mm"
	#define MSG_RECTRACT "Wycofanie"
	#define MSG_TEMPERATURE "Temperatura"
	#define MSG_MOTION "Ruch"
	#define MSG_CONTRAST "Kontrast LCD"
	#define MSG_STORE_EPROM "Zapisz w pamieci"
	#define MSG_LOAD_EPROM "Wczytaj z pamieci"
	#define MSG_RESTORE_FAILSAFE "Ustaw. fabryczne"
	#define MSG_REFRESH "\004Odswiez"
	#define MSG_WATCH "Ekran glowny"
	#define MSG_PREPARE "Przygotuj"
	#define MSG_CONTROL "Ustawienia"
	#define MSG_TUNE "Strojenie"
	#define MSG_PAUSE_PRINT "Pauza"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_RESUME_PRINT "Wznowienie"
	#define MSG_STOP_PRINT "Stop"
	#define MSG_CARD_MENU "Menu karty SD"
	#define MSG_NO_CARD "Brak karty"
	#define MSG_DWELL "Uspij..."
	#define MSG_USERWAIT "Oczekiwanie..."
	#define MSG_RESUMING "Wznawianie druku"
	#define MSG_NO_MOVE "Brak ruchu"
	#define MSG_KILLED "Ubity. "
	#define MSG_STOPPED "Zatrzymany. "
	#define MSG_STEPPER_RELEASED "Zwolniony."
	#define MSG_CONTROL_RETRACT  "Wycofaj mm"
	#define MSG_CONTROL_RETRACTF "Wycofaj  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Skok Z mm:"
	#define MSG_CONTROL_RETRACT_RECOVER "Cof. wycof. +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "Cof. wycof.  F"
	#define MSG_AUTORETRACT "Auto. wycofanie"
	#define MSG_FILAMENTCHANGE "Zmien filament"
	#define MSG_INIT_SDCARD "Inicjal. karty SD"
	#define MSG_CNG_SDCARD "Zmiana karty SD"
	#define MSG_ZPROBE_OUT "Sonda Z za lozem"
	#define MSG_POSITION_UNKNOWN "Wroc w XY przed Z"
	#define MSG_ZPROBE_ZOFFSET "Offset Z"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Blad wyl. kranc."
	#define MSG_CONTRAST "Kontrast"
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 3

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " prete."
	#define MSG_SD_INSERTED "Carte inseree"
	#define MSG_SD_REMOVED "Carte retiree"
	#define MSG_MAIN "Menu principal"
	#define MSG_BACK "Retour"
	#define MSG_AUTOSTART "Demarrage auto"
	#define MSG_DISABLE_STEPPERS "Desactiver moteurs"
	#define MSG_AUTO_HOME "Retour origine"
	#define MSG_SET_ORIGIN "Definir origine"
	#define MSG_PREHEAT_PLA "Prechauffer le PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Conf prechauffe PLA"
	#define MSG_PREHEAT_ABS "Prechauffer ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Conf prechauffe ABS"
	#define MSG_COOLDOWN "Refroidir"
	#define MSG_SWITCH_PS_ON "Allumer"
	#define MSG_SWITCH_PS_OFF "Eteindre"
	#define MSG_EXTRUDE "Extruder"
	#define MSG_RETRACT "Retracter"
	#define MSG_MOVE_AXIS "Deplacer axe"
	#define MSG_MOVE_X "Deplacer X"
	#define MSG_MOVE_Y "Deplacer Y"
	#define MSG_MOVE_Z "Deplacer Z"
	#define MSG_MOVE_E "Extrudeuse"
	#define MSG_MOVE_01MM "Deplacer 0,1mm"
	#define MSG_MOVE_1MM "Deplacer 1mm"
	#define MSG_MOVE_10MM "Deplacer 10mm"
	#define MSG_SPEED "Vitesse"
	#define MSG_NOZZLE "Temperature"
	#define MSG_NOZZLE1 "Embout2"
	#define MSG_NOZZLE2 "Embout3"
	#define MSG_BED "Plateau"
	#define MSG_FAN_SPEED "Vitesse ventilateur"
	#define MSG_FLOW "Flux"
	#define MSG_CONTROL "Controle"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Fact"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "On "
	#define MSG_OFF "Off"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Accel."
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "A-retract"
	#define MSG_XSTEPS "X pas/mm"
	#define MSG_YSTEPS "Y pas/mm"
	#define MSG_ZSTEPS "Z pas/mm"
	#define MSG_ESTEPS "E pas/mm"
	#define MSG_RECTRACT "Retracter"
	#define MSG_TEMPERATURE "Temperature"
	#define MSG_MOTION "Mouvement"
	#define MSG_CONTRAST "Contraste ecran LCD"
	#define MSG_STORE_EPROM "Stocker memoire"
	#define MSG_LOAD_EPROM "Charger memoire"
	#define MSG_RESTORE_FAILSAFE "Restauration urgente"
	#define MSG_REFRESH "Rafraichir"
	#define MSG_WATCH "Ecran info"
	#define MSG_PREPARE "Preparer"
	#define MSG_TUNE "Syntonisation"
	#define MSG_PAUSE_PRINT "Pause impression"
	#define MSG_PAUSED "Appuy pour reprendre"
	#define MSG_PAUSING "En pause..."
	#define MSG_PRINTING "Impression en cours"
	#define MSG_READY_UNLOAD "Appuy. & retirer fil"
	#define MSG_UNLOAD_CLICK "Appuy pour continuer"
	#define MSG_LOAD_CLICK "Charger nv filament"
	#define MSG_RESUME_PRINT "Reprendre impression"
	#define MSG_STOP_PRINT "Arreter impression"
	#define MSG_CARD_MENU "Imprimer depuis SD"
	#define MSG_NO_CARD "Pas de carte SD"
	#define MSG_DWELL "En veille"
	#define MSG_USERWAIT "En attente"
	#define MSG_RESUMING "Reprise impression"
	#define MSG_NO_MOVE "Aucun mouvement"
	#define MSG_KILLED "Arret d'urgence. "
	#define MSG_STOPPED "ARRETE "
	#define MSG_CONTROL_RETRACT  "Retracter mm"
	#define MSG_CONTROL_RETRACTF "Retracter  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Hop mm"
	#define MSG_CONTROL_RETRACT_RECOVER "UnRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "UnRet  F"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Changer filament"
	#define MSG_INIT_SDCARD "Init. carte SD"
	#define MSG_CNG_SDCARD "Changer carte SD"
	#define MSG_ZPROBE_OUT "verif. Z hors base"
	#define MSG_POSITION_UNKNOWN "Origine X/Y avant Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Butoir annuler"
	#define MSG_END_HOUR "heures"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Niveler plateau"
		#define MSG_START_SCRIPT "Demarrer script"
		#define MSG_PREHEAT "Prechauffer"
		#define MSG_JOG "Deplacer"
		#define MSG_LOAD "Charger"
		#define MSG_UNLOAD "Retirer"
		#define MSG_ABORT "Annuler" 
		#define MSG_PRE_EXTRUD "Inserer & appuyer"      
		#define MSG_EXTRUDING "Extrusion en cours" 
		#define MSG_LENGTH "Longueur :"         
		#define MSG_RETRACTING "Retractation..."
		#define MSG_WELLCOME "Witbox"
		#define MSG_LP_COOL_1 "Refroidissement..."
		#define MSG_LP_COOL_2 "Temp."
		#define MSG_LP_COOL_3 "Appuyer pour annuler"
		#define MSG_LB_COOL_1 "Refroidissement..."
		#define MSG_LB_COOL_2 "Temp."
		#define MSG_CF_HEAT_1 "En chauffe..."
		#define MSG_CF_HEAT_2 "Temp."
		#define MSG_EXIT "Appuyer pour annuler"
		#define MSG_WIZARD_LEVELBED_0_1 		"Nivellement plateau"
		#define MSG_WIZARD_LEVELBED_0_2 		"Appuyer pour debuter"
		#define MSG_WIZARD_LEVELBED_1_1 		" Nivelez 1er point "
		#define MSG_WIZARD_LEVELBED_1_2 		"& appuyer sur bouton"
		#define MSG_WIZARD_LEVELBED_2_1  		" Nivelez 2eme point "
		#define MSG_WIZARD_LEVELBED_2_2 		"& appuyer sur bouton"
		#define MSG_WIZARD_LEVELBED_3_1  		" Nivelez 3eme point "
		#define MSG_WIZARD_LEVELBED_3_2 		"& appuyer sur bouton"
		#define MSG_WIZARD_LEVELBED_4_1  		" Nivelez 4eme point "
		#define MSG_WIZARD_LEVELBED_4_2 		"& appuyer sur bouton"
		#define MSG_WIZARD_LEVELBED_5_1  		"Verifiez le centre"
		#define MSG_WIZARD_LEVELBED_6_1 		"  Plateau nivele !  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Appuy. bouton pour"
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	"debuter le processus"
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	" & retirer filament"
		#define MSG_WIZARD_CHANGEFILAMENT_1_0	"Retirer le filament"
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"rapidement quand"
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	"il aura ete expulse"
		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"Inserer le nouveau"
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	"filament et appuyer"
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "sur le bouton"
		#define MSG_WIZARD_CHANGEFILAMENT_3_0	"Quand le filament"
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"est rentre, appuyer"
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"sur le bouton pour"
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"reprendre impression"
		#define MSG_SD_BAD_FILENAME "Mauvais nom fichier!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 4

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " fertig."
	#define MSG_SD_INSERTED "Karte eingesetzt"
	#define MSG_SD_REMOVED "Karte entfernt"
	#define MSG_MAIN "Hauptmenue"
	#define MSG_BACK "Zurueck"
	#define MSG_AUTOSTART "Autostart"
	#define MSG_DISABLE_STEPPERS "Motoren abschalten"
	#define MSG_AUTO_HOME "Zum Ursprung bringen"
	#define MSG_SET_ORIGIN "Ursprung festlegen"
	#define MSG_PREHEAT_PLA "PLA vorwaermen"
	#define MSG_PREHEAT_PLA_SETTINGS "PLA Temp. anpassen"
	#define MSG_PREHEAT_ABS "ABS vorwaermen"
	#define MSG_PREHEAT_ABS_SETTINGS "ABS Temp. anpassen"
	#define MSG_COOLDOWN "Abkuehlen"
	#define MSG_SWITCH_PS_ON "Switch power on"
	#define MSG_SWITCH_PS_OFF "Switch power off"
	#define MSG_EXTRUDE "Extrudieren"
	#define MSG_RETRACT "Retract"
	#define MSG_MOVE_AXIS "Achsen bewegen"
	#define MSG_MOVE_X "X bewegen"
	#define MSG_MOVE_Y "Y bewegen"
	#define MSG_MOVE_Z "Z bewegen"
	#define MSG_MOVE_E "Extruder"
	#define MSG_MOVE_01MM "0.1mm bewegen"
	#define MSG_MOVE_1MM "1mm bewegen"
	#define MSG_MOVE_10MM "10mm bewegen"
	#define MSG_SPEED "Geschwindigkeit"
	#define MSG_NOZZLE "Temperatur"
	#define MSG_NOZZLE1 "Einspritzduese2"
	#define MSG_NOZZLE2 "Einspritzduese3"
	#define MSG_BED "Bett"
	#define MSG_FAN_SPEED "Lueftergeschw"
	#define MSG_FLOW "Fluss"
	#define MSG_CONTROL "Einstellungen"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Faktor"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "Ein "
	#define MSG_OFF "AUS"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Accel"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "A-retract"
	#define MSG_XSTEPS "XSchritte/mm"
	#define MSG_YSTEPS "YSchritte/mm"
	#define MSG_ZSTEPS "ZSchritte/mm"
	#define MSG_ESTEPS "ESchritte/mm"
	#define MSG_RECTRACT "Retract"
	#define MSG_TEMPERATURE "Temperatur"
	#define MSG_MOTION "Bewegung"
	#define MSG_CONTRAST "LCD Kontrast"
	#define MSG_STORE_EPROM "Speicher ablegen"
	#define MSG_LOAD_EPROM "Speicher laden"
	#define MSG_RESTORE_FAILSAFE "Standardkonf"
	#define MSG_REFRESH "Aktualisieren"
	#define MSG_WATCH "Start"
	#define MSG_PREPARE "Vorbereiten"
	#define MSG_TUNE "Justierung"
	#define MSG_PAUSE_PRINT "Druck unterbrechen"
	#define MSG_PAUSED "Zum Fortsetzen druecken"
	#define MSG_PAUSING "Zum Weiterlaufen klicken"
	#define MSG_PRINTING "Pausiert"
	#define MSG_READY_UNLOAD "Druecken & Fil. ausgeben"
	#define MSG_UNLOAD_CLICK "Zum Fortfahren druecken"
	#define MSG_LOAD_CLICK "Neues Filament laden"
	#define MSG_RESUME_PRINT "Mit dem Druck fortfahren"
	#define MSG_STOP_PRINT "Druck stoppen"
	#define MSG_CARD_MENU "Von SD Karte drucken"
	#define MSG_NO_CARD "Keine SD Karte"
	#define MSG_DWELL "Ruhen..." 
	#define MSG_USERWAIT "Warte auf Nutzer..."
	#define MSG_RESUMING "Druck fortsetzen"
	#define MSG_NO_MOVE "Keine Bewegung."
	#define MSG_KILLED "STILLSTAND"
	#define MSG_STOPPED "GESTOPPT. "
	#define MSG_CONTROL_RETRACT  "Retract mm"
	#define MSG_CONTROL_RETRACTF "Retract  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Hop mm"
	#define MSG_CONTROL_RETRACT_RECOVER "UnRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "UnRet  F"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Filament wechseln"
	#define MSG_INIT_SDCARD "SD- Karte starten"
	#define MSG_CNG_SDCARD "SD- Karte wechseln"
	#define MSG_ZPROBE_OUT "Z probe out. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Endstop abort"
	#define MSG_END_HOUR "Stunden"
	#define MSG_END_MINUTE "Minuten"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Platte kalibrieren"
		#define MSG_START_SCRIPT "Script starten"
		#define MSG_PREHEAT "Vorwaermen"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Laden"
		#define MSG_UNLOAD "Entfernen"
		#define MSG_ABORT "Abbrechen" 
		#define MSG_PRE_EXTRUD "Einsetzen & Druecken"      
		#define MSG_EXTRUDING "Extrudiert..." 
		#define MSG_LENGTH "Länge:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"
		#define MSG_LP_COOL_1 "Kuehlt..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Druecke zum Abbruch"
		#define MSG_LB_COOL_1 "Kuehlt..."
		#define MSG_LB_COOL_2 "Temp:"
		#define MSG_CF_HEAT_1 "Heizt..."
		#define MSG_CF_HEAT_2 "Temp:"
		#define MSG_EXIT "Druecke zum Abbruch..."
		#define MSG_WIZARD_LEVELBED_0_1 " Platte kalibrieren...  "
		#define MSG_WIZARD_LEVELBED_0_2"   Druecken für Start   "
		#define MSG_WIZARD_LEVELBED_1_1 " Ersten Punkt justier "
		#define MSG_WIZARD_LEVELBED_1_2 " & druecke den Knopf "
		#define MSG_WIZARD_LEVELBED_2_1 "Zweiten Punkt justier "
		#define MSG_WIZARD_LEVELBED_2_2 " & druecke den Knopf "
		#define MSG_WIZARD_LEVELBED_3_1 " Dritten Punkt justier "
		#define MSG_WIZARD_LEVELBED_3_2 " & druecke den Knopf "
		#define MSG_WIZARD_LEVELBED_4_1 "Vierten Punkt justier "
		#define MSG_WIZARD_LEVELBED_4_2 " & druecke den Knopf "
		#define MSG_WIZARD_LEVELBED_5_1 "     Ist es so gut?      "		
		#define MSG_WIZARD_LEVELBED_6_1 "   Platte kalibriert!   "
		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Druecke den Knopf um "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" Prozess zu starten  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"und Fil. auszugeben"
		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Ziehe das Filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"schnell bei Stopp"
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" des Extrudierens  "
		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Setze das neue  "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" Fil. ein und druecke "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     den Knopf     "
		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" Wenn das Filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrud. druecke den "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  Knopf um weiter  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      zu drucken      "
		#define MSG_SD_BAD_FILENAME "Unguelt. Dateiname!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 5

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " lista"
	#define MSG_SD_INSERTED "Tarjeta insertada"
	#define MSG_SD_REMOVED "Tarjeta retirada"
	#define MSG_MAIN "Menu principal"
	#define MSG_BACK "Atras"
	#define MSG_AUTOSTART " Autoarranque"
	#define MSG_DISABLE_STEPPERS "Apagar motores"
	#define MSG_AUTO_HOME "Llevar al origen"
	#define MSG_SET_ORIGIN "Establecer origen"
	#define MSG_PREHEAT_PLA "Precalentar PLA"
	#define MSG_PREHEAT_PLA0 "Precalentar PLA 1"
	#define MSG_PREHEAT_PLA1 "Precalentar PLA 2"
	#define MSG_PREHEAT_PLA2 "Precalentar PLA 3"
	#define MSG_PREHEAT_PLA012 "Precal. PLA todo"
	#define MSG_PREHEAT_PLA_BEDONLY "Precal. PLA base"
	#define MSG_PREHEAT_PLA_SETTINGS "Ajustar temp. PLA"
	#define MSG_PREHEAT_ABS "Precalentar ABS"
	#define MSG_PREHEAT_ABS0 "Precalentar ABS 1"
	#define MSG_PREHEAT_ABS1 "Precalentar ABS 2"
	#define MSG_PREHEAT_ABS2 "Precalentar ABS 3"
	#define MSG_PREHEAT_ABS012 "Precal. ABS todo"
	#define MSG_PREHEAT_ABS_BEDONLY "Precal. ABS base"
	#define MSG_PREHEAT_ABS_SETTINGS "Ajustar temp. ABS"
	#define MSG_COOLDOWN "Enfriar"
	#define MSG_SWITCH_PS_ON "Encender"
	#define MSG_SWITCH_PS_OFF "Apagar"
	#define MSG_EXTRUDE "Extruir"
	#define MSG_RETRACT "Retraer"
	#define MSG_MOVE_AXIS "Mover ejes"
	#define MSG_MOVE_X "Mover X"
	#define MSG_MOVE_Y "Mover Y"
	#define MSG_MOVE_Z "Mover Z"
	#define MSG_MOVE_E "Extrusor"
	#define MSG_MOVE_E1 "Extrusor 2"
	#define MSG_MOVE_E2 "Extrusor 3"
	#define MSG_MOVE_01MM "Mover 0.1 mm"
	#define MSG_MOVE_1MM "Mover 1 mm"
	#define MSG_MOVE_10MM "Mover 10 mm"
	#define MSG_SPEED "Velocidad"
	#define MSG_NOZZLE "Temperatura"
	#define MSG_NOZZLE1 "Inyector2"
	#define MSG_NOZZLE2 "Inyector3"
	#define MSG_BED "Base"
	#define MSG_FAN_SPEED "Ventilador"
	#define MSG_FLOW "Flujo"
	#define MSG_FLOW0 "Flujo 0"
	#define MSG_FLOW1 "Flujo 1"
	#define MSG_FLOW2 "Flujo 2"
	#define MSG_CONTROL "Control"
	#define MSG_MIN "\002 Min"
	#define MSG_MAX "\002 Max"
	#define MSG_FACTOR "\002 Fact"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "On"
	#define MSG_OFF "Off"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Acel"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax"
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax"
	#define MSG_A_RETRACT "A-retrac."
	#define MSG_XSTEPS "X pasos/mm"
	#define MSG_YSTEPS "Y pasos/mm"
	#define MSG_ZSTEPS "Z pasos/mm"
	#define MSG_ESTEPS "E pasos/mm"
	#define MSG_RECTRACT "Retraer"
	#define MSG_TEMPERATURE "Temperatura"
	#define MSG_MOTION "Movimiento"
	#define MSG_STORE_EPROM "Guardar memoria"
	#define MSG_LOAD_EPROM "Cargar memoria"
	#define MSG_RESTORE_FAILSAFE "Rest. de emergen."
	#define MSG_REFRESH "Volver a cargar"
	#define MSG_WATCH "Inicio"
	#define MSG_PREPARE "Preparar"
	#define MSG_TUNE "Ajustar"
	#define MSG_PAUSE_PRINT "Pausar impresion"
	#define MSG_PRINTING "Imprimiendo..."
	#define MSG_PAUSED "Pulsa para seguir"
	#define MSG_PAUSING "Pausando..."
	#define MSG_READY_UNLOAD "Pulsa y extrae fila."
	#define MSG_UNLOAD_CLICK "Pulsa para continuar"
	#define MSG_LOAD_CLICK "Carga filamento"
	#define MSG_RESUME_PRINT "Reanudar impr."
	#define MSG_STOP_PRINT "Detener impresion"
	#define MSG_CARD_MENU "Tarjeta SD"
	#define MSG_NO_CARD "No hay tarjeta SD"
	#define MSG_DWELL "Reposo..."
	#define MSG_USERWAIT "Esperando ordenes"
	#define MSG_RESUMING "Reanudando impr."
	#define MSG_NO_MOVE "Sin movimiento"
	#define MSG_KILLED "PARADA DE EMERG."
	#define MSG_STOPPED "PARADA"
	#define MSG_CONTROL_RETRACT  "Retraer mm"
	#define MSG_CONTROL_RETRACT_SWAP  "Interc. Retraer mm"
	#define MSG_CONTROL_RETRACTF "Retraer  V"
	#define MSG_CONTROL_RETRACT_ZLIFT "Levantar mm"
	#define MSG_CONTROL_RETRACT_RECOVER "DesRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVER_SWAP "Interc. DesRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "DesRet V"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Cambiar filamento"
	#define MSG_INIT_SDCARD "Iniciando tarjeta"
	#define MSG_CNG_SDCARD "Cambiar tarjeta"
	#define MSG_RECTRACT_WIDE "Retraer"
	#define MSG_TEMPERATURE_WIDE "Temperatura"
	#define MSG_TEMPERATURE_RTN  "Temperatura"
	#define MSG_MAIN_WIDE "Menu principal"
	#define MSG_MOTION_WIDE "Movimiento"
	#define MSG_PREPARE_ALT "Preparar"
	#define MSG_CONTROL_ARROW "Control"
	#define MSG_RETRACT_ARROW "Retraer"
	#define MSG_STEPPER_RELEASED "Desacoplado"
	#define MSG_ZPROBE_OUT "Z probe out. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Minipaso X"
	#define MSG_BABYSTEP_Y "Minipaso Y"
	#define MSG_BABYSTEP_Z "Minipaso Z"
	#define MSG_ENDSTOP_ABORT "Anular endstop"
	#define MSG_CONTRAST "Contrast"
	#define MSG_HEATING "Calentando..."
	#define MSG_HEATING_COMPLETE "Fin calentamiento"
	#define MSG_BED_HEATING "Calentando cama"
	#define MSG_BED_DONE "Fin cal. cama"
	#define MSG_END_HOUR "horas"
	#define MSG_END_MINUTE "minutos"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filamento"
		#define MSG_LEVEL_PLATE "Nivelar base"
		#define MSG_START_SCRIPT "Iniciar script"
		#define MSG_PREHEAT "Calentar"
		#define MSG_JOG "Mover"
		#define MSG_LOAD "Cargar"
		#define MSG_UNLOAD "Descargar"
		#define MSG_ABORT "Atras"
		#define MSG_PRE_EXTRUD "Insertar & pulsar"
		#define MSG_EXTRUDING "Extruyendo..."
		#define MSG_LENGTH "Longitud:"
		#define MSG_RETRACTING "Retrayendo"
		#define MSG_WELLCOME "bq Hephestos"
		#define MSG_LP_INTRO "Nivelando la base... Pulsa para empezar"
		#define MSG_LP_1 " Nivela el punto 1     Pulsa la rueda"
		#define MSG_LP_2 " Nivela el punto 2     Pulsa la rueda"
		#define MSG_LP_3 " Nivela el punto 3     Pulsa la rueda"
		#define MSG_LP_4 " Nivela el punto 4     Pulsa la rueda"        
		#define MSG_LP_5 "Comprueba el centro  Pulsa para acabar"
		#define MSG_LP_6 "Base nivelada"
		#define MSG_LP_COOL_1 "Enfriando..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "  Pulsa para salir"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."

		#define MSG_SD_BAD_FILENAME "Nombre ilegal"

		#define MSG_WIZARD_LEVELBED_0_1 		"Nivelando la base..."
		#define MSG_WIZARD_LEVELBED_0_2			" Pulsa para empezar "

		#define MSG_WIZARD_LEVELBED_1_1 		" Nivela el punto 1  "
		#define MSG_WIZARD_LEVELBED_1_2 		"   Pulsa la rueda   "

		#define MSG_WIZARD_LEVELBED_2_1 		" Nivela el punto 2  "
		#define MSG_WIZARD_LEVELBED_2_2 		"   Pulsa la rueda   "

		#define MSG_WIZARD_LEVELBED_3_1 		" Nivela el punto 3  "
		#define MSG_WIZARD_LEVELBED_3_2 		"   Pulsa la rueda   "

		#define MSG_WIZARD_LEVELBED_4_1 		" Nivela el punto 4  "
		#define MSG_WIZARD_LEVELBED_4_2 		"   Pulsa la rueda   "

		#define MSG_WIZARD_LEVELBED_5_1 		"Comprueba el centro "
			
		#define MSG_WIZARD_LEVELBED_6_1 		"   Base nivelada    "

		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Pulsa el boton para "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" iniciar el proceso "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"y extraer filamento "

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	"  Tira rapidamente  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"del filamento cuando"
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" termine de extruir "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"  Inserta el nuevo  "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	"  filamento y pulsa "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "      el boton      "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" Cuando extruya el  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"filamento, pulsa el "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"boton para reanudar "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"    la impresion    "
	
	#endif //#ifdef WITBOX

#endif

#if LANGUAGE_CHOICE == 6


// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME			" Готов."
	#define MSG_SD_INSERTED						"Карта вставлена"
	#define MSG_SD_REMOVED						"Карта извлечена"
	#define MSG_MAIN							"Меню            \003"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART						"Автостарт"
	#define MSG_DISABLE_STEPPERS 				"Выкл. двигатели"
	#define MSG_AUTO_HOME						"Парковка"
	#define MSG_SET_ORIGIN						"Запомнить ноль"
	#define MSG_PREHEAT_PLA 					"Преднагрев PLA"
	#define MSG_PREHEAT_PLA_SETTINGS  			"Настройки PLA"
	#define MSG_PREHEAT_ABS						"Преднагрев ABS"
	#define MSG_PREHEAT_ABS_SETTINGS  			"Настройки ABS"
	#define MSG_COOLDOWN						"Охлаждение"
	#define MSG_SWITCH_PS_ON					"Switch Power On"
	#define MSG_SWITCH_PS_OFF					"Switch Power Off"
	#define MSG_EXTRUDE							"Экструзия"
	#define MSG_RETRACT							"Откат"
	#define MSG_MOVE_AXIS  						"Движение по осям"
	#define MSG_MOVE_X                          "Move X"
	#define MSG_MOVE_Y                          "Move Y"
	#define MSG_MOVE_Z                          "Move Z"
	#define MSG_MOVE_E                          "Extruder"
	#define MSG_MOVE_01MM                       "Move 0.1mm"
	#define MSG_MOVE_1MM                        "Move 1mm"
	#define MSG_MOVE_10MM                       "Move 10mm"
	#define MSG_SPEED							"Скорость:"
	#define MSG_NOZZLE							"\002 Фильера:"
	#define MSG_NOZZLE1							"\002 Фильера2:"
	#define MSG_NOZZLE2							"\002 Фильера3:"
	#define MSG_BED								"\002 Кровать:"
	#define MSG_FAN_SPEED						"Куллер:"
	#define MSG_FLOW							"Поток:"
	#define MSG_CONTROL							"Настройки \003"
	#define MSG_MIN								"\002 Минимум:"
	#define MSG_MAX								"\002 Максимум:"
	#define MSG_FACTOR							"\002 Фактор:"
	#define MSG_AUTOTEMP						"Autotemp:"
	#define MSG_ON								"Вкл. "
	#define MSG_OFF								"Выкл. "
	#define MSG_PID_P							"PID-P: "
	#define MSG_PID_I							"PID-I: "
	#define MSG_PID_D							"PID-D: "
	#define MSG_PID_C							"PID-C: "
	#define MSG_ACC								"Acc:"
	#define MSG_VXY_JERK						"Vxy-jerk: "
	#define MSG_VZ_JERK                         "Vz-jerk"
	#define MSG_VE_JERK                         "Ve-jerk"
	#define MSG_VMAX							"Vmax "
	#define MSG_X								"x:"
	#define MSG_Y								"y:"
	#define MSG_Z								"z:"
	#define MSG_E								"e:"
	#define MSG_VMIN							"Vmin:"
	#define MSG_VTRAV_MIN						"VTrav min:"
	#define MSG_AMAX							"Amax "
	#define MSG_A_RETRACT						"A-retract:"
	#define MSG_XSTEPS							"X шаг/mm:"
	#define MSG_YSTEPS							"Y шаг/mm:"
	#define MSG_ZSTEPS							"Z шаг/mm:"
	#define MSG_ESTEPS							"E шаг/mm:"
	#define MSG_RECTRACT    					"Откат подачи    \x7E"
	#define MSG_TEMPERATURE  					"Температура     \x7E"
	#define MSG_MOTION							"Скорости        \x7E"
	#define MSG_CONTRAST  						"LCD contrast"
	#define MSG_STORE_EPROM  					"Сохранить в EPROM"
	#define MSG_LOAD_EPROM  					"Загруз. из EPROM"
	#define MSG_RESTORE_FAILSAFE				"Сброс настроек"
	#define MSG_REFRESH							"\004Обновить"
	#define MSG_WATCH							"Обзор           \003"
	#define MSG_PREPARE							"Действия        \x7E"
	#define MSG_TUNE							"Настройки       \x7E"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_RESUME_PRINT  					"Продолжить печать"
	#define MSG_RESUME_PRINT					"Продолжить печать"
	#define MSG_STOP_PRINT 						"Остановить печать"
	#define MSG_CARD_MENU						"Меню карты      \x7E"
	#define MSG_NO_CARD							"Нет карты"
	#define MSG_DWELL							"Сон..."
	#define MSG_USERWAIT  						"Ожиданиие"
	#define MSG_RESUMING 						"Resuming print"
	#define MSG_NO_MOVE							"Нет движения."
	#define MSG_KILLED							"УБИТО."
	#define MSG_STOPPED							"ОСТАНОВЛЕНО."
	#define MSG_CONTROL_RETRACT					"Откат mm:"
	#define MSG_CONTROL_RETRACTF				"Откат  F:"
	#define MSG_CONTROL_RETRACT_ZLIFT			"Прыжок mm:"
	#define MSG_CONTROL_RETRACT_RECOVER			"Возврат +mm:"
	#define MSG_CONTROL_RETRACT_RECOVERF		"Возврат  F:"
	#define MSG_AUTORETRACT						"АвтоОткат:"
	#define MSG_FILAMENTCHANGE 					"Change filament"
	#define MSG_INIT_SDCARD 					"Init. SD-Card"
	#define MSG_CNG_SDCARD 						"Change SD-Card"
	#define MSG_ZPROBE_OUT 						"Z probe out. bed"
	#define MSG_POSITION_UNKNOWN 				"Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET 					"Z Offset"
	#define MSG_BABYSTEP_X 						"Babystep X"
	#define MSG_BABYSTEP_Y 						"Babystep Y"
	#define MSG_BABYSTEP_Z 						"Babystep Z"
	#define MSG_ENDSTOP_ABORT 					"Endstop abort"
	#define MSG_CONTRAST 						"Contrast"
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 7

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME "pronta."

	#define MSG_SD_INSERTED "SD Card inserita" 
	#define MSG_SD_REMOVED "SD Card rimossa"
	#define MSG_MAIN "Menù principale"
	#define MSG_BACK "Indietro" 
	#define MSG_AUTOSTART "Avvio automatico" 
	#define MSG_DISABLE_STEPPERS "Disabilita motori" 
	#define MSG_AUTO_HOME "Auto home" 
	#define MSG_SET_ORIGIN "Imposta origine" 
	#define MSG_PREHEAT_PLA "Preriscalda PLA" 
	#define MSG_PREHEAT_PLA_SETTINGS "Config. prerisc. PLA" 
	#define MSG_PREHEAT_ABS "Preriscalda ABS" 
	#define MSG_PREHEAT_ABS_SETTINGS "Config. prerisc. ABS" 
	#define MSG_COOLDOWN "Raffredda" 
	#define MSG_SWITCH_PS_ON "Accendi" 
	#define MSG_SWITCH_PS_OFF "Spegni" 
	#define MSG_EXTRUDE "Estrudi" 
	#define MSG_RETRACT "Ritrai" 
	#define MSG_MOVE_AXIS "Muovi assi" 
	#define MSG_MOVE_X "Muovi X" 
	#define MSG_MOVE_Y "Muovi Y" 
	#define MSG_MOVE_Z "Muovi Z" 
	#define MSG_MOVE_E "Estrudi" 
	#define MSG_MOVE_01MM "Sposta 0,1 mm" 
	#define MSG_MOVE_1MM "Sposta 1 mm" 
	#define MSG_MOVE_10MM "Sposta 10 mm" 
	#define MSG_SPEED "Velocità" 
	#define MSG_NOZZLE "Nozzle" 
	#define MSG_NOZZLE1 "Nozzle2" 
	#define MSG_NOZZLE2 "Nozzle3" 
	#define MSG_BED "Piano" 
	#define MSG_FAN_SPEED "Vel. ventola" 
	#define MSG_FLOW "Flusso" 
	#define MSG_CONTROL "Controllo" 
	#define MSG_MIN "\002 min" 
	#define MSG_MAX "\002 max" 
	#define MSG_FACTOR "\002 effett." 
	#define MSG_AUTOTEMP "Auto temp." 
	#define MSG_ON "On" 
	#define MSG_OFF "Off" 
	#define MSG_PID_P "PID-P" 
	#define MSG_PID_I "PID-I" 
	#define MSG_PID_D "PID-D" 
	#define MSG_PID_C "PID-C" 
	#define MSG_ACC  "Accel." 
	#define MSG_VXY_JERK "Vxy-jerk" 
	#define MSG_VZ_JERK "Vz-jerk" 
	#define MSG_VE_JERK "Ve-jerk" 
	#define MSG_VMAX "V.max" 
	#define MSG_X "x" 
	#define MSG_Y "y" 
	#define MSG_Z "z" 
	#define MSG_E "e" 
	#define MSG_VMIN "V.min" 
	#define MSG_VTRAV_MIN "V.trav min" 
	#define MSG_AMAX "A.max " 
	#define MSG_RETRACT "Accel. ritraz." 
	#define MSG_XSTEPS "X passi/mm" 
	#define MSG_YSTEPS "Y passi/mm" 
	#define MSG_ZSTEPS "Z passi/mm" 
	#define MSG_ESTEPS "E passi/mm" 
	#define MSG_RETRACT "Ritrai" 
	#define MSG_TEMPERATURE "Temperatura"
	#define MSG_MOTION "Movimento" 
	#define MSG_CONTRAST "Contrasto LCD" 
	#define MSG_STORE_EPROM "Salva memoria"
	#define MSG_LOAD_EPROM "Carica memoria" 
	#define MSG_RESTORE_FAILSAFE "Riprist. fail-safe"
	#define MSG_RETRACT "Refresh" 
	#define MSG_WATCH "Info display" 
	#define MSG_PREPARE "Prepara" 
	#define MSG_TUNE "Regola" 
	#define MSG_PAUSE_PRINT "Interrompi stampa" 
	#define MSG_PAUSED "Premi per riprendere" 
	#define MSG_PAUSING "In pausa..." 
	#define MSG_PRINTING "Stampa in corso..." 
	#define MSG_READY_UNLOAD "Premi e scarica filam." 
	#define MSG_UNLOAD_CLICK "Premi per continuare" 
	#define MSG_LOAD_CLICK "Carica nuovo filam." 
	#define MSG_RESUME_PRINT "Riprendi stampa" 
	#define MSG_STOP_PRINT "Arresta stampa" 
	#define MSG_CARD_MENU "Stampa da SD" 
	#define MSG_NO_CARD "Nessuna SD Card" 
	#define MSG_DWELL "Stand-by..." 
	#define MSG_USERWAIT "In attesa..." 
	#define MSG_RESUMING "Ripresa stampa in corso" 
	#define MSG_NO_MOVE "Nessun movimento" 
	#define MSG_KILLED "PROCESSO TERMINATO. " 
	#define MSG_STOPPED "PROCESSO ARRESTATO." 
	#define MSG_CONTROL_RETRACT  "Ritrai mm" 
	#define MSG_CONTROL_RETRACTF "Ritrai F" 
	#define MSG_CONTROL_RETRACT_ZLIFT "Alza mm" 
	#define MSG_CONTROL_RETRACT_RECOVER  "Riprist. ritraz. + mm" 
	#define MSG_CONTROL_RETRACT_RECOVERF "Riprist. ritraz. F" 
	#define MSG_RETRACT "Auto-ritraz." 
	#define MSG_FILAMENTCHANGE "Cambia filam." 
	#define MSG_INIT_SDCARD "Inizializ. SD Card" 
	#define MSG_CNG_SDCARD "Cambia SD Card" 
	#define MSG_ZPROBE_OUT "Verifica Z fuori piano" 
	#define MSG_POSITION_UNKNOWN "Home X/Y prima di Z" 
	#define MSG_ZPROBE_OUT "Z offset" 
	#define MSG_BABYSTEP_X "Babystep X" 
	#define MSG_BABYSTEP_Y "Babystep Y" 
	#define MSG_BABYSTEP_Z "Babystep Z" 
	#define MSG_ENDSTOP_ABORT "Ferma endstop" 
	#define MSG_END_HOUR "ore" 
	#define MSG_END_MINUTE "minuti" 

	#ifdef WITBOX

		#define MSG_FILAMENT "Filamento" 
		#define MSG_LEVEL_PLATE "Livella il piano" 
		#define MSG_START_SCRIPT "Avvia script" 
		#define MSG_PREHEAT "Preriscalda"
		#define MSG_JOG "Jog" 
		#define MSG_LOAD "Carica" 
		#define MSG_UNLOAD "Scarica" 
		#define MSG_ABORT "Ferma" 
		#define MSG_PRE_EXTRUD "Inserisci e premi"      
		#define MSG_EXTRUDING "Estrusione in corso..." 
		#define MSG_LENGTH "Lungh.:"         
		#define MSG_RETRACTING "Ritrazione..." 
		#define MSG_WELLCOME "bq Witbox" 
		#define MSG_LP_COOL_1 "Raffreddamento..." 
		#define MSG_LP_COOL_2 "Temp.:" 
		#define MSG_LP_COOL_3 "Premi per fermare" 
		#define MSG_LB_COOL_1 "Raffreddamento..." 
		#define MSG_LP_COOL_2 "Temp.:" 
		#define MSG_CF_HEAT_1 "Riscaldamento..." 
		#define MSG_CF_HEAT_2 "Temp.:" 
		#define MSG_EXIT "Premi per fermare..." 
		#define MSG_WIZARD_LEVELBED_0_1 "Livellamento del piano...  " 
		#define MSG_WIZARD_LEVELBED_0_2"Premi per avviare"
		#define MSG_WIZARD_LEVELBED_1_1 		"Regola primo punto"
		#define MSG_WIZARD_LEVELBED_1_2		"e premi il pulsante"
		#define MSG_WIZARD_LEVELBED_2_1 		"Regola secondo punto"
		#define MSG_WIZARD_LEVELBED_2_2		"e premi il pulsante"
		#define MSG_WIZARD_LEVELBED_3_1 		"Regola terzo punto"
		#define MSG_WIZARD_LEVELBED_3_2		"e premi il pulsante"
		#define MSG_WIZARD_LEVELBED_4_1 		"Regola quarto punto"
		#define MSG_WIZARD_LEVELBED_4_2		"e premi il pulsante"
		#define MSG_WIZARD_LEVELBED_5_1 		"È corretto?"		
		#define MSG_WIZARD_LEVELBED_6_1 		"Piano livellato!"
		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Premi il pulsante per"
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	"avviare il processo"
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"ed estrarre il filamento"
		#define MSG_WIZARD_CHANGEFILAMENT_1_0	"Spingi il filamento"
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"rapidamente quando"
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	"si interrompe l'estrusione"
		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"Inserisci il nuovo"
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	"filamento e premi"
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "il pulsante"
		#define MSG_WIZARD_CHANGEFILAMENT_3_0	"Quando il filamento"
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"fuoriesce, premi il"
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"pulsante per riprendere"
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"la stampa"
		#define MSG_SD_BAD_FILENAME "Nome del file non valido!"
	#endif // WITBOX
#endif


#if LANGUAGE_CHOICE == 8

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " pronta."
	#define MSG_SD_INSERTED "Cartao inserido"
	#define MSG_SD_REMOVED "Cartao extraido"
	#define MSG_MAIN "Menu principal"
	#define MSG_BACK "Voltar"
	#define MSG_AUTOSTART "Incio automatico"
	#define MSG_DISABLE_STEPPERS "Desligar motores"
	#define MSG_AUTO_HOME "Ir a origem"
	#define MSG_SET_ORIGIN "Selecionar origem"
	#define MSG_PREHEAT_PLA "Preaquecer PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Configurar temp. PLA"
	#define MSG_PREHEAT_ABS "Preaquecer ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Configurar temp. ABS"
	#define MSG_COOLDOWN "Arrefecer"
	#define MSG_SWITCH_PS_ON "Ligar energia"
	#define MSG_SWITCH_PS_OFF "Desligar energia"
	#define MSG_EXTRUDE "Extrudir"
	#define MSG_RETRACT "Retrair"
	#define MSG_MOVE_AXIS "Mover eixos"
	#define MSG_MOVE_X "Mover X"
	#define MSG_MOVE_Y "Mover Y"
	#define MSG_MOVE_Z "Mover Z"
	#define MSG_MOVE_E "Extrusor"
	#define MSG_MOVE_01MM "Mover 0,1 mm"
	#define MSG_MOVE_1MM "Mover 1 mm"
	#define MSG_MOVE_10MM "Mover 10 mm"
	#define MSG_SPEED "Velocidade"
	#define MSG_NOZZLE "Bocal"
	#define MSG_NOZZLE1 "Bocal2"
	#define MSG_NOZZLE2 "Bocal3"
	#define MSG_BED "Base"
	#define MSG_FAN_SPEED "Veloc ventoinha"
	#define MSG_FLOW "Fluxo"
	#define MSG_CONTROL "Controlo"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Fator"
	#define MSG_AUTOTEMP "Temp automatica"
	#define MSG_ON "Ligado"
	#define MSG_OFF "Desligado"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Acelerar"
	#define MSG_VXY_JERK "Solavanco-Vxy"
	#define MSG_VZ_JERK "Solavanco-Vz"
	#define MSG_VE_JERK "Solavanco-Ve"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "Retrair-A"
	#define MSG_XSTEPS "Xpassos/mm"
	#define MSG_YSTEPS "Ypassos/mm"
	#define MSG_ZSTEPS "Zpassos/mm"
	#define MSG_ESTEPS "Epassos/mm"
	#define MSG_RECTRACT "Retrair"
	#define MSG_TEMPERATURE "Temperatura"
	#define MSG_MOTION "Movimento"
	#define MSG_CONTRAST "Contraste do LCD"
	#define MSG_STORE_EPROM "Armazenar memoria"
	#define MSG_LOAD_EPROM "Carregar memoria"
	#define MSG_RESTORE_FAILSAFE "Rest. seg. de falha"
	#define MSG_REFRESH "Atualizar"
	#define MSG_WATCH "Ecra de info"
	#define MSG_PREPARE "Preparar"
	#define MSG_TUNE "Afinar"
	#define MSG_PAUSE_PRINT "Pausar impressao"
	#define MSG_PAUSED "Premir para cont."
	#define MSG_PAUSING "A pausar..."
	#define MSG_PRINTING "A imprimir..."
	#define MSG_READY_UNLOAD "Premir descarr fil."
	#define MSG_UNLOAD_CLICK "Premir para cont"
	#define MSG_LOAD_CLICK "Carregar filamento"
	#define MSG_RESUME_PRINT "Retomar impressao"
	#define MSG_STOP_PRINT "Parar impressao"
	#define MSG_CARD_MENU "Imprimir do SD"
	#define MSG_NO_CARD "Sem cartao SD"
	#define MSG_DWELL "Repouso..."
	#define MSG_USERWAIT "Aguardar ordem"
	#define MSG_RESUMING "Retomar impressao"
	#define MSG_NO_MOVE "Sem mover."
	#define MSG_KILLED "CORTADO. "
	#define MSG_STOPPED "PARADO. "
	#define MSG_CONTROL_RETRACT  "Retrair mm"
	#define MSG_CONTROL_RETRACTF "Retrair F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Elevar mm"
	#define MSG_CONTROL_RETRACT_RECOVER "Inv. Ret. +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "Inv. Ret.  F"
	#define MSG_AUTORETRACT "Retrair auto."
	#define MSG_FILAMENTCHANGE "Alterar filam."
	#define MSG_INIT_SDCARD "Inic. cartao SD"
	#define MSG_CNG_SDCARD "Alterar cartao SD"
	#define MSG_ZPROBE_OUT "Sonda fora cam. Z"
	#define MSG_POSITION_UNKNOWN "Inic. X/Y antes Z"
	#define MSG_ZPROBE_ZOFFSET "Desvio Z"
	#define MSG_BABYSTEP_X "Passo peq. X"
	#define MSG_BABYSTEP_Y "Passo peq. Y"
	#define MSG_BABYSTEP_Z "Passo peq. Z"
	#define MSG_ENDSTOP_ABORT "Abortar fim de curso"
	#define MSG_END_HOUR "horas"
	#define MSG_END_MINUTE "minutos"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filamento"
		#define MSG_LEVEL_PLATE "Nivelar base"
		#define MSG_START_SCRIPT "Iniciar sequencia"
		#define MSG_PREHEAT "Preaquecer"
		#define MSG_JOG "Mover"
		#define MSG_LOAD "Carregar"
		#define MSG_UNLOAD "Descarregar"
		#define MSG_ABORT "Abortar" 
		#define MSG_PRE_EXTRUD "Inserir e premir"      
		#define MSG_EXTRUDING "A extrudir..." 
		#define MSG_LENGTH "Comprimento:"         
		#define MSG_RETRACTING "A retrair"
		#define MSG_WELLCOME "bq Witbox"
		#define MSG_LP_COOL_1 "A arrefec..."
		#define MSG_LP_COOL_2 "Temp.:"
		#define MSG_LP_COOL_3 "Prima para abort."
		#define MSG_LB_COOL_1 "A arrefec..."
		#define MSG_LB_COOL_2 "Temp.:"
		#define MSG_CF_HEAT_1 "A aquecer..."
		#define MSG_CF_HEAT_2 "Temp.:"
		#define MSG_EXIT "Prima para abort..."
		#define MSG_WIZARD_LEVELBED_0_1 		"A nivelar placa...  "
		#define MSG_WIZARD_LEVELBED_0_2			"Prima para iniciar"
		#define MSG_WIZARD_LEVELBED_1_1 		"Ajustar prim. ponto"
		#define MSG_WIZARD_LEVELBED_1_2 		"e prima o botao"
		#define MSG_WIZARD_LEVELBED_2_1 		"Ajustar seg. ponto"
		#define MSG_WIZARD_LEVELBED_2_2 		"e prima o botao"
		#define MSG_WIZARD_LEVELBED_3_1 		" Ajustar terc. ponto"
		#define MSG_WIZARD_LEVELBED_3_2 		"e prima o botao"
		#define MSG_WIZARD_LEVELBED_4_1 		"Ajustar quar. ponto"
		#define MSG_WIZARD_LEVELBED_4_2 		"e prima o botao"
		#define MSG_WIZARD_LEVELBED_5_1 		"Esta ok?      "
		#define MSG_WIZARD_LEVELBED_6_1 		"   Placa nivelada!   "
		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Prima o bot. para"
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" iniciar o proces.  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"e extrair o fil."
		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Puxe o fil. "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"rapid. quando"
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" parar de extrude.  "
		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insira o novo   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" fil. e prima "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     o botao     "
		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" Quando o fil.  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrude., prima o "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  botao para resum.  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      impressao      "
		#define MSG_SD_BAD_FILENAME "Nome de fich. nulo!"
	#endif // WITBOX
#endif



#if LANGUAGE_CHOICE == 9

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " valmis."
	#define MSG_SD_INSERTED "Kortti asetettu"
	#define MSG_SD_REMOVED "Kortti poistettu"
	#define MSG_MAIN "Palaa"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART "Automaatti"
	#define MSG_DISABLE_STEPPERS "Vapauta moottorit"
	#define MSG_AUTO_HOME "Aja referenssiin"
	#define MSG_SET_ORIGIN "Aseta origo"
	#define MSG_PREHEAT_PLA "Esilammita PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Esilamm. PLA konf"
	#define MSG_PREHEAT_ABS "Esilammita ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Esilamm. ABS konf"
	#define MSG_COOLDOWN "Jaahdyta"
	#define MSG_SWITCH_PS_ON "Switch Power On"
	#define MSG_SWITCH_PS_OFF "Switch Power Off"
	#define MSG_EXTRUDE "Pursota"
	#define MSG_RETRACT "Veda takaisin"
	#define MSG_MOVE_AXIS "Liikuta akseleita"
	#define MSG_MOVE_X "Move X"
	#define MSG_MOVE_Y "Move Y"
	#define MSG_MOVE_Z "Move Z"
	#define MSG_MOVE_E "Extruder"
	#define MSG_MOVE_01MM "Move 0.1mm"
	#define MSG_MOVE_1MM "Move 1mm"
	#define MSG_MOVE_10MM "Move 10mm"
	#define MSG_SPEED "Nopeus"
	#define MSG_NOZZLE "Suutin"
	#define MSG_NOZZLE1 "Suutin2"
	#define MSG_NOZZLE2 "Suutin3"
	#define MSG_BED "Alusta"
	#define MSG_FAN_SPEED "Tuul. nopeus"
	#define MSG_FLOW "Virtaus"
	#define MSG_CONTROL "Kontrolli"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Kerr"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "On "
	#define MSG_OFF "Off"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Kiihtyv"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VLiike min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "A-peruuta"
	#define MSG_XSTEPS "Xsteps/mm"
	#define MSG_YSTEPS "Ysteps/mm"
	#define MSG_ZSTEPS "Zsteps/mm"
	#define MSG_ESTEPS "Esteps/mm"
	#define MSG_RECTRACT "Veda takaisin"
	#define MSG_TEMPERATURE "Lampotila"
	#define MSG_MOTION "Liike"
	#define MSG_CONTRAST "LCD contrast"
	#define MSG_STORE_EPROM "Tallenna muistiin"
	#define MSG_LOAD_EPROM "Lataa muistista"
	#define MSG_RESTORE_FAILSAFE "Palauta oletus"
	#define MSG_REFRESH "Paivita"
	#define MSG_WATCH "Seuraa"
	#define MSG_PREPARE "Valmistele"
	#define MSG_TUNE "Saada"
	#define MSG_PAUSE_PRINT "Keskeyta tulostus"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_RESUME_PRINT "Jatka tulostusta"
	#define MSG_STOP_PRINT "Pysayta tulostus"
	#define MSG_CARD_MENU "Korttivalikko"
	#define MSG_NO_CARD "Ei korttia"
	#define MSG_DWELL "Nukkumassa..."
	#define MSG_USERWAIT "Odotet. valintaa"
	#define MSG_RESUMING "Jatke. tulostusta"
	#define MSG_NO_MOVE "Ei liiketta."
	#define MSG_KILLED "KILLED. "
	#define MSG_STOPPED "STOPPED. "
	#define MSG_CONTROL_RETRACT  "Veda mm"
	#define MSG_CONTROL_RETRACTF "Veda F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Z mm"
	#define MSG_CONTROL_RETRACT_RECOVER "UnRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "UnRet  F"
	#define MSG_AUTORETRACT "AutoVeto."
	#define MSG_FILAMENTCHANGE "Change filament"
	#define MSG_INIT_SDCARD "Init. SD-Card"
	#define MSG_CNG_SDCARD "Change SD-Card"
	#define MSG_ZPROBE_OUT "Z probe out. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Endstop abort"
	#define MSG_CONTRAST "Contrast"
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif

#if LANGUAGE_CHOICE == 10

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " parada."
	#define MSG_SD_INSERTED "Tarcheta colocada"
	#define MSG_SD_REMOVED "Tarcheta retirada"
	#define MSG_MAIN "Menu prencipal"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART " Autostart"
	#define MSG_DISABLE_STEPPERS "Amortar motors"
	#define MSG_AUTO_HOME "Levar a l'orichen"
	#define MSG_SET_ORIGIN "Establir zero"
	#define MSG_PREHEAT_PLA "Precalentar PLA"
	#define MSG_PREHEAT_PLA_SETTINGS "Achustar tem. PLA"
	#define MSG_PREHEAT_ABS "Precalentar ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "Achustar tem. ABS"
	#define MSG_COOLDOWN "Enfriar"
	#define MSG_SWITCH_PS_ON "Enchegar Fuent"
	#define MSG_SWITCH_PS_OFF "Desenchegar Fuent"
	#define MSG_EXTRUDE "Extruir"
	#define MSG_RETRACT "Retraer"
	#define MSG_MOVE_AXIS "Mover Eixes"
	#define MSG_MOVE_X "Move X"
	#define MSG_MOVE_Y "Move Y"
	#define MSG_MOVE_Z "Move Z"
	#define MSG_MOVE_E "Extruder"
	#define MSG_MOVE_01MM "Move 0.1mm"
	#define MSG_MOVE_1MM "Move 1mm"
	#define MSG_MOVE_10MM "Move 10mm"
	#define MSG_SPEED "Velocidat"
	#define MSG_NOZZLE "Nozzle"
	#define MSG_NOZZLE1 "Nozzle2"
	#define MSG_NOZZLE2 "Nozzle3"
	#define MSG_BED "Base"
	#define MSG_FAN_SPEED "Ixoriador"
	#define MSG_FLOW "Fluxo"
	#define MSG_CONTROL "Control"
	#define MSG_MIN "\002 Min"
	#define MSG_MAX "\002 Max"
	#define MSG_FACTOR "\002 Fact"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "On"
	#define MSG_OFF "Off"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Acel"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ves-jerk"
	#define MSG_VMAX "Vmax"
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "y"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax"
	#define MSG_A_RETRACT "A-retrac."
	#define MSG_XSTEPS "X trangos/mm"
	#define MSG_YSTEPS "Y trangos/mm"
	#define MSG_ZSTEPS "Z trangos/mm"
	#define MSG_ESTEPS "E trangos/mm"
	#define MSG_RECTRACT "Retraer"
	#define MSG_TEMPERATURE "Temperatura"
	#define MSG_MOTION "Movimiento"
	#define MSG_STORE_EPROM "Alzar Memoria"
	#define MSG_LOAD_EPROM "Cargar Memoria"
	#define MSG_RESTORE_FAILSAFE "Rest. d'emerchen."
	#define MSG_REFRESH "Tornar a cargar"
	#define MSG_WATCH "Monitorizar"
	#define MSG_PREPARE "Preparar"
	#define MSG_TUNE "Achustar"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_PAUSE_PRINT "Pausar impresion"
	#define MSG_RESUME_PRINT "Contin. impresion"
	#define MSG_STOP_PRINT "Detener Impresion"
	#define MSG_CARD_MENU "Menu de SD"
	#define MSG_NO_CARD "No i hai tarcheta"
	#define MSG_DWELL "Reposo..."
	#define MSG_USERWAIT "Asperan. ordines"
	#define MSG_RESUMING "Contin. impresion"
	#define MSG_NO_MOVE "Sin movimiento"
	#define MSG_KILLED "ATURADA D'EMERCH."
	#define MSG_STOPPED "ATURADA."
	#define MSG_CONTROL_RETRACT  "Retraer mm"
	#define MSG_CONTROL_RETRACTF "Retraer  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Devantar mm"
	#define MSG_CONTROL_RETRACT_RECOVER "DesRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "DesRet F"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Cambear"
	#define MSG_INIT_SDCARD "Encetan. tarcheta"
	#define MSG_CNG_SDCARD "Cambiar tarcheta"
	#define MSG_RECTRACT_WIDE "Retraer"
	#define MSG_TEMPERATURE_WIDE "Temperatura"
	#define MSG_TEMPERATURE_RTN  "Temperatura"
	#define MSG_MAIN_WIDE "Menu Prencipal"
	#define MSG_MOTION_WIDE "Movimiento"
	#define MSG_PREPARE_ALT "Preparar"
	#define MSG_CONTROL_ARROW "Control"
	#define MSG_RETRACT_ARROW "Retraer"
	#define MSG_STEPPER_RELEASED "Desacoplada."
	#define MSG_ZPROBE_OUT "Z probe out. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y before Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystep X"
	#define MSG_BABYSTEP_Y "Babystep Y"
	#define MSG_BABYSTEP_Z "Babystep Z"
	#define MSG_ENDSTOP_ABORT "Endstop abort"
	#define MSG_CONTRAST "Contrast"
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif

#if LANGUAGE_CHOICE == 11 //Dutch

// LCD Menu Messages
// Please note these are limited to 17 characters!

	#define WELCOME_MSG MACHINE_NAME " gereed."
	#define MSG_SD_INSERTED "Kaart ingestoken"
	#define MSG_SD_REMOVED "Kaart verwijderd"
	#define MSG_MAIN "Main"
	#define MSG_BACK "Back"
	#define MSG_AUTOSTART "Autostart"
	#define MSG_DISABLE_STEPPERS "Motoren uit"
	#define MSG_AUTO_HOME "Auto home"
	#define MSG_SET_ORIGIN "Nulpunt instellen"
	#define MSG_PREHEAT_PLA "PLA voorverwarmen"
	#define MSG_PREHEAT_PLA_SETTINGS "PLA verw. conf"
	#define MSG_PREHEAT_ABS "ABS voorverwarmen"
	#define MSG_PREHEAT_ABS_SETTINGS "ABS verw. conf"
	#define MSG_COOLDOWN "Afkoelen"
	#define MSG_SWITCH_PS_ON "Stroom aan"
	#define MSG_SWITCH_PS_OFF "Stroom uit"
	#define MSG_EXTRUDE "Extrude"
	#define MSG_RETRACT "Retract"
	#define MSG_MOVE_AXIS "As verplaatsen"
	#define MSG_MOVE_X "Verplaats X"
	#define MSG_MOVE_Y "Verplaats Y"
	#define MSG_MOVE_Z "Verplaats Z"
	#define MSG_MOVE_E "Extruder"
	#define MSG_MOVE_01MM "Verplaats 0.1mm"
	#define MSG_MOVE_1MM "Verplaats 1mm"
	#define MSG_MOVE_10MM "Verplaats 10mm"
	#define MSG_SPEED "Snelheid"
	#define MSG_NOZZLE "Nozzle"
	#define MSG_NOZZLE1 "Nozzle2"
	#define MSG_NOZZLE2 "Nozzle3"
	#define MSG_BED "Bed"
	#define MSG_FAN_SPEED "Fan snelheid"
	#define MSG_FLOW "Flow"
	#define MSG_CONTROL "Control"
	#define MSG_MIN " \002 Min"
	#define MSG_MAX " \002 Max"
	#define MSG_FACTOR " \002 Fact"
	#define MSG_AUTOTEMP "Autotemp"
	#define MSG_ON "Aan "
	#define MSG_OFF "Uit"
	#define MSG_PID_P "PID-P"
	#define MSG_PID_I "PID-I"
	#define MSG_PID_D "PID-D"
	#define MSG_PID_C "PID-C"
	#define MSG_ACC  "Versn"
	#define MSG_VXY_JERK "Vxy-jerk"
	#define MSG_VZ_JERK "Vz-jerk"
	#define MSG_VE_JERK "Ve-jerk"
	#define MSG_VMAX "Vmax "
	#define MSG_X "x"
	#define MSG_Y "y"
	#define MSG_Z "z"
	#define MSG_E "e"
	#define MSG_VMIN "Vmin"
	#define MSG_VTRAV_MIN "VTrav min"
	#define MSG_AMAX "Amax "
	#define MSG_A_RETRACT "A-retract"
	#define MSG_XSTEPS "Xsteps/mm"
	#define MSG_YSTEPS "Ysteps/mm"
	#define MSG_ZSTEPS "Zsteps/mm"
	#define MSG_ESTEPS "Esteps/mm"
	#define MSG_RECTRACT "Terugtrekken"
	#define MSG_TEMPERATURE "Temperatuur"
	#define MSG_MOTION "Beweging"
	#define MSG_CONTRAST "LCD contrast"
	#define MSG_STORE_EPROM "Geheugen opslaan"
	#define MSG_LOAD_EPROM "Geheugen laden"
	#define MSG_RESTORE_FAILSAFE "Noodstop reset"
	#define MSG_REFRESH "Ververs"
	#define MSG_WATCH "Info scherm"
	#define MSG_PREPARE "Voorbereiden"
	#define MSG_TUNE "Afstellen"
	#define MSG_PAUSED "Press to resume"
	#define MSG_PAUSING "Pausing..."
	#define MSG_PRINTING "Printing..."
	#define MSG_READY_UNLOAD "Press & unload fil."
	#define MSG_UNLOAD_CLICK "Press to continue"
	#define MSG_LOAD_CLICK "Load new filament"
	#define MSG_PAUSE_PRINT "Print pauzeren"
	#define MSG_RESUME_PRINT "Print hervatten"
	#define MSG_STOP_PRINT "Print stoppen"
	#define MSG_CARD_MENU "Print van SD"
	#define MSG_NO_CARD "Geen SD kaart"
	#define MSG_DWELL "Slapen..."
	#define MSG_USERWAIT "Wachten..."
	#define MSG_RESUMING "Print hervatten"
	#define MSG_NO_MOVE "Geen beweging."
	#define MSG_KILLED "AFGEBROKEN. "
	#define MSG_STOPPED "GESTOPT. "
	#define MSG_CONTROL_RETRACT  "Retract mm"
	#define MSG_CONTROL_RETRACTF "Retract  F"
	#define MSG_CONTROL_RETRACT_ZLIFT "Hop mm"
	#define MSG_CONTROL_RETRACT_RECOVER "UnRet +mm"
	#define MSG_CONTROL_RETRACT_RECOVERF "UnRet  F"
	#define MSG_AUTORETRACT "AutoRetr."
	#define MSG_FILAMENTCHANGE "Verv. Filament"
	#define MSG_INIT_SDCARD "Init. SD kaart"
	#define MSG_CNG_SDCARD "Verv. SD card"
	#define MSG_ZPROBE_OUT "Z probe uit. bed"
	#define MSG_POSITION_UNKNOWN "Home X/Y voor Z"
	#define MSG_ZPROBE_ZOFFSET "Z Offset"
	#define MSG_BABYSTEP_X "Babystap X"
	#define MSG_BABYSTEP_Y "Babystap Y"
	#define MSG_BABYSTEP_Z "Babystap Z"
	#define MSG_ENDSTOP_ABORT "Endstop afbr."
	#define MSG_END_HOUR "hours"
	#define MSG_END_MINUTE "minutes"

	#ifdef WITBOX

		#define MSG_FILAMENT "Filament"
		#define MSG_LEVEL_PLATE "Level plate"
		#define MSG_START_SCRIPT "Start script"
		#define MSG_PREHEAT "Preheat"
		#define MSG_JOG "Jog"
		#define MSG_LOAD "Load"
		#define MSG_UNLOAD "Unload"
		#define MSG_ABORT "Abort" 
		#define MSG_PRE_EXTRUD "Insert & Press"      
		#define MSG_EXTRUDING "Extruding..." 
		#define MSG_LENGTH "Length:"         
		#define MSG_RETRACTING "Retracting"
		#define MSG_WELLCOME "bq Witbox"

		#define MSG_LP_COOL_1 "Cooling..."
		#define MSG_LP_COOL_2 "Temp:"
		#define MSG_LP_COOL_3 "   Press to abort"
		#define MSG_LB_COOL_1 "Cooling..."
		#define MSG_LB_COOL_2 "Temp:"

		#define MSG_CF_HEAT_1 "Heating..."
		#define MSG_CF_HEAT_2 "Temp:"

		#define MSG_EXIT "Press to abort..."


		#define MSG_WIZARD_LEVELBED_0_1 		" Leveling plate...  "
		#define MSG_WIZARD_LEVELBED_0_2			"   Press to start   "

		#define MSG_WIZARD_LEVELBED_1_1 		" Adjust first point "
		#define MSG_WIZARD_LEVELBED_1_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_2_1 		"Adjust second point "
		#define MSG_WIZARD_LEVELBED_2_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_3_1 		" Adjust third point "
		#define MSG_WIZARD_LEVELBED_3_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_4_1 		"Adjust fourth point "
		#define MSG_WIZARD_LEVELBED_4_2 		" & Press the button "

		#define MSG_WIZARD_LEVELBED_5_1 		"     Is it ok?      "
		
		#define MSG_WIZARD_LEVELBED_6_1 		"   Plate leveled!   "


		#define MSG_WIZARD_CHANGEFILAMENT_0_0	"Press the button to "
		#define MSG_WIZARD_CHANGEFILAMENT_0_1	" start the process  "
		#define MSG_WIZARD_CHANGEFILAMENT_0_2	"and extract filament"

		#define MSG_WIZARD_CHANGEFILAMENT_1_0	" Pull the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_1_1	"quickly when it has "
		#define MSG_WIZARD_CHANGEFILAMENT_1_2	" stopped extruding  "

		#define MSG_WIZARD_CHANGEFILAMENT_2_0	"   Insert the new   "
		#define MSG_WIZARD_CHANGEFILAMENT_2_1	" filament and press "
		#define MSG_WIZARD_CHANGEFILAMENT_2_2   "     the button     "

		#define MSG_WIZARD_CHANGEFILAMENT_3_0	" When the filament  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_1	"extrudes, press the "
		#define MSG_WIZARD_CHANGEFILAMENT_3_2	"  button to resume  "
		#define MSG_WIZARD_CHANGEFILAMENT_3_3	"      printing      "

		#define MSG_SD_BAD_FILENAME "Bad filename!"
	#endif // WITBOX
#endif

#endif // ifndef LANGUAGE_H
