#ifndef _TFT_LANGUAGE_T_CN_H
#define _TFT_LANGUAGE_T_CN_H
//***************繁体中文**********************//
#define TOOL_TEXT_T_CN							"工具"
#define PREHEAT_TEXT_T_CN 					    "預熱"
#define	MOVE_TEXT_T_CN							"移動"
#define HOME_TEXT_T_CN  						"回零"
#define PRINT_TEXT_T_CN							"打印"
#define EXTRUDE_TEXT_T_CN 					    "擠出"
#define LEVELING_TEXT_T_CN 					    "調平"
#define AUTO_LEVELING_TEXT_T_CN 		        "自動調平"
#define SET_TEXT_T_CN							"設置"
#define MORE_TEXT_T_CN     					    "更多"

#define ADD_TEXT_T_CN			    "增加"
#define DEC_TEXT_T_CN			    "減少"
#define EXTRUDER_1_TEXT_T_CN		"噴頭1"
#define EXTRUDER_2_TEXT_T_CN		"噴頭2"
#define HEATBED_TEXT_T_CN			"熱床"
#define TEXT_1C_T_CN				"1℃"
#define TEXT_5C_T_CN				"5℃"
#define TEXT_10C_T_CN				"10℃"
#define CLOSE_TEXT_T_CN				"關閉"

#define BACK_TEXT_T_CN					    "返回"

#define TOOL_PREHEAT_T_CN            "預熱"
#define TOOL_EXTRUDE_T_CN             "擠出"
#define TOOL_MOVE_T_CN                "移動"
#define TOOL_HOME_T_CN                "回零"
#define TOOL_LEVELING_T_CN               "調平"
#define TOOL_AUTO_LEVELING_T_CN         "自動調平"
#define TOOL_FILAMENT_T_CN                "換料"
#define TOOL_MORE_T_CN                    "更多"

#define AXIS_X_ADD_TEXT_T_CN				"X+"
#define AXIS_X_DEC_TEXT_T_CN				"X-"
#define AXIS_Y_ADD_TEXT_T_CN				"Y+"
#define AXIS_Y_DEC_TEXT_T_CN				"Y-"
#define AXIS_Z_ADD_TEXT_T_CN				"Z+"
#define AXIS_Z_DEC_TEXT_T_CN				"Z-"
#define TEXT_01MM_T_CN						"0.1mm"
#define TEXT_1MM_T_CN						"1mm"
#define TEXT_10MM_T_CN						"10mm"

#define HOME_X_TEXT_T_CN					"X"
#define HOME_Y_TEXT_T_CN					"Y"
#define HOME_Z_TEXT_T_CN					"Z"
#define HOME_ALL_TEXT_T_CN					"回零"
#define HOME_STOPMOVE_T_CN                  "急停"

#define PAGE_UP_TEXT_T_CN					"上一頁"
#define PAGE_DOWN_TEXT_T_CN				    "下一頁"

#define EXTRUDER_IN_TEXT_T_CN		    "進料"
#define EXTRUDER_OUT_TEXT_T_CN		    "退料"
#define EXTRUDE_1MM_TEXT_T_CN			"1mm"
#define EXTRUDE_5MM_TEXT_T_CN			"5mm"
#define EXTRUDE_10MM_TEXT_T_CN		    "10mm"
#define EXTRUDE_LOW_SPEED_TEXT_T_CN		"低速"
#define EXTRUDE_MEDIUM_SPEED_TEXT_T_CN	"常速"
#define EXTRUDE_HIGH_SPEED_TEXT_T_CN	"高速"

#define LEVELING_POINT1_TEXT_T_CN				"第一點"
#define LEVELING_POINT2_TEXT_T_CN				"第二點"
#define LEVELING_POINT3_TEXT_T_CN				"第三點"
#define LEVELING_POINT4_TEXT_T_CN				"第四點"
#define LEVELING_POINT5_TEXT_T_CN				"第五點"

#define FILESYS_TEXT_T_CN							"文件系統"
#define WIFI_TEXT_T_CN								"WIFI"
#define FAN_TEXT_T_CN								"風扇"
#define ABOUT_TEXT_T_CN								"關於"
#define BREAK_POINT_TEXT_T_CN						"斷點續打"
#define FILAMENT_TEXT_T_CN							"換料"
#define LANGUAGE_TEXT_T_CN							"語言"
#define MOTOR_OFF_TEXT_T_CN							"關閉電機"
#define MOTOR_OFF_XY_TEXT_T_CN    "關閉XY"
#define SHUTDOWN_TEXT_T_CN							"關機"

#define U_DISK_TEXT_T_CN							"U盤"
#define SD_CARD_TEXT_T_CN							"SD卡"
#define WIFI_NAME_TEXT_T_CN							"無線網絡:"
#define WIFI_KEY_TEXT_T_CN							"密碼: "
#define WIFI_IP_TEXT_T_CN							"IP: "
#define WIFI_AP_TEXT_T_CN							"狀態: AP"
#define WIFI_STA_TEXT_T_CN							"狀態: STA"
#define WIFI_CONNECTED_TEXT_T_CN				    "已連接"
#define WIFI_DISCONNECTED_TEXT_T_CN			        "未連接"
#define WIFI_EXCEPTION_TEXT_T_CN				    "模塊異常"
#define CLOUD_TEXT_T_CN								"雲服務"
#define CLOUD_BIND_T_CN								"已綁定"
#define CLOUD_UNBIND_T_CN							"解綁"
#define CLOUD_UNBINDING_T_CN					    "解绑中"
#define CLOUD_DISCONNECTED_T_CN				        "未連接"
#define CLOUD_UNBINDED_T_CN						    "未綁定"
#define CLOUD_BINDED_T_CN							"已綁定"
#define CLOUD_DISABLE_T_CN						    "已禁用"

#define FAN_ADD_TEXT_T_CN							"增加"
#define FAN_DEC_TEXT_T_CN							"減少"
#define FAN_OPEN_TEXT_T_CN							"100%"
#define FAN_HALF_TEXT_T_CN							"50%"
#define FAN_CLOSE_TEXT_T_CN							"關閉"
#define FAN_TIPS1_TEXT_T_CN							"風扇"
#define FAN_TIPS2_TEXT_T_CN							"FAN\nClose"

#define FILAMENT_IN_TEXT_T_CN					"進料"
#define FILAMENT_OUT_TEXT_T_CN					"退料"
#define FILAMENT_EXT0_TEXT_T_CN					"噴頭1"
#define FILAMENT_EXT1_TEXT_T_CN					"噴頭2"
#define FILAMENT_HEAT_TEXT_T_CN					"預熱"					
#define FILAMENT_STOP_TEXT_T_CN					"停止"
//#define FILAMENT_CHANGE_TEXT_T_CN				"準備換料"
#define FILAMENT_TIPS2_TEXT_T_CN				"T:"
#define FILAMENT_TIPS3_TEXT_T_CN				"正在進料"
#define FILAMENT_TIPS4_TEXT_T_CN				"正在退料"
#define FILAMENT_TIPS5_TEXT_T_CN				"溫度太低,請先預熱"
#define FILAMENT_TIPS6_TEXT_T_CN				"換料完成"

#if 0
  #define FILAMENT_REPLAYS_IDLE_TEXT_T_CN         "請按<進料>或<退料>進行換料!"
  #define FILAMENT_CHANGE_TEXT_T_CN				"待打印機暫停后,請按<進料>或<退料>進行換料!"

#endif


  #define FILAMENT_CHANGE_TEXT_T_CN				"待打印機暫停后,\n請按<進料>或<退料>"



#define FILAMENT_DIALOG_LOAD_HEAT_TIPS_T_CN		"準備進料,正在加熱,請稍等"
#define FILAMENT_DIALOG_UNLOAD_HEAT_TIPS_T_CN		"準備退料,正在加熱,請稍等"
#define FILAMENT_DIALOG_LOAD_CONFIRM1_TIPS_T_CN           "加熱完成,請裝載耗材后,按<確定>開始進料"
#define FILAMENT_DIALOG_LOAD_CONFIRM2_TIPS_T_CN           "請裝載耗,按<確定>開始進料!"
#define FILAMENT_DIALOG_UNLOAD_CONFIRM_TIPS_T_CN          "加熱完成,请按<確定>開始退料!"
#define FILAMENT_DIALOG_LOADING_TIPS_T_CN                 "正在進料,请等待耗材加載完成!"
#define FILAMENT_DIALOG_UNLOADING_TIPS_T_CN               "正在退料,请等待耗材卸載完成!"
#define FILAMENT_DIALOG_LOAD_COMPLETE_TIPS_T_CN           "進料完成,请按<確定>返回"
#define FILAMENT_DIALOG_UNLOAD_COMPLETE_TIPS_T_CN         "退料完成,请按<確定>返回"

#define PRE_HEAT_EXT_TEXT_T_CN					"噴頭"
#define PRE_HEAT_BED_TEXT_T_CN					"熱床"

#define FILE_LOADING_T_CN					"正在載入......"
#define NO_FILE_AND_CHECK_T_CN					"無文件!請插入sd卡/u盤!"
#define NO_FILE_T_CN					"無文件!"

#define EXTRUDER_TEMP_TEXT_T_CN		    "溫度"
#define EXTRUDER_E_LENGTH1_TEXT_T_CN    "噴頭"
#define EXTRUDER_E_LENGTH2_TEXT_T_CN    "噴頭"
#define EXTRUDER_E_LENGTH3_TEXT_T_CN    "噴頭"

#define ABOUT_TYPE_TEXT_T_CN			"Type: "
#define ABOUT_VERSION_TEXT_T_CN			"Firmware: "
#define ABOUT_WIFI_TEXT_T_CN			"Wifi: "

#define PRINTING_OPERATION_T_CN		    "操作"
#define PRINTING_PAUSE_T_CN				"暫停"
#define PRINTING_TEMP_T_CN				"溫度"
#define PRINTING_CHANGESPEED_T_CN		"變速"
#define PRINTING_RESUME_T_CN			"恢復"
#define PRINTING_STOP_T_CN				"停止"
#define PRINTING_MORE_T_CN				"更多"
#define PRINTING_EXTRUDER_T_CN			"擠出"
#define PRINTING_MOVE_T_CN              "移動"

#define EXTRUDER_SPEED_T_CN				"擠出"
#define MOVE_SPEED_T_CN					"移動"
#define EXTRUDER_SPEED_STATE_T_CN		"擠出速度"
#define MOVE_SPEED_STATE_T_CN			"移動速度"
#define STEP_1PERCENT_T_CN				"1%%"
#define STEP_5PERCENT_T_CN				"5%%"
#define STEP_10PERCENT_T_CN				"10%%"

#define ZOFFSET_T_CN                          "Z Offset"
#define ZOFFSET_INC_T_CN                       "增加"
#define ZOFFSET_DEC_T_CN                        "減少"

#define TITLE_READYPRINT_T_CN				    "準備打印"
#define TITLE_PREHEAT_T_CN						"預熱"
#define TITLE_MOVE_T_CN					        "移動"
#define TITLE_HOME_T_CN							"回零"
#define TITLE_EXTRUDE_T_CN						"擠出"
#define TITLE_LEVELING_T_CN						"調平"
#define TITLE_SET_T_CN							"設置"
#define TITLE_MORE_T_CN							"更多"
#define TITLE_CHOOSEFILE_T_CN					"選擇文件"
#define TITLE_PRINTING_T_CN						"正在打印"
#define TITLE_OPERATION_T_CN					"操作"
#define TITLE_ADJUST_T_CN						"調整"
#define	TITLE_WIRELESS_T_CN						"無線網絡"
#define	TITLE_FILAMENT_T_CN						"換料"
#define TITLE_ABOUT_T_CN						"關於"
#define TITLE_FAN_T_CN							"風扇"
#define TITLE_LANGUAGE_T_CN						"語言"
#define TITLE_PAUSE_T_CN						"暫停"
#define TITLE_CHANGESPEED_T_CN				    "變速"
#define TITLE_CLOUD_TEXT_T_CN				        "雲服務"
#define TITLE_DIALOG_CONFIRM_T_CN					"確認"
#define TITLE_FILESYS_T_CN								"文件系統"
#define TITLE_ZOFFSET_T_CN                    "Z Offset"

#define AUTO_SHUTDOWN_T_CN				"自動關機"
#define MANUAL_SHUTDOWN_T_CN			"手動關機"

#define DIALOG_CONFIRM_T_CN				"確定"
#define DIALOG_CANCLE_T_CN				"取消"
#define DIALOG_OK_T_CN					"確認"
#define DIALOG_RESET_T_CN				"重設"
#define DIALOG_RETRY_T_CN				"重試"
#define DIALOG_DISABLE_T_CN				"禁用"
#define DIALOG_PRINT_MODEL_T_CN			"打印模型?"
#define DIALOG_CANCEL_PRINT_T_CN		"停止打印?"
#define DIALOG_RETRY_T_CN									"重試"
#define DIALOG_STOP_T_CN									"停止"
#define DIALOG_REPRINT_FROM_BREAKPOINT_T_CN	                "從斷點續打?"
//#define DIALOG_UNBIND_PRINTER_T_CN						    "解除綁定?"
#define DIALOG_ERROR_TIPS1_T_CN								"錯誤:找不到文件,請插入sd卡/u盤!"
#define DIALOG_ERROR_TIPS2_T_CN								"錯誤:通信失敗,請檢查波特率或主板硬件!"
#define DIALOG_ERROR_TIPS3_T_CN								"錯誤:文件名或文件路徑太長!"
#define DIALOG_CLOSE_MACHINE_T_CN             "正在關機......"
#define DIALOG_UNBIND_PRINTER_T_CN            "解除綁定?"
#define DIALOG_FILAMENT_NO_PRESS_T_CN         "請先裝載耗材!"
#define DIALOG_PRINT_FINISH_T_CN              "打印完成!"
#define DIALOG_PRINT_TIME_T_CN              "打印時間: "
#define DIALOG_REPRINT_T_CN                "再打印壹次"
#define DIALOG_WIFI_ENABLE_TIPS_T_CN "wifi模塊正在配置中,請稍等......"

#define TEXT_VALUE_T_CN                  "%d℃/%d℃"
#define EXTRUDE_TEXT_VALUE_T_T_CN								": %d℃"
#define WIFI_RECONNECT_TEXT_T_CN         "重新連接"

#define MESSEGE_PAUSING_T_CN			"暫停中..."
#define MESSEGE_CHANGING_T_CN			"等待換料開始..."
#define MESSEGE_UNLOAD_T_CN			"退料中,請稍等..."
#define MESSEGE_WAITING_T_CN			"點擊按鈕恢復打印"
#define MESSEGE_INSERT_T_CN			"裝載耗材後,點擊按鈕開始打印"
#define MESSEGE_LOAD_T_CN			"進料中,請稍等..."
#define MESSEGE_PURGE_T_CN			"等待擠出..."
#define MESSEGE_RESUME_T_CN			"等待恢復打印..."
#define MESSEGE_HEAT_T_CN			"按下按鈕,加熱噴頭"
#define MESSEGE_HEATING_T_CN			"噴頭加熱中,請等待..."
#define MESSEGE_OPTION_T_CN			"擠出更多還是繼續打印"
#define MESSEGE_PURGE_MORE_T_CN   "擠出"
#define MESSEGE_CONTINUE_PRINT_T_CN   "打印"

#endif