#!/usr/bin/env bash
#
# Build tests for STM32F1 ARMED
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
use_example_configs ArmEd
opt_set X_DRIVER_TYPE TMC2130 Y_DRIVER_TYPE TMC2208
exec_test $1 $2 "ArmEd Example Configuration with mixed TMC Drivers" "$3"

# clean up
restore_configs
