#!/usr/bin/env bash
#
# Build tests for AT90USB1286 ARMED
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BRAINWAVE_PRO
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
