#!/usr/bin/env bash
#
# Build tests for BTT_SKR_SE_BX
#

# exit on first failure
set -e

#
# Build with the default configurations
#
use_example_configs BIQU/BX
exec_test $1 $2 "BIQU/BX" "$3"

# clean up
restore_configs
