#!/usr/bin/env bash
#
# Build tests for BTT_SKR_SE_BX
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_SE_BX
opt_set SERIAL_PORT 1
exec_test $1 $2 "Default Configuration" "$3"

# clean up
restore_configs
