#!/usr/bin/env bash
#
# Build tests for FLYF407ZG
#

# exit on first failure
set -e

# Build examples
restore_configs
opt_set MOTHERBOARD BOARD_FLYF407ZG SERIAL_PORT -1 X_DRIVER_TYPE TMC2208 Y_DRIVER_TYPE TMC2130
exec_test $1 $2 "FLYF407ZG Default Config with mixed TMC Drivers" "$3"

# cleanup
restore_configs
