#!/usr/bin/env bash
#
# Build tests for AVR ATmega FYSETC F6 1.3
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_FYSETC_F6_13
opt_enable DGUS_LCD_UI_FYSETC
exec_test $1 $2 "FYSETC F6 1.3 with DGUS"

# clean up
restore_configs
