#!/usr/bin/env bash
#
# Build tests for FYSETC_S6
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs FYSETC/S6
opt_enable MEATPACK_ON_SERIAL_PORT_1
opt_set Y_DRIVER_TYPE TMC2209 Z_DRIVER_TYPE TMC2130
exec_test $1 $2 "FYSETC S6 Example" "$3"

# cleanup
restore_configs
