#!/usr/bin/env bash
#
# Build tests for GD32F303RE_creality_mfl
#

# exit on first failure
set -e

restore_configs
opt_set MOTHERBOARD BOARD_MFL_CREALITY_V422 SERIAL_PORT 1
opt_enable EEPROM_SETTINGS EEPROM_CHITCHAT SDSUPPORT \
           PAREN_COMMENTS GCODE_MOTION_MODES SINGLENOZZLE \
           EMERGENCY_PARSER PINS_DEBUGGING \
           CLASSIC_JERK BABYSTEPPING AUTO_BED_LEVELING_BILINEAR \
           PROBE_MANUALLY FAN_SOFT_PWM
opt_add NO_CREALITY_422_DRIVER_WARNING
opt_add NO_AUTO_ASSIGN_WARNING
exec_test $1 $2 "Creality V4.2.2 MFL GD32 Default Configuration" "$3"

# cleanup
restore_configs
