#!/usr/bin/env bash
#
# Build tests for Index_Mobo_Rev03
#

# exit on first failure
set -e

use_example_configs Index/REV_03
exec_test $1 $2 "Index REV03 Pick and Place" "$3"

# cleanup
restore_configs
