#!/usr/bin/env bash
#
# Build tests for STM32F103ZE JGAurora A5S A1
#

# exit on first failure
set -e

#
# Build with the default configurations
#
use_example_configs JGAurora/A5S
exec_test $1 $2 "JGAurora/A5S Configuration"

# clean up
restore_configs
