#!/usr/bin/env bash
#
# Build tests for Linux x86_64
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_LINUX_RAMPS
opt_set TEMP_SENSOR_BED 1
opt_enable PIDTEMPBED EEPROM_SETTINGS BAUD_RATE_GCODE
exec_test $1 $2 "Linux with EEPROM" "$3"

# cleanup
restore_configs
