#!/usr/bin/env bash
#
# Build tests for STM32F070CB Malyan M300
#

# exit on first failure
set -e

restore_configs
use_example_configs "delta/Malyan M300"
opt_disable AUTO_BED_LEVELING_3POINT
opt_set LCD_SERIAL_PORT 1
exec_test $1 $2 "Malyan M300 (delta)" "$3"

# cleanup
restore_configs
