#!/usr/bin/env bash
#
# Build tests for AVR ATmega2560
#

# exit on first failure
set -e

#
# Build with the default configurations
#
#restore_configs
#exec_test $1 $2 "Default Configuration" "$3"

#
# Test a probeless build of AUTO_BED_LEVELING_UBL, with lots of extruders
#
use_example_configs AnimationExample
opt_set SHOW_CUSTOM_BOOTSCREEN
opt_set MOTHERBOARD BOARD_AZTEEG_X3_PRO
opt_set LCD_LANGUAGE fr
opt_set EXTRUDERS 5
opt_set TEMP_SENSOR_1 1
opt_set TEMP_SENSOR_2 5
opt_set TEMP_SENSOR_3 20
opt_set TEMP_SENSOR_4 1000
opt_set TEMP_SENSOR_BED 1
opt_enable AUTO_BED_LEVELING_UBL RESTORE_LEVELING_AFTER_G28 DEBUG_LEVELING_FEATURE G26_MESH_VALIDATION ENABLE_LEVELING_FADE_HEIGHT SKEW_CORRECTION \
           REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER LIGHTWEIGHT_UI STATUS_MESSAGE_SCROLLING BOOT_MARLIN_LOGO_SMALL \
           SDSUPPORT SDCARD_SORT_ALPHA USB_FLASH_DRIVE_SUPPORT SCROLL_LONG_FILENAMES CANCEL_OBJECTS SOUND_MENU_ITEM \
           EEPROM_SETTINGS EEPROM_CHITCHAT GCODE_MACROS CUSTOM_USER_MENUS \
           MULTI_NOZZLE_DUPLICATION CLASSIC_JERK LIN_ADVANCE EXTRA_LIN_ADVANCE_K QUICK_HOME \
           LCD_SET_PROGRESS_MANUALLY PRINT_PROGRESS_SHOW_DECIMALS SHOW_REMAINING_TIME \
           BABYSTEPPING BABYSTEP_XY NANODLP_Z_SYNC I2C_POSITION_ENCODERS M114_DETAIL
exec_test $1 $2 "Azteeg X3 Pro | EXTRUDERS 5 | RRDFGSC | UBL | LIN_ADVANCE ..." "$3"

#
# Add a Sled Z Probe, use UBL Cartesian moves, use Japanese language
#
use_example_configs AnimationExample
opt_set SHOW_CUSTOM_BOOTSCREEN
opt_set MOTHERBOARD BOARD_AZTEEG_X3_PRO
opt_set LCD_LANGUAGE fr
opt_set EXTRUDERS 5
opt_set TEMP_SENSOR_1 1
opt_set TEMP_SENSOR_2 5
opt_set TEMP_SENSOR_3 20
opt_set TEMP_SENSOR_4 1000
opt_set TEMP_SENSOR_BED 1
opt_enable AUTO_BED_LEVELING_UBL RESTORE_LEVELING_AFTER_G28 DEBUG_LEVELING_FEATURE G26_MESH_VALIDATION ENABLE_LEVELING_FADE_HEIGHT SKEW_CORRECTION \
           REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER LIGHTWEIGHT_UI STATUS_MESSAGE_SCROLLING BOOT_MARLIN_LOGO_SMALL \
           SDSUPPORT SDCARD_SORT_ALPHA USB_FLASH_DRIVE_SUPPORT SCROLL_LONG_FILENAMES CANCEL_OBJECTS NO_SD_AUTOSTART \
           EEPROM_SETTINGS EEPROM_CHITCHAT GCODE_MACROS CUSTOM_USER_MENUS \
           MULTI_NOZZLE_DUPLICATION CLASSIC_JERK LIN_ADVANCE QUICK_HOME \
           LCD_SET_PROGRESS_MANUALLY PRINT_PROGRESS_SHOW_DECIMALS SHOW_REMAINING_TIME \
           BABYSTEPPING BABYSTEP_XY NANODLP_Z_SYNC I2C_POSITION_ENCODERS M114_DETAIL \
           Z_PROBE_SLED SKEW_CORRECTION SKEW_CORRECTION_FOR_Z SKEW_CORRECTION_GCODE
opt_set LCD_LANGUAGE jp_kana
opt_disable SEGMENT_LEVELED_MOVES
opt_enable BABYSTEPPING BABYSTEP_XY BABYSTEP_ZPROBE_OFFSET DOUBLECLICK_FOR_Z_BABYSTEPPING BABYSTEP_HOTEND_Z_OFFSET BABYSTEP_DISPLAY_TOTAL M114_DETAIL
exec_test $1 $2 "Azteeg X3 Pro | EXTRUDERS 5 | RRDFGSC | UBL | LIN_ADVANCE | Sled Probe | Skew | JP-Kana | Babystep offsets ..." "$3"


#
# 5 runout sensors with distinct states
#
restore_configs
opt_set MOTHERBOARD BOARD_AZTEEG_X3_PRO
opt_set EXTRUDERS 5
opt_set NUM_SERVOS 1
opt_set TEMP_SENSOR_1 1
opt_set TEMP_SENSOR_2 1
opt_set TEMP_SENSOR_3 1
opt_set TEMP_SENSOR_4 1
opt_enable VIKI2 Z_PROBE_SERVO_NR Z_SERVO_ANGLES DEACTIVATE_SERVOS_AFTER_MOVE BOOT_MARLIN_LOGO_ANIMATED \
           AUTO_BED_LEVELING_3POINT DEBUG_LEVELING_FEATURE EEPROM_SETTINGS EEPROM_CHITCHAT M114_DETAIL \
           NO_VOLUMETRICS EXTENDED_CAPABILITIES_REPORT AUTO_REPORT_TEMPERATURES AUTOTEMP G38_PROBE_TARGET JOYSTICK \
           DIRECT_STEPPING DETECT_BROKEN_ENDSTOP \
           FILAMENT_RUNOUT_SENSOR NOZZLE_PARK_FEATURE ADVANCED_PAUSE_FEATURE Z_SAFE_HOMING FIL_RUNOUT3_PULLUP
opt_set NUM_RUNOUT_SENSORS 5
opt_set FIL_RUNOUT2_PIN 44
opt_set FIL_RUNOUT3_PIN 45
opt_set FIL_RUNOUT3_STATE HIGH
opt_set FIL_RUNOUT4_PIN 46
opt_set FIL_RUNOUT5_PIN 47
exec_test $1 $2 "Multiple runout sensors (x5) | Distinct runout states" "$3"


#
# Mixing Extruder with 5 steppers, Greek
#
restore_configs
opt_set MOTHERBOARD BOARD_AZTEEG_X3_PRO
opt_set LCD_LANGUAGE el_gr
opt_enable MIXING_EXTRUDER GRADIENT_MIX GRADIENT_VTOOL CR10_STOCKDISPLAY \
           USE_CONTROLLER_FAN CONTROLLER_FAN_EDITABLE CONTROLLER_FAN_IGNORE_Z
opt_set MIXING_STEPPERS 5
opt_set LCD_LANGUAGE ru
exec_test $1 $2 "Azteeg X3 | Mixing Extruder (x5) | Gradient Mix | Greek" "$3"

#
# Test SPEAKER with BOARD_BQ_ZUM_MEGA_3D and BQ_LCD_SMART_CONTROLLER
#
#restore_configs
#opt_set MOTHERBOARD BOARD_BQ_ZUM_MEGA_3D
#opt_set LCD_FEEDBACK_FREQUENCY_DURATION_MS 10
#opt_set LCD_FEEDBACK_FREQUENCY_HZ 100
#opt_enable BQ_LCD_SMART_CONTROLLER SPEAKER

#
# Enable COREXY
#
#restore_configs
#opt_enable COREXY
#exec_test $1 $2 "Stuff" "$3"

######## Other Standard LCD/Panels ##############
#
# ULTRA_LCD
#
#restore_configs
#opt_enable ULTRA_LCD
#exec_test $1 $2 "Stuff" "$3"
#
# DOGLCD
#
#restore_configs
#opt_enable DOGLCD
#exec_test $1 $2 "Stuff" "$3"
#
# MAKRPANEL
# Needs to use Melzi and Sanguino hardware
#
#restore_configs
#opt_enable MAKRPANEL
#exec_test $1 $2 "Stuff" "$3"
#
# REPRAP_DISCOUNT_SMART_CONTROLLER, SDSUPPORT, BABYSTEPPING, RIGIDBOARD_V2, and DAC_MOTOR_CURRENT_DEFAULT
#
#restore_configs
#opt_set MOTHERBOARD BOARD_RIGIDBOARD_V2
#opt_enable REPRAP_DISCOUNT_SMART_CONTROLLER SDSUPPORT BABYSTEPPING DAC_MOTOR_CURRENT_DEFAULT
#exec_test $1 $2 "Stuff" "$3"
# #
# G3D_PANEL with SDCARD_SORT_ALPHA and STATUS_MESSAGE_SCROLLING
#
#restore_configs
#opt_enable G3D_PANEL SDSUPPORT SDCARD_SORT_ALPHA STATUS_MESSAGE_SCROLLING SCROLL_LONG_FILENAMES
#opt_set SDSORT_GCODE true
#opt_set SDSORT_USES_RAM true
#opt_set SDSORT_USES_STACK true
#opt_set SDSORT_CACHE_NAMES true
#exec_test $1 $2 "Stuff" "$3"
#
# REPRAPWORLD_KEYPAD
#
# Cant find configuration details to get it to compile
#restore_configs
#opt_enable ULTRA_LCD REPRAPWORLD_KEYPAD REPRAPWORLD_KEYPAD_MOVE_STEP
#exec_test $1 $2 "Stuff" "$3"
#
# RA_CONTROL_PANEL
#
#restore_configs
#opt_enable RA_CONTROL_PANEL PINS_DEBUGGING
#exec_test $1 $2 "Stuff" "$3"

######## I2C LCD/PANELS ##############
#
# !!!ATTENTION!!!
# Most I2C configurations are failing at the moment because they require
# a different Liquid Crystal library "LiquidTWI2".
#
# LCD_SAINSMART_I2C_1602
#
#restore_configs
#opt_enable LCD_SAINSMART_I2C_1602
#exec_test $1 $2 "Stuff" "$3"
#
# LCD_I2C_PANELOLU2
#
#restore_configs
#opt_enable LCD_I2C_PANELOLU2
#exec_test $1 $2 "Stuff" "$3"
#
# LCD_I2C_VIKI
#
#restore_configs
#opt_enable LCD_I2C_VIKI
#exec_test $1 $2 "Stuff" "$3"
#
# LCM1602
#
#restore_configs
#opt_enable LCM1602
#exec_test $1 $2 "Stuff" "$3"

#
# Language files test with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#
#restore_configs
#opt_enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER SDSUPPORT
#for lang in an bg ca cz da de el el_gr en es eu fi fr gl hr hu it jp_kana nl pl pt pt_br ro ru sk sv tr uk vi zh_CN zh_TW test; do opt_set LCD_LANGUAGE $lang; echo "compile with language $lang ..."; exec_test $1 $2 "Stuff" "$3"; done
#
#restore_configs
#opt_enable REPRAP_DISCOUNT_SMART_CONTROLLER SDSUPPORT
#for lang in an bg ca cz da de el el_gr en es eu fi fr gl hr hu it jp_kana nl pl pt pt_br ro ru sk sv tr uk vi zh_CN zh_TW test; do opt_set LCD_LANGUAGE $lang; echo "compile with language $lang ..."; exec_test $1 $2 "Stuff" "$3"; done

######## Example Configurations ##############
#
# Test a basic DUAL_X_CARRIAGE configuration
#
use_example_configs Formbot/T_Rex_3
exec_test $1 $2 "Formbot/T_Rex_3 example configuration." "$3"

#
# BQ Hephestos 2
#restore_configs
#use_example_configs BQ/Hephestos_2
#exec_test $1 $2 "Stuff" "$3"

#
# Makibox Config  need to check board type for Teensy++ 2.0
#
#use_example_configs makibox
#exec_test $1 $2 "Stuff" "$3"

#
# tvrrug Config need to check board type for sanguino atmega644p
#
#use_example_configs tvrrug/Round2
#exec_test $1 $2 "Stuff" "$3"

# clean up
restore_configs
