#!/usr/bin/env bash
#
# Build tests for MKS Robin nano
# (STM32F1 genericSTM32F103VE)
#

# exit on first failure
set -e

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO
opt_disable TFT_320x240
opt_enable TOUCH_SCREEN
opt_enable FSMC_GRAPHICAL_TFT
exec_test $1 $2 "MKS Robin nano v1.2 Emulated DOGM FSMC"

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V2
opt_disable TFT_320x240
opt_enable TOUCH_SCREEN
opt_enable SPI_GRAPHICAL_TFT
exec_test $1 $2 "MKS Robin v2 nano Emulated DOGM SPI"

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO
opt_disable TFT_320x240
opt_disable TOUCH_SCREEN
opt_enable TFT_LVGL_UI_FSMC
exec_test $1 $2 "MKS Robin nano v1.2 LVGL FSMC"

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V2
opt_disable TFT_320x240
opt_disable TOUCH_SCREEN
opt_enable TFT_LVGL_UI_SPI
exec_test $1 $2 "MKS Robin v2 nano LVGL SPI"

use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V2
opt_disable TFT_320x240
opt_enable TOUCH_SCREEN
opt_enable TFT_480x320_SPI
exec_test $1 $2 "MKS Robin v2 nano New Color UI 480x320 SPI"

# cleanup
restore_configs
