#!/usr/bin/env bash
#
# Build tests for MKS Robin Pro
#

# exit on first failure
set -e

use_example_configs Mks/Robin_Pro
opt_enable EMERGENCY_PARSER
opt_set SDCARD_CONNECTION LCD
opt_set X_DRIVER_TYPE TMC2209
opt_set Y_DRIVER_TYPE TMC2130
opt_set TEMP_SENSOR_BED 1
opt_disable THERMAL_PROTECTION_HOTENDS
exec_test $1 $2 "MKS Robin Pro, TMC Drivers, no thermal protection"

# cleanup
restore_configs
