#!/usr/bin/env bash
#
# Build tests for mks_monster8_usb_flash_drive_msc_CAN (STM32F407VE)
#

# exit on first failure
set -e

#
# MKS Monster8 V1 with CAN bus
#
restore_configs
opt_set MOTHERBOARD BOARD_MKS_MONSTER8_V1 SERIAL_PORT -1
opt_enable CAN_HOST CAN_TOOLHEAD
exec_test $1 $2 "MKS Monster8 V1 with CAN bus" "$3"

# cleanup
restore_configs
