#!/usr/bin/env bash
#
# Build tests for MKS Robin
# (STM32F1 genericSTM32F103ZE)
#

# exit on first failure
set -e

use_example_configs Mks/Robin
exec_test $1 $2 "MKS Robin config (FSMC Color UI)" "$3"

# cleanup
restore_configs
