#!/usr/bin/env bash
#
# Build tests for MKS Robin (HAL/STM32)
#

# exit on first failure
set -e

use_example_configs Mks/Robin
exec_test $1 $2 "MKS Robin base configuration"

# cleanup
restore_configs
