#!/usr/bin/env bash
#
# Build tests for MKS Robin
# (STM32F1 genericSTM32F103ZE)
#

# exit on first failure
set -e

use_example_configs Mks/Robin
opt_disable TFT_320x240
opt_enable FSMC_GRAPHICAL_TFT
exec_test $1 $2 "MKS Robin base configuration"

# cleanup
restore_configs
