#!/usr/bin/env bash
#
# Build tests for NUCLEO_F767ZI
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_NUCLEO_F767ZI SERIAL_PORT -1 X_DRIVER_TYPE TMC2209 Y_DRIVER_TYPE TMC2208
opt_enable BLTOUCH Z_SAFE_HOMING REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER SPEAKER SOFTWARE_DRIVER_ENABLE
exec_test $1 $2 "Mixed timer usage" "$3"

# clean up
restore_configs
