#!/usr/bin/env bash
#
# Build tests for Opulo LumenPnP REV3
#

# exit on first failure
set -e

use_example_configs Opulo/Lumen_REV3
exec_test $1 $2 "Opulo LumenPnP REV3 Pick and Place" "$3"

# cleanup
restore_configs
