#!/usr/bin/env bash
#
# Build tests for PANDA_PI_V29
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_PANDA_PI_V29 SERIAL_PORT -1 \
        Z_CLEARANCE_DEPLOY_PROBE 0 Z_CLEARANCE_BETWEEN_PROBES 1 Z_CLEARANCE_MULTI_PROBE 1
opt_enable BD_SENSOR AUTO_BED_LEVELING_BILINEAR Z_SAFE_HOMING BABYSTEPPING
exec_test $1 $2 "Panda Pi V29 | BD Sensor | ABL-B" "$3"

# clean up
restore_configs
