#!/usr/bin/env bash
#
# Build tests for AVR ATmega 1284p
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_SANGUINOLOLU_12
opt_set LCD_LANGUAGE de
opt_enable MINIPANEL USE_CONTROLLER_FAN CONTROLLER_FAN_EDITABLE
opt_set CONTROLLER_FAN_PIN 27
exec_test $1 $2 "Default Configuration | MINIPANAL | CONTROLLER_FAN" "$3"


# clean up
restore_configs
