#!/usr/bin/env bash
#
# Build tests for STM32F401RC_creality
#

# exit on first failure
set -e

use_example_configs "Creality/Ender-3 V2/CrealityV422/MarlinUI"
opt_enable AUTO_BED_LEVELING_BILINEAR Z_SAFE_HOMING
opt_set MOTHERBOARD BOARD_CREALITY_V24S1_301F4
opt_add SDCARD_EEPROM_EMULATION
exec_test $1 $2 "Ender-3 v2 with MarlinUI" "$3"

# clean up
restore_configs
