#!/usr/bin/env bash
#
# Build tests for STM32F103RE BigTreeTech (SKR E3 DIP v1.0)
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_E3_DIP \
        SERIAL_PORT 1 SERIAL_PORT_2 -1 \
        X_DRIVER_TYPE TMC2209 Y_DRIVER_TYPE TMC2130
exec_test $1 $2 "BTT SKR E3 DIP 1.0 | Mixed TMC Drivers" "$3"

# clean up
restore_configs
