#!/usr/bin/env bash
#
# Build tests for STM32F103RC_btt (BigTreeTech SKR Mini E3)
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_0 SERIAL_PORT 1 SERIAL_PORT_2 -1 \
        X_DRIVER_TYPE TMC2209 Y_DRIVER_TYPE TMC2209 Z_DRIVER_TYPE TMC2209 E0_DRIVER_TYPE TMC2209
opt_enable CR10_STOCKDISPLAY PINS_DEBUGGING Z_IDLE_HEIGHT ADAPTIVE_STEP_SMOOTHING
exec_test $1 $2 "BigTreeTech SKR Mini E3 1.0 - TMC2209 HW Serial" "$3"

# clean up
restore_configs
