#!/usr/bin/env bash
#
# Build tests for STM32F103VET6 (using maple STM32F1 framework)
#

# exit on first failure
set -e

use_example_configs Alfawise/U20
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "maple CLASSIC_UI U20 config" "$3"

use_example_configs Alfawise/U20
opt_enable BAUD_RATE_GCODE TFT_COLOR_UI
opt_disable TFT_CLASSIC_UI CUSTOM_STATUS_SCREEN_IMAGE
exec_test $1 $2 "maple COLOR_UI U20 config" "$3"

use_example_configs Alfawise/U20-bltouch
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "maple BLTouch U20 config"

# cleanup
restore_configs
