#!/usr/bin/env bash
#
# Build tests for STM32F103RC_fysetc_maple
#

# exit on first failure
set -e

#
# Build with the default configurations
#
use_example_configs "Creality/Ender-3/FYSETC Cheetah 1.2/base"
exec_test $1 $2 "Maple build of Cheetah 1.2 Configuration" "$3"

# clean up
restore_configs
