#!/usr/bin/env bash
#
# Build tests for STM32F103VET6 (using maple STM32F1 framework)
#

# exit on first failure
set -e

use_example_configs Alfawise/U20
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "Maple - Alfawise U20 - CLASSIC_UI" "$3"

use_example_configs Alfawise/U20
opt_enable BAUD_RATE_GCODE TFT_COLOR_UI
opt_disable TFT_CLASSIC_UI CUSTOM_STATUS_SCREEN_IMAGE
exec_test $1 $2 "Maple - Alfawise U20 - COLOR_UI" "$3"

use_example_configs Alfawise/U20-bltouch
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "Maple - Alfawise U20 - BLTouch"

# cleanup
restore_configs
