#!/usr/bin/env bash
#
# Build tests for STM32F103VET6
#

# exit on first failure
set -e

use_example_configs Alfawise/U20
opt_enable BAUD_RATE_GCODE
exec_test $1 $2 "Full-featured U20 config" "$3"

# cleanup
restore_configs
