#!/usr/bin/env bash
#
# Build tests for STM32F103RC MEEB_3DP (ccrobot-online.com)
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_CCROBOT_MEEB_3DP
opt_set SERIAL_PORT 1
opt_set SERIAL_PORT_2 -1
opt_set X_DRIVER_TYPE TMC2208
opt_set Y_DRIVER_TYPE TMC2208
opt_set Z_DRIVER_TYPE TMC2208
opt_set E0_DRIVER_TYPE TMC2208
exec_test $1 $2 "MEEB_3DP - Basic Config with TMC2208 SW Serial"

# clean up
restore_configs
