#!/usr/bin/env bash
#
# Build tests for STM32F103RET6_creality
#

# exit on first failure
set -e

#
# Build with configs included in the PR
#
use_example_configs "Creality/Ender-3 V2"
exec_test $1 $2 "Ender 3 v2"

restore_configs
