/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
#pragma once

/**
 * This file was generated by tltgen on Thu Jul  5 15:46:43 2018.
 * tltgen was created by Pieter Agten (pieter.agten@gmail.com).
 */
//#include "output_table.h"

/**
 * Parameters:
 * A: -0.000480634
 * B: 0.00031362
 * C: -2.03978e-07
 */
constexpr temp_entry_t temptable_666[] PROGMEM = {
  { OV(  1), 794 },
  { OV( 18), 288 },
  { OV( 35), 234 },
  { OV( 52), 207 },
  { OV( 69), 189 },
  { OV( 86), 176 },
  { OV(103), 166 },
  { OV(120), 157 },
  { OV(137) ,150 },
  { OV(154), 144 },
  { OV(172), 138 },
  { OV(189), 134 },
  { OV(206), 129 },
  { OV(223), 125 },
  { OV(240), 121 },
  { OV(257), 118 },
  { OV(274), 115 },
  { OV(291), 112 },
  { OV(308), 109 },
  { OV(325), 106 },
  { OV(342), 103 },
  { OV(359), 101 },
  { OV(376),  99 },
  { OV(393),  96 },
  { OV(410),  94 },
  { OV(427),  92 },
  { OV(444),  90 },
  { OV(461),  88 },
  { OV(478),  86 },
  { OV(495),  84 },
  { OV(512),  82 },
  { OV(530),  80 },
  { OV(547),  78 },
  { OV(564),  76 },
  { OV(581),  74 },
  { OV(598),  72 },
  { OV(615),  70 },
  { OV(632),  68 },
  { OV(649),  67 },
  { OV(666),  65 },
  { OV(683),  63 },
  { OV(700),  61 },
  { OV(717),  59 },
  { OV(734),  57 },
  { OV(751),  55 },
  { OV(768),  53 },
  { OV(785),  51 },
  { OV(802),  49 },
  { OV(819),  47 },
  { OV(836),  44 },
  { OV(853),  42 },
  { OV(871),  39 },
  { OV(888),  37 },
  { OV(905),  34 },
  { OV(922),  30 },
  { OV(939),  27 },
  { OV(956),  23 },
  { OV(973),  18 },
  { OV(990),  11 },
  { OV(1007),  2 },
  { OV(1023),-25 }
};
