/**
 * Instance header for ADC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_ADC_INSTANCE_
#define _SAM3U4E_ADC_INSTANCE_

#define REG_ADC_CR                 (*(__O uint32_t*)0x400AC000U)
#define REG_ADC_MR                 (*(__IO uint32_t*)0x400AC004U)
#define REG_ADC_CHER               (*(__O uint32_t*)0x400AC010U)
#define REG_ADC_CHDR               (*(__O uint32_t*)0x400AC014U)
#define REG_ADC_CHSR               (*(__I uint32_t*)0x400AC018U)
#define REG_ADC_SR                 (*(__I uint32_t*)0x400AC01CU)
#define REG_ADC_LCDR               (*(__I uint32_t*)0x400AC020U)
#define REG_ADC_IER                (*(__O uint32_t*)0x400AC024U)
#define REG_ADC_IDR                (*(__O uint32_t*)0x400AC028U)
#define REG_ADC_IMR                (*(__I uint32_t*)0x400AC02CU)
#define REG_ADC_CDR                (*(__I uint32_t(*)[8])0x400AC030U)
#define REG_ADC_RPR                (*(__IO uint32_t*)0x400AC100U)
#define REG_ADC_RCR                (*(__IO uint32_t*)0x400AC104U)
#define REG_ADC_RNPR               (*(__IO uint32_t*)0x400AC110U)
#define REG_ADC_RNCR               (*(__IO uint32_t*)0x400AC114U)
#define REG_ADC_PTCR               (*(__O uint32_t*)0x400AC120U)
#define REG_ADC_PTSR               (*(__I uint32_t*)0x400AC124U)

#endif /* _SAM3U4E_ADC_INSTANCE_ */
