/**
 * Instance header for ADC12B on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_ADC12B_INSTANCE_
#define _SAM3U4E_ADC12B_INSTANCE_

#define REG_ADC12B_CR              (*(__O uint32_t*)0x400A8000U)
#define REG_ADC12B_MR              (*(__IO uint32_t*)0x400A8004U)
#define REG_ADC12B_CHER            (*(__O uint32_t*)0x400A8010U)
#define REG_ADC12B_CHDR            (*(__O uint32_t*)0x400A8014U)
#define REG_ADC12B_CHSR            (*(__I uint32_t*)0x400A8018U)
#define REG_ADC12B_SR              (*(__I uint32_t*)0x400A801CU)
#define REG_ADC12B_LCDR            (*(__I uint32_t*)0x400A8020U)
#define REG_ADC12B_IER             (*(__O uint32_t*)0x400A8024U)
#define REG_ADC12B_IDR             (*(__O uint32_t*)0x400A8028U)
#define REG_ADC12B_IMR             (*(__I uint32_t*)0x400A802CU)
#define REG_ADC12B_CDR             (*(__I uint32_t(*)[8])0x400A8030U)
#define REG_ADC12B_ACR             (*(__IO uint32_t*)0x400A8064U)
#define REG_ADC12B_EMR             (*(__IO uint32_t*)0x400A8068U)
#define REG_ADC12B_RPR             (*(__IO uint32_t*)0x400A8100U)
#define REG_ADC12B_RCR             (*(__IO uint32_t*)0x400A8104U)
#define REG_ADC12B_RNPR            (*(__IO uint32_t*)0x400A8110U)
#define REG_ADC12B_RNCR            (*(__IO uint32_t*)0x400A8114U)
#define REG_ADC12B_PTCR            (*(__O uint32_t*)0x400A8120U)
#define REG_ADC12B_PTSR            (*(__I uint32_t*)0x400A8124U)

#endif /* _SAM3U4E_ADC12B_INSTANCE_ */
