/**
 * Instance header for EFC0 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_EFC0_INSTANCE_
#define _SAM3U4E_EFC0_INSTANCE_

#define REG_EFC0_FMR               (*(__IO uint32_t*)0x400E0800U)
#define REG_EFC0_FCR               (*(__O uint32_t*)0x400E0804U)
#define REG_EFC0_FSR               (*(__I uint32_t*)0x400E0808U)
#define REG_EFC0_FRR               (*(__I uint32_t*)0x400E080CU)

#endif /* _SAM3U4E_EFC0_INSTANCE_ */
