/**
 * Instance header for HSMCI on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_HSMCI_INSTANCE_
#define _SAM3U4E_HSMCI_INSTANCE_

#define REG_HSMCI_CR               (*(__O uint32_t*)0x40000000U)
#define REG_HSMCI_MR               (*(__IO uint32_t*)0x40000004U)
#define REG_HSMCI_DTOR             (*(__IO uint32_t*)0x40000008U)
#define REG_HSMCI_SDCR             (*(__IO uint32_t*)0x4000000CU)
#define REG_HSMCI_ARGR             (*(__IO uint32_t*)0x40000010U)
#define REG_HSMCI_CMDR             (*(__O uint32_t*)0x40000014U)
#define REG_HSMCI_BLKR             (*(__IO uint32_t*)0x40000018U)
#define REG_HSMCI_CSTOR            (*(__IO uint32_t*)0x4000001CU)
#define REG_HSMCI_RSPR             (*(__I uint32_t(*)[4])0x40000020U)
#define REG_HSMCI_RDR              (*(__I uint32_t*)0x40000030U)
#define REG_HSMCI_TDR              (*(__O uint32_t*)0x40000034U)
#define REG_HSMCI_SR               (*(__I uint32_t*)0x40000040U)
#define REG_HSMCI_IER              (*(__O uint32_t*)0x40000044U)
#define REG_HSMCI_IDR              (*(__O uint32_t*)0x40000048U)
#define REG_HSMCI_IMR              (*(__I uint32_t*)0x4000004CU)
#define REG_HSMCI_DMA              (*(__IO uint32_t*)0x40000050U)
#define REG_HSMCI_CFG              (*(__IO uint32_t*)0x40000054U)
#define REG_HSMCI_WPMR             (*(__IO uint32_t*)0x400000E4U)
#define REG_HSMCI_WPSR             (*(__I uint32_t*)0x400000E8U)
#define REG_HSMCI_FIFO             (*(__IO uint32_t(*)[256])0x40000200U)

#endif /* _SAM3U4E_HSMCI_INSTANCE_ */
