/**
 * Instance header for MATRIX on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_MATRIX_INSTANCE_
#define _SAM3U4E_MATRIX_INSTANCE_

#define REG_MATRIX_MCFG            (*(__IO uint32_t(*)[5])0x400E0200U)
#define REG_MATRIX_SCFG            (*(__IO uint32_t(*)[10])0x400E0240U)
#define REG_MATRIX_PRAS0           (*(__IO uint32_t*)0x400E0280U)
#define REG_MATRIX_PRAS1           (*(__IO uint32_t*)0x400E0288U)
#define REG_MATRIX_PRAS2           (*(__IO uint32_t*)0x400E0290U)
#define REG_MATRIX_PRAS3           (*(__IO uint32_t*)0x400E0298U)
#define REG_MATRIX_PRAS4           (*(__IO uint32_t*)0x400E02A0U)
#define REG_MATRIX_PRAS5           (*(__IO uint32_t*)0x400E02A8U)
#define REG_MATRIX_PRAS6           (*(__IO uint32_t*)0x400E02B0U)
#define REG_MATRIX_PRAS7           (*(__IO uint32_t*)0x400E02B8U)
#define REG_MATRIX_PRAS8           (*(__IO uint32_t*)0x400E02C0U)
#define REG_MATRIX_PRAS9           (*(__IO uint32_t*)0x400E02C8U)
#define REG_MATRIX_MRCR            (*(__IO uint32_t*)0x400E0300U)
#define REG_MATRIX_WPMR            (*(__IO uint32_t*)0x400E03E4U)
#define REG_MATRIX_WPSR            (*(__I uint32_t*)0x400E03E8U)

#endif /* _SAM3U4E_MATRIX_INSTANCE_ */
