/**
 * Instance header for PIOA on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_PIOA_INSTANCE_
#define _SAM3U4E_PIOA_INSTANCE_

#define REG_PIOA_PER               (*(__O uint32_t*)0x400E0C00U)
#define REG_PIOA_PDR               (*(__O uint32_t*)0x400E0C04U)
#define REG_PIOA_PSR               (*(__I uint32_t*)0x400E0C08U)
#define REG_PIOA_OER               (*(__O uint32_t*)0x400E0C10U)
#define REG_PIOA_ODR               (*(__O uint32_t*)0x400E0C14U)
#define REG_PIOA_OSR               (*(__I uint32_t*)0x400E0C18U)
#define REG_PIOA_IFER              (*(__O uint32_t*)0x400E0C20U)
#define REG_PIOA_IFDR              (*(__O uint32_t*)0x400E0C24U)
#define REG_PIOA_IFSR              (*(__I uint32_t*)0x400E0C28U)
#define REG_PIOA_SODR              (*(__O uint32_t*)0x400E0C30U)
#define REG_PIOA_CODR              (*(__O uint32_t*)0x400E0C34U)
#define REG_PIOA_ODSR              (*(__IO uint32_t*)0x400E0C38U)
#define REG_PIOA_PDSR              (*(__I uint32_t*)0x400E0C3CU)
#define REG_PIOA_IER               (*(__O uint32_t*)0x400E0C40U)
#define REG_PIOA_IDR               (*(__O uint32_t*)0x400E0C44U)
#define REG_PIOA_IMR               (*(__I uint32_t*)0x400E0C48U)
#define REG_PIOA_ISR               (*(__I uint32_t*)0x400E0C4CU)
#define REG_PIOA_MDER              (*(__O uint32_t*)0x400E0C50U)
#define REG_PIOA_MDDR              (*(__O uint32_t*)0x400E0C54U)
#define REG_PIOA_MDSR              (*(__I uint32_t*)0x400E0C58U)
#define REG_PIOA_PUDR              (*(__O uint32_t*)0x400E0C60U)
#define REG_PIOA_PUER              (*(__O uint32_t*)0x400E0C64U)
#define REG_PIOA_PUSR              (*(__I uint32_t*)0x400E0C68U)
#define REG_PIOA_ABSR              (*(__IO uint32_t*)0x400E0C70U)
#define REG_PIOA_SCIFSR            (*(__O uint32_t*)0x400E0C80U)
#define REG_PIOA_DIFSR             (*(__O uint32_t*)0x400E0C84U)
#define REG_PIOA_IFDGSR            (*(__I uint32_t*)0x400E0C88U)
#define REG_PIOA_SCDR              (*(__IO uint32_t*)0x400E0C8CU)
#define REG_PIOA_OWER              (*(__O uint32_t*)0x400E0CA0U)
#define REG_PIOA_OWDR              (*(__O uint32_t*)0x400E0CA4U)
#define REG_PIOA_OWSR              (*(__I uint32_t*)0x400E0CA8U)
#define REG_PIOA_AIMER             (*(__O uint32_t*)0x400E0CB0U)
#define REG_PIOA_AIMDR             (*(__O uint32_t*)0x400E0CB4U)
#define REG_PIOA_AIMMR             (*(__I uint32_t*)0x400E0CB8U)
#define REG_PIOA_ESR               (*(__O uint32_t*)0x400E0CC0U)
#define REG_PIOA_LSR               (*(__O uint32_t*)0x400E0CC4U)
#define REG_PIOA_ELSR              (*(__I uint32_t*)0x400E0CC8U)
#define REG_PIOA_FELLSR            (*(__O uint32_t*)0x400E0CD0U)
#define REG_PIOA_REHLSR            (*(__O uint32_t*)0x400E0CD4U)
#define REG_PIOA_FRLHSR            (*(__I uint32_t*)0x400E0CD8U)
#define REG_PIOA_LOCKSR            (*(__I uint32_t*)0x400E0CE0U)
#define REG_PIOA_WPMR              (*(__IO uint32_t*)0x400E0CE4U)
#define REG_PIOA_WPSR              (*(__I uint32_t*)0x400E0CE8U)

#endif /* _SAM3U4E_PIOA_INSTANCE_ */
