/**
 * Instance header for PIOB on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_PIOB_INSTANCE_
#define _SAM3U4E_PIOB_INSTANCE_

#define REG_PIOB_PER               (*(__O uint32_t*)0x400E0E00U)
#define REG_PIOB_PDR               (*(__O uint32_t*)0x400E0E04U)
#define REG_PIOB_PSR               (*(__I uint32_t*)0x400E0E08U)
#define REG_PIOB_OER               (*(__O uint32_t*)0x400E0E10U)
#define REG_PIOB_ODR               (*(__O uint32_t*)0x400E0E14U)
#define REG_PIOB_OSR               (*(__I uint32_t*)0x400E0E18U)
#define REG_PIOB_IFER              (*(__O uint32_t*)0x400E0E20U)
#define REG_PIOB_IFDR              (*(__O uint32_t*)0x400E0E24U)
#define REG_PIOB_IFSR              (*(__I uint32_t*)0x400E0E28U)
#define REG_PIOB_SODR              (*(__O uint32_t*)0x400E0E30U)
#define REG_PIOB_CODR              (*(__O uint32_t*)0x400E0E34U)
#define REG_PIOB_ODSR              (*(__IO uint32_t*)0x400E0E38U)
#define REG_PIOB_PDSR              (*(__I uint32_t*)0x400E0E3CU)
#define REG_PIOB_IER               (*(__O uint32_t*)0x400E0E40U)
#define REG_PIOB_IDR               (*(__O uint32_t*)0x400E0E44U)
#define REG_PIOB_IMR               (*(__I uint32_t*)0x400E0E48U)
#define REG_PIOB_ISR               (*(__I uint32_t*)0x400E0E4CU)
#define REG_PIOB_MDER              (*(__O uint32_t*)0x400E0E50U)
#define REG_PIOB_MDDR              (*(__O uint32_t*)0x400E0E54U)
#define REG_PIOB_MDSR              (*(__I uint32_t*)0x400E0E58U)
#define REG_PIOB_PUDR              (*(__O uint32_t*)0x400E0E60U)
#define REG_PIOB_PUER              (*(__O uint32_t*)0x400E0E64U)
#define REG_PIOB_PUSR              (*(__I uint32_t*)0x400E0E68U)
#define REG_PIOB_ABSR              (*(__IO uint32_t*)0x400E0E70U)
#define REG_PIOB_SCIFSR            (*(__O uint32_t*)0x400E0E80U)
#define REG_PIOB_DIFSR             (*(__O uint32_t*)0x400E0E84U)
#define REG_PIOB_IFDGSR            (*(__I uint32_t*)0x400E0E88U)
#define REG_PIOB_SCDR              (*(__IO uint32_t*)0x400E0E8CU)
#define REG_PIOB_OWER              (*(__O uint32_t*)0x400E0EA0U)
#define REG_PIOB_OWDR              (*(__O uint32_t*)0x400E0EA4U)
#define REG_PIOB_OWSR              (*(__I uint32_t*)0x400E0EA8U)
#define REG_PIOB_AIMER             (*(__O uint32_t*)0x400E0EB0U)
#define REG_PIOB_AIMDR             (*(__O uint32_t*)0x400E0EB4U)
#define REG_PIOB_AIMMR             (*(__I uint32_t*)0x400E0EB8U)
#define REG_PIOB_ESR               (*(__O uint32_t*)0x400E0EC0U)
#define REG_PIOB_LSR               (*(__O uint32_t*)0x400E0EC4U)
#define REG_PIOB_ELSR              (*(__I uint32_t*)0x400E0EC8U)
#define REG_PIOB_FELLSR            (*(__O uint32_t*)0x400E0ED0U)
#define REG_PIOB_REHLSR            (*(__O uint32_t*)0x400E0ED4U)
#define REG_PIOB_FRLHSR            (*(__I uint32_t*)0x400E0ED8U)
#define REG_PIOB_LOCKSR            (*(__I uint32_t*)0x400E0EE0U)
#define REG_PIOB_WPMR              (*(__IO uint32_t*)0x400E0EE4U)
#define REG_PIOB_WPSR              (*(__I uint32_t*)0x400E0EE8U)

#endif /* _SAM3U4E_PIOB_INSTANCE_ */
