/**
 * Instance header for PIOC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_PIOC_INSTANCE_
#define _SAM3U4E_PIOC_INSTANCE_

#define REG_PIOC_PER               (*(__O uint32_t*)0x400E1000U)
#define REG_PIOC_PDR               (*(__O uint32_t*)0x400E1004U)
#define REG_PIOC_PSR               (*(__I uint32_t*)0x400E1008U)
#define REG_PIOC_OER               (*(__O uint32_t*)0x400E1010U)
#define REG_PIOC_ODR               (*(__O uint32_t*)0x400E1014U)
#define REG_PIOC_OSR               (*(__I uint32_t*)0x400E1018U)
#define REG_PIOC_IFER              (*(__O uint32_t*)0x400E1020U)
#define REG_PIOC_IFDR              (*(__O uint32_t*)0x400E1024U)
#define REG_PIOC_IFSR              (*(__I uint32_t*)0x400E1028U)
#define REG_PIOC_SODR              (*(__O uint32_t*)0x400E1030U)
#define REG_PIOC_CODR              (*(__O uint32_t*)0x400E1034U)
#define REG_PIOC_ODSR              (*(__IO uint32_t*)0x400E1038U)
#define REG_PIOC_PDSR              (*(__I uint32_t*)0x400E103CU)
#define REG_PIOC_IER               (*(__O uint32_t*)0x400E1040U)
#define REG_PIOC_IDR               (*(__O uint32_t*)0x400E1044U)
#define REG_PIOC_IMR               (*(__I uint32_t*)0x400E1048U)
#define REG_PIOC_ISR               (*(__I uint32_t*)0x400E104CU)
#define REG_PIOC_MDER              (*(__O uint32_t*)0x400E1050U)
#define REG_PIOC_MDDR              (*(__O uint32_t*)0x400E1054U)
#define REG_PIOC_MDSR              (*(__I uint32_t*)0x400E1058U)
#define REG_PIOC_PUDR              (*(__O uint32_t*)0x400E1060U)
#define REG_PIOC_PUER              (*(__O uint32_t*)0x400E1064U)
#define REG_PIOC_PUSR              (*(__I uint32_t*)0x400E1068U)
#define REG_PIOC_ABSR              (*(__IO uint32_t*)0x400E1070U)
#define REG_PIOC_SCIFSR            (*(__O uint32_t*)0x400E1080U)
#define REG_PIOC_DIFSR             (*(__O uint32_t*)0x400E1084U)
#define REG_PIOC_IFDGSR            (*(__I uint32_t*)0x400E1088U)
#define REG_PIOC_SCDR              (*(__IO uint32_t*)0x400E108CU)
#define REG_PIOC_OWER              (*(__O uint32_t*)0x400E10A0U)
#define REG_PIOC_OWDR              (*(__O uint32_t*)0x400E10A4U)
#define REG_PIOC_OWSR              (*(__I uint32_t*)0x400E10A8U)
#define REG_PIOC_AIMER             (*(__O uint32_t*)0x400E10B0U)
#define REG_PIOC_AIMDR             (*(__O uint32_t*)0x400E10B4U)
#define REG_PIOC_AIMMR             (*(__I uint32_t*)0x400E10B8U)
#define REG_PIOC_ESR               (*(__O uint32_t*)0x400E10C0U)
#define REG_PIOC_LSR               (*(__O uint32_t*)0x400E10C4U)
#define REG_PIOC_ELSR              (*(__I uint32_t*)0x400E10C8U)
#define REG_PIOC_FELLSR            (*(__O uint32_t*)0x400E10D0U)
#define REG_PIOC_REHLSR            (*(__O uint32_t*)0x400E10D4U)
#define REG_PIOC_FRLHSR            (*(__I uint32_t*)0x400E10D8U)
#define REG_PIOC_LOCKSR            (*(__I uint32_t*)0x400E10E0U)
#define REG_PIOC_WPMR              (*(__IO uint32_t*)0x400E10E4U)
#define REG_PIOC_WPSR              (*(__I uint32_t*)0x400E10E8U)

#endif /* _SAM3U4E_PIOC_INSTANCE_ */
