/**
 * Instance header for PMC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_PMC_INSTANCE_
#define _SAM3U4E_PMC_INSTANCE_

#define REG_PMC_SCER               (*(__O uint32_t*)0x400E0400U)
#define REG_PMC_SCDR               (*(__O uint32_t*)0x400E0404U)
#define REG_PMC_SCSR               (*(__I uint32_t*)0x400E0408U)
#define REG_PMC_PCER0              (*(__O uint32_t*)0x400E0410U)
#define REG_PMC_PCDR0              (*(__O uint32_t*)0x400E0414U)
#define REG_PMC_PCSR0              (*(__I uint32_t*)0x400E0418U)
#define REG_PMC_UCKR               (*(__IO uint32_t*)0x400E041CU)
#define REG_PMC_MOR                (*(__IO uint32_t*)0x400E0420U)
#define REG_PMC_MCFR               (*(__I uint32_t*)0x400E0424U)
#define REG_PMC_PLLAR              (*(__IO uint32_t*)0x400E0428U)
#define REG_PMC_MCKR               (*(__IO uint32_t*)0x400E0430U)
#define REG_PMC_PCK                (*(__IO uint32_t(*)[3])0x400E0440U)
#define REG_PMC_IER                (*(__O uint32_t*)0x400E0460U)
#define REG_PMC_IDR                (*(__O uint32_t*)0x400E0464U)
#define REG_PMC_SR                 (*(__I uint32_t*)0x400E0468U)
#define REG_PMC_IMR                (*(__I uint32_t*)0x400E046CU)
#define REG_PMC_FSMR               (*(__IO uint32_t*)0x400E0470U)
#define REG_PMC_FSPR               (*(__IO uint32_t*)0x400E0474U)
#define REG_PMC_FOCR               (*(__O uint32_t*)0x400E0478U)
#define REG_PMC_WPMR               (*(__IO uint32_t*)0x400E04E4U)
#define REG_PMC_WPSR               (*(__I uint32_t*)0x400E04E8U)

#endif /* _SAM3U4E_PMC_INSTANCE_ */
