/**
 * Instance header for PWM on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_PWM_INSTANCE_
#define _SAM3U4E_PWM_INSTANCE_

#define REG_PWM_CMR                (*(__IO uint32_t*)0x4008C000U)
#define REG_PWM_CDTY               (*(__IO uint32_t*)0x4008C004U)
#define REG_PWM_CDTYUPD            (*(__O uint32_t*)0x4008C008U)
#define REG_PWM_CPRD               (*(__IO uint32_t*)0x4008C00CU)
#define REG_PWM_CPRDUPD            (*(__O uint32_t*)0x4008C010U)
#define REG_PWM_CCNT               (*(__I uint32_t*)0x4008C014U)
#define REG_PWM_DT                 (*(__IO uint32_t*)0x4008C018U)
#define REG_PWM_DTUPD              (*(__O uint32_t*)0x4008C01CU)
#define REG_PWM_CMPV               (*(__IO uint32_t*)0x4008C000U)
#define REG_PWM_CMPVUPD            (*(__O uint32_t*)0x4008C004U)
#define REG_PWM_CMPM               (*(__IO uint32_t*)0x4008C008U)
#define REG_PWM_CMPMUPD            (*(__O uint32_t*)0x4008C00CU)
#define REG_PWM_CLK                (*(__IO uint32_t*)0x4008C000U)
#define REG_PWM_ENA                (*(__O uint32_t*)0x4008C004U)
#define REG_PWM_DIS                (*(__O uint32_t*)0x4008C008U)
#define REG_PWM_SR                 (*(__I uint32_t*)0x4008C00CU)
#define REG_PWM_IER1               (*(__O uint32_t*)0x4008C010U)
#define REG_PWM_IDR1               (*(__O uint32_t*)0x4008C014U)
#define REG_PWM_IMR1               (*(__I uint32_t*)0x4008C018U)
#define REG_PWM_ISR1               (*(__I uint32_t*)0x4008C01CU)
#define REG_PWM_SCM                (*(__IO uint32_t*)0x4008C020U)
#define REG_PWM_SCUC               (*(__IO uint32_t*)0x4008C028U)
#define REG_PWM_SCUP               (*(__IO uint32_t*)0x4008C02CU)
#define REG_PWM_SCUPUPD            (*(__O uint32_t*)0x4008C030U)
#define REG_PWM_IER2               (*(__O uint32_t*)0x4008C034U)
#define REG_PWM_IDR2               (*(__O uint32_t*)0x4008C038U)
#define REG_PWM_IMR2               (*(__I uint32_t*)0x4008C03CU)
#define REG_PWM_ISR2               (*(__I uint32_t*)0x4008C040U)
#define REG_PWM_OOV                (*(__IO uint32_t*)0x4008C044U)
#define REG_PWM_OS                 (*(__IO uint32_t*)0x4008C048U)
#define REG_PWM_OSS                (*(__O uint32_t*)0x4008C04CU)
#define REG_PWM_OSC                (*(__O uint32_t*)0x4008C050U)
#define REG_PWM_OSSUPD             (*(__O uint32_t*)0x4008C054U)
#define REG_PWM_OSCUPD             (*(__O uint32_t*)0x4008C058U)
#define REG_PWM_FMR                (*(__IO uint32_t*)0x4008C05CU)
#define REG_PWM_FSR                (*(__I uint32_t*)0x4008C060U)
#define REG_PWM_FCR                (*(__O uint32_t*)0x4008C064U)
#define REG_PWM_FPV                (*(__IO uint32_t*)0x4008C068U)
#define REG_PWM_FPE                (*(__IO uint32_t*)0x4008C06CU)
#define REG_PWM_ELMR               (*(__IO uint32_t(*)[2])0x4008C07CU)
#define REG_PWM_SMMR               (*(__IO uint32_t*)0x4008C0B0U)
#define REG_PWM_WPCR               (*(__O uint32_t*)0x4008C0E4U)
#define REG_PWM_WPSR               (*(__I uint32_t*)0x4008C0E8U)
#define REG_PWM_TPR                (*(__IO uint32_t*)0x4008C108U)
#define REG_PWM_TCR                (*(__IO uint32_t*)0x4008C10CU)
#define REG_PWM_TNPR               (*(__IO uint32_t*)0x4008C118U)
#define REG_PWM_TNCR               (*(__IO uint32_t*)0x4008C11CU)
#define REG_PWM_PTCR               (*(__O uint32_t*)0x4008C120U)
#define REG_PWM_PTSR               (*(__I uint32_t*)0x4008C124U)

#endif /* _SAM3U4E_PWM_INSTANCE_ */
