/**
 * Instance header for RTC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_RTC_INSTANCE_
#define _SAM3U4E_RTC_INSTANCE_

#define REG_RTC_CR                 (*(__IO uint32_t*)0x400E1260U)
#define REG_RTC_MR                 (*(__IO uint32_t*)0x400E1264U)
#define REG_RTC_TIMR               (*(__IO uint32_t*)0x400E1268U)
#define REG_RTC_CALR               (*(__IO uint32_t*)0x400E126CU)
#define REG_RTC_TIMALR             (*(__IO uint32_t*)0x400E1270U)
#define REG_RTC_CALALR             (*(__IO uint32_t*)0x400E1274U)
#define REG_RTC_SR                 (*(__I uint32_t*)0x400E1278U)
#define REG_RTC_SCCR               (*(__O uint32_t*)0x400E127CU)
#define REG_RTC_IER                (*(__O uint32_t*)0x400E1280U)
#define REG_RTC_IDR                (*(__O uint32_t*)0x400E1284U)
#define REG_RTC_IMR                (*(__I uint32_t*)0x400E1288U)
#define REG_RTC_VER                (*(__I uint32_t*)0x400E128CU)
#define REG_RTC_WPMR               (*(__IO uint32_t*)0x400E1344U)

#endif /* _SAM3U4E_RTC_INSTANCE_ */
