/**
 * Instance header for SMC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_SMC_INSTANCE_
#define _SAM3U4E_SMC_INSTANCE_

#define REG_SMC_SETUP              (*(__IO uint32_t*)0x400E0000U)
#define REG_SMC_PULSE              (*(__IO uint32_t*)0x400E0004U)
#define REG_SMC_CYCLE              (*(__IO uint32_t*)0x400E0008U)
#define REG_SMC_TIMINGS            (*(__IO uint32_t*)0x400E000CU)
#define REG_SMC_MODE               (*(__IO uint32_t*)0x400E0010U)
#define REG_SMC_CFG                (*(__IO uint32_t*)0x400E0000U)
#define REG_SMC_CTRL               (*(__O uint32_t*)0x400E0004U)
#define REG_SMC_SR                 (*(__I uint32_t*)0x400E0008U)
#define REG_SMC_IER                (*(__O uint32_t*)0x400E000CU)
#define REG_SMC_IDR                (*(__O uint32_t*)0x400E0010U)
#define REG_SMC_IMR                (*(__I uint32_t*)0x400E0014U)
#define REG_SMC_ADDR               (*(__IO uint32_t*)0x400E0018U)
#define REG_SMC_BANK               (*(__IO uint32_t*)0x400E001CU)
#define REG_SMC_ECC_CTRL           (*(__O uint32_t*)0x400E0020U)
#define REG_SMC_ECC_MD             (*(__IO uint32_t*)0x400E0024U)
#define REG_SMC_ECC_SR1            (*(__I uint32_t*)0x400E0028U)
#define REG_SMC_ECC_PR0            (*(__I uint32_t*)0x400E002CU)
#define REG_SMC_ECC_PR1            (*(__I uint32_t*)0x400E0030U)
#define REG_SMC_ECC_SR2            (*(__I uint32_t*)0x400E0034U)
#define REG_SMC_ECC_PR2            (*(__I uint32_t*)0x400E0038U)
#define REG_SMC_ECC_PR3            (*(__I uint32_t*)0x400E003CU)
#define REG_SMC_ECC_PR4            (*(__I uint32_t*)0x400E0040U)
#define REG_SMC_ECC_PR5            (*(__I uint32_t*)0x400E0044U)
#define REG_SMC_ECC_PR6            (*(__I uint32_t*)0x400E0048U)
#define REG_SMC_ECC_PR7            (*(__I uint32_t*)0x400E004CU)
#define REG_SMC_ECC_PR8            (*(__I uint32_t*)0x400E0050U)
#define REG_SMC_ECC_PR9            (*(__I uint32_t*)0x400E0054U)
#define REG_SMC_ECC_PR10           (*(__I uint32_t*)0x400E0058U)
#define REG_SMC_ECC_PR11           (*(__I uint32_t*)0x400E005CU)
#define REG_SMC_ECC_PR12           (*(__I uint32_t*)0x400E0060U)
#define REG_SMC_ECC_PR13           (*(__I uint32_t*)0x400E0064U)
#define REG_SMC_ECC_PR14           (*(__I uint32_t*)0x400E0068U)
#define REG_SMC_ECC_PR15           (*(__I uint32_t*)0x400E006CU)
#define REG_SMC_OCMS               (*(__IO uint32_t*)0x400E0110U)
#define REG_SMC_KEY1               (*(__O uint32_t*)0x400E0114U)
#define REG_SMC_KEY2               (*(__O uint32_t*)0x400E0118U)
#define REG_SMC_WPCR               (*(__O uint32_t*)0x400E01E4U)
#define REG_SMC_WPSR               (*(__I uint32_t*)0x400E01E8U)

#endif /* _SAM3U4E_SMC_INSTANCE_ */
