/**
 * Instance header for SPI on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_SPI_INSTANCE_
#define _SAM3U4E_SPI_INSTANCE_

#define REG_SPI_CR                 (*(__O uint32_t*)0x40008000U)
#define REG_SPI_MR                 (*(__IO uint32_t*)0x40008004U)
#define REG_SPI_RDR                (*(__I uint32_t*)0x40008008U)
#define REG_SPI_TDR                (*(__O uint32_t*)0x4000800CU)
#define REG_SPI_SR                 (*(__I uint32_t*)0x40008010U)
#define REG_SPI_IER                (*(__O uint32_t*)0x40008014U)
#define REG_SPI_IDR                (*(__O uint32_t*)0x40008018U)
#define REG_SPI_IMR                (*(__I uint32_t*)0x4000801CU)
#define REG_SPI_CSR                (*(__IO uint32_t(*)[4])0x40008030U)
#define REG_SPI_WPMR               (*(__IO uint32_t*)0x400080E4U)
#define REG_SPI_WPSR               (*(__I uint32_t*)0x400080E8U)

#endif /* _SAM3U4E_SPI_INSTANCE_ */
