/**
 * Instance header for SSC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_SSC_INSTANCE_
#define _SAM3U4E_SSC_INSTANCE_

#define REG_SSC_CR                 (*(__O uint32_t*)0x40004000U)
#define REG_SSC_CMR                (*(__IO uint32_t*)0x40004004U)
#define REG_SSC_RCMR               (*(__IO uint32_t*)0x40004010U)
#define REG_SSC_RFMR               (*(__IO uint32_t*)0x40004014U)
#define REG_SSC_TCMR               (*(__IO uint32_t*)0x40004018U)
#define REG_SSC_TFMR               (*(__IO uint32_t*)0x4000401CU)
#define REG_SSC_RHR                (*(__I uint32_t*)0x40004020U)
#define REG_SSC_THR                (*(__O uint32_t*)0x40004024U)
#define REG_SSC_RSHR               (*(__I uint32_t*)0x40004030U)
#define REG_SSC_TSHR               (*(__IO uint32_t*)0x40004034U)
#define REG_SSC_RC0R               (*(__IO uint32_t*)0x40004038U)
#define REG_SSC_RC1R               (*(__IO uint32_t*)0x4000403CU)
#define REG_SSC_SR                 (*(__I uint32_t*)0x40004040U)
#define REG_SSC_IER                (*(__O uint32_t*)0x40004044U)
#define REG_SSC_IDR                (*(__O uint32_t*)0x40004048U)
#define REG_SSC_IMR                (*(__I uint32_t*)0x4000404CU)
#define REG_SSC_WPMR               (*(__IO uint32_t*)0x400040E4U)
#define REG_SSC_WPSR               (*(__I uint32_t*)0x400040E8U)

#endif /* _SAM3U4E_SSC_INSTANCE_ */
