/**
 * Instance header for SUPC on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_SUPC_INSTANCE_
#define _SAM3U4E_SUPC_INSTANCE_

#define REG_SUPC_CR                (*(__O uint32_t*)0x400E1210U)
#define REG_SUPC_SMMR              (*(__IO uint32_t*)0x400E1214U)
#define REG_SUPC_MR                (*(__IO uint32_t*)0x400E1218U)
#define REG_SUPC_WUMR              (*(__IO uint32_t*)0x400E121CU)
#define REG_SUPC_WUIR              (*(__IO uint32_t*)0x400E1220U)
#define REG_SUPC_SR                (*(__I uint32_t*)0x400E1224U)

#endif /* _SAM3U4E_SUPC_INSTANCE_ */
