/**
 * Instance header for TC0 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_TC0_INSTANCE_
#define _SAM3U4E_TC0_INSTANCE_

#define REG_TC0_CCR                (*(__O uint32_t*)0x40080000U)
#define REG_TC0_CMR                (*(__IO uint32_t*)0x40080004U)
#define REG_TC0_CV                 (*(__I uint32_t*)0x40080010U)
#define REG_TC0_RA                 (*(__IO uint32_t*)0x40080014U)
#define REG_TC0_RB                 (*(__IO uint32_t*)0x40080018U)
#define REG_TC0_RC                 (*(__IO uint32_t*)0x4008001CU)
#define REG_TC0_SR                 (*(__I uint32_t*)0x40080020U)
#define REG_TC0_IER                (*(__O uint32_t*)0x40080024U)
#define REG_TC0_IDR                (*(__O uint32_t*)0x40080028U)
#define REG_TC0_IMR                (*(__I uint32_t*)0x4008002CU)
#define REG_TC0_BCR                (*(__O uint32_t*)0x400800C0U)
#define REG_TC0_BMR                (*(__IO uint32_t*)0x400800C4U)
#define REG_TC0_QIER               (*(__O uint32_t*)0x400800C8U)
#define REG_TC0_QIDR               (*(__O uint32_t*)0x400800CCU)
#define REG_TC0_QIMR               (*(__I uint32_t*)0x400800D0U)
#define REG_TC0_QISR               (*(__I uint32_t*)0x400800D4U)

#endif /* _SAM3U4E_TC0_INSTANCE_ */
