/**
 * Instance header for TWI0 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_TWI0_INSTANCE_
#define _SAM3U4E_TWI0_INSTANCE_

#define REG_TWI0_CR                (*(__O uint32_t*)0x40084000U)
#define REG_TWI0_MMR               (*(__IO uint32_t*)0x40084004U)
#define REG_TWI0_SMR               (*(__IO uint32_t*)0x40084008U)
#define REG_TWI0_IADR              (*(__IO uint32_t*)0x4008400CU)
#define REG_TWI0_CWGR              (*(__IO uint32_t*)0x40084010U)
#define REG_TWI0_SR                (*(__I uint32_t*)0x40084020U)
#define REG_TWI0_IER               (*(__O uint32_t*)0x40084024U)
#define REG_TWI0_IDR               (*(__O uint32_t*)0x40084028U)
#define REG_TWI0_IMR               (*(__I uint32_t*)0x4008402CU)
#define REG_TWI0_RHR               (*(__I uint32_t*)0x40084030U)
#define REG_TWI0_THR               (*(__O uint32_t*)0x40084034U)
#define REG_TWI0_RPR               (*(__IO uint32_t*)0x40084100U)
#define REG_TWI0_RCR               (*(__IO uint32_t*)0x40084104U)
#define REG_TWI0_TPR               (*(__IO uint32_t*)0x40084108U)
#define REG_TWI0_TCR               (*(__IO uint32_t*)0x4008410CU)
#define REG_TWI0_RNPR              (*(__IO uint32_t*)0x40084110U)
#define REG_TWI0_RNCR              (*(__IO uint32_t*)0x40084114U)
#define REG_TWI0_TNPR              (*(__IO uint32_t*)0x40084118U)
#define REG_TWI0_TNCR              (*(__IO uint32_t*)0x4008411CU)
#define REG_TWI0_PTCR              (*(__O uint32_t*)0x40084120U)
#define REG_TWI0_PTSR              (*(__I uint32_t*)0x40084124U)

#endif /* _SAM3U4E_TWI0_INSTANCE_ */
