/**
 * Instance header for TWI1 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_TWI1_INSTANCE_
#define _SAM3U4E_TWI1_INSTANCE_

#define REG_TWI1_CR                (*(__O uint32_t*)0x40088000U)
#define REG_TWI1_MMR               (*(__IO uint32_t*)0x40088004U)
#define REG_TWI1_SMR               (*(__IO uint32_t*)0x40088008U)
#define REG_TWI1_IADR              (*(__IO uint32_t*)0x4008800CU)
#define REG_TWI1_CWGR              (*(__IO uint32_t*)0x40088010U)
#define REG_TWI1_SR                (*(__I uint32_t*)0x40088020U)
#define REG_TWI1_IER               (*(__O uint32_t*)0x40088024U)
#define REG_TWI1_IDR               (*(__O uint32_t*)0x40088028U)
#define REG_TWI1_IMR               (*(__I uint32_t*)0x4008802CU)
#define REG_TWI1_RHR               (*(__I uint32_t*)0x40088030U)
#define REG_TWI1_THR               (*(__O uint32_t*)0x40088034U)
#define REG_TWI1_RPR               (*(__IO uint32_t*)0x40088100U)
#define REG_TWI1_RCR               (*(__IO uint32_t*)0x40088104U)
#define REG_TWI1_TPR               (*(__IO uint32_t*)0x40088108U)
#define REG_TWI1_TCR               (*(__IO uint32_t*)0x4008810CU)
#define REG_TWI1_RNPR              (*(__IO uint32_t*)0x40088110U)
#define REG_TWI1_RNCR              (*(__IO uint32_t*)0x40088114U)
#define REG_TWI1_TNPR              (*(__IO uint32_t*)0x40088118U)
#define REG_TWI1_TNCR              (*(__IO uint32_t*)0x4008811CU)
#define REG_TWI1_PTCR              (*(__O uint32_t*)0x40088120U)
#define REG_TWI1_PTSR              (*(__I uint32_t*)0x40088124U)

#endif /* _SAM3U4E_TWI1_INSTANCE_ */
