/**
 * Instance header for UART on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_UART_INSTANCE_
#define _SAM3U4E_UART_INSTANCE_

#define REG_UART_CR                (*(__O uint32_t*)0x400E0600U)
#define REG_UART_MR                (*(__IO uint32_t*)0x400E0604U)
#define REG_UART_IER               (*(__O uint32_t*)0x400E0608U)
#define REG_UART_IDR               (*(__O uint32_t*)0x400E060CU)
#define REG_UART_IMR               (*(__I uint32_t*)0x400E0610U)
#define REG_UART_SR                (*(__I uint32_t*)0x400E0614U)
#define REG_UART_RHR               (*(__I uint32_t*)0x400E0618U)
#define REG_UART_THR               (*(__O uint32_t*)0x400E061CU)
#define REG_UART_BRGR              (*(__IO uint32_t*)0x400E0620U)
#define REG_UART_RPR               (*(__IO uint32_t*)0x400E0700U)
#define REG_UART_RCR               (*(__IO uint32_t*)0x400E0704U)
#define REG_UART_TPR               (*(__IO uint32_t*)0x400E0708U)
#define REG_UART_TCR               (*(__IO uint32_t*)0x400E070CU)
#define REG_UART_RNPR              (*(__IO uint32_t*)0x400E0710U)
#define REG_UART_RNCR              (*(__IO uint32_t*)0x400E0714U)
#define REG_UART_TNPR              (*(__IO uint32_t*)0x400E0718U)
#define REG_UART_TNCR              (*(__IO uint32_t*)0x400E071CU)
#define REG_UART_PTCR              (*(__O uint32_t*)0x400E0720U)
#define REG_UART_PTSR              (*(__I uint32_t*)0x400E0724U)

#endif /* _SAM3U4E_UART_INSTANCE_ */
