/**
 * Instance header for UDPHS on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_UDPHS_INSTANCE_
#define _SAM3U4E_UDPHS_INSTANCE_

#define REG_UDPHS_DMANXTDSC        (*(__IO uint32_t*)0x400A4000U)
#define REG_UDPHS_DMAADDRESS       (*(__IO uint32_t*)0x400A4004U)
#define REG_UDPHS_DMACONTROL       (*(__IO uint32_t*)0x400A4008U)
#define REG_UDPHS_DMASTATUS        (*(__IO uint32_t*)0x400A400CU)
#define REG_UDPHS_EPTCFG           (*(__IO uint32_t*)0x400A4000U)
#define REG_UDPHS_EPTCTLENB        (*(__O uint32_t*)0x400A4004U)
#define REG_UDPHS_EPTCTLDIS        (*(__O uint32_t*)0x400A4008U)
#define REG_UDPHS_EPTCTL           (*(__I uint32_t*)0x400A400CU)
#define REG_UDPHS_EPTSETSTA        (*(__O uint32_t*)0x400A4014U)
#define REG_UDPHS_EPTCLRSTA        (*(__O uint32_t*)0x400A4018U)
#define REG_UDPHS_EPTSTA           (*(__I uint32_t*)0x400A401CU)
#define REG_UDPHS_CTRL             (*(__IO uint32_t*)0x400A4000U)
#define REG_UDPHS_FNUM             (*(__I uint32_t*)0x400A4004U)
#define REG_UDPHS_IEN              (*(__IO uint32_t*)0x400A4010U)
#define REG_UDPHS_INTSTA           (*(__I uint32_t*)0x400A4014U)
#define REG_UDPHS_CLRINT           (*(__O uint32_t*)0x400A4018U)
#define REG_UDPHS_EPTRST           (*(__O uint32_t*)0x400A401CU)
#define REG_UDPHS_TST              (*(__IO uint32_t*)0x400A40E0U)

#endif /* _SAM3U4E_UDPHS_INSTANCE_ */
