/**
 * Instance header for USART1 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_USART1_INSTANCE_
#define _SAM3U4E_USART1_INSTANCE_

#define REG_USART1_CR              (*(__O uint32_t*)0x40094000U)
#define REG_USART1_MR              (*(__IO uint32_t*)0x40094004U)
#define REG_USART1_IER             (*(__O uint32_t*)0x40094008U)
#define REG_USART1_IDR             (*(__O uint32_t*)0x4009400CU)
#define REG_USART1_IMR             (*(__I uint32_t*)0x40094010U)
#define REG_USART1_CSR             (*(__I uint32_t*)0x40094014U)
#define REG_USART1_RHR             (*(__I uint32_t*)0x40094018U)
#define REG_USART1_THR             (*(__O uint32_t*)0x4009401CU)
#define REG_USART1_BRGR            (*(__IO uint32_t*)0x40094020U)
#define REG_USART1_RTOR            (*(__IO uint32_t*)0x40094024U)
#define REG_USART1_TTGR            (*(__IO uint32_t*)0x40094028U)
#define REG_USART1_FIDI            (*(__IO uint32_t*)0x40094040U)
#define REG_USART1_NER             (*(__I uint32_t*)0x40094044U)
#define REG_USART1_IF              (*(__IO uint32_t*)0x4009404CU)
#define REG_USART1_MAN             (*(__IO uint32_t*)0x40094050U)
#define REG_USART1_WPMR            (*(__IO uint32_t*)0x400940E4U)
#define REG_USART1_WPSR            (*(__I uint32_t*)0x400940E8U)
#define REG_USART1_RPR             (*(__IO uint32_t*)0x40094100U)
#define REG_USART1_RCR             (*(__IO uint32_t*)0x40094104U)
#define REG_USART1_TPR             (*(__IO uint32_t*)0x40094108U)
#define REG_USART1_TCR             (*(__IO uint32_t*)0x4009410CU)
#define REG_USART1_RNPR            (*(__IO uint32_t*)0x40094110U)
#define REG_USART1_RNCR            (*(__IO uint32_t*)0x40094114U)
#define REG_USART1_TNPR            (*(__IO uint32_t*)0x40094118U)
#define REG_USART1_TNCR            (*(__IO uint32_t*)0x4009411CU)
#define REG_USART1_PTCR            (*(__O uint32_t*)0x40094120U)
#define REG_USART1_PTSR            (*(__I uint32_t*)0x40094124U)

#endif /* _SAM3U4E_USART1_INSTANCE_ */
