/**
 * Instance header for USART3 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_USART3_INSTANCE_
#define _SAM3U4E_USART3_INSTANCE_

#define REG_USART3_CR              (*(__O uint32_t*)0x4009C000U)
#define REG_USART3_MR              (*(__IO uint32_t*)0x4009C004U)
#define REG_USART3_IER             (*(__O uint32_t*)0x4009C008U)
#define REG_USART3_IDR             (*(__O uint32_t*)0x4009C00CU)
#define REG_USART3_IMR             (*(__I uint32_t*)0x4009C010U)
#define REG_USART3_CSR             (*(__I uint32_t*)0x4009C014U)
#define REG_USART3_RHR             (*(__I uint32_t*)0x4009C018U)
#define REG_USART3_THR             (*(__O uint32_t*)0x4009C01CU)
#define REG_USART3_BRGR            (*(__IO uint32_t*)0x4009C020U)
#define REG_USART3_RTOR            (*(__IO uint32_t*)0x4009C024U)
#define REG_USART3_TTGR            (*(__IO uint32_t*)0x4009C028U)
#define REG_USART3_FIDI            (*(__IO uint32_t*)0x4009C040U)
#define REG_USART3_NER             (*(__I uint32_t*)0x4009C044U)
#define REG_USART3_IF              (*(__IO uint32_t*)0x4009C04CU)
#define REG_USART3_MAN             (*(__IO uint32_t*)0x4009C050U)
#define REG_USART3_WPMR            (*(__IO uint32_t*)0x4009C0E4U)
#define REG_USART3_WPSR            (*(__I uint32_t*)0x4009C0E8U)
#define REG_USART3_RPR             (*(__IO uint32_t*)0x4009C100U)
#define REG_USART3_RCR             (*(__IO uint32_t*)0x4009C104U)
#define REG_USART3_TPR             (*(__IO uint32_t*)0x4009C108U)
#define REG_USART3_TCR             (*(__IO uint32_t*)0x4009C10CU)
#define REG_USART3_RNPR            (*(__IO uint32_t*)0x4009C110U)
#define REG_USART3_RNCR            (*(__IO uint32_t*)0x4009C114U)
#define REG_USART3_TNPR            (*(__IO uint32_t*)0x4009C118U)
#define REG_USART3_TNCR            (*(__IO uint32_t*)0x4009C11CU)
#define REG_USART3_PTCR            (*(__O uint32_t*)0x4009C120U)
#define REG_USART3_PTSR            (*(__I uint32_t*)0x4009C124U)

#endif /* _SAM3U4E_USART3_INSTANCE_ */
