/**
 * Instance header for USART0 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_USART0_INSTANCE_
#define _SAM3U4E_USART0_INSTANCE_

#define REG_USART0_CR              (*(__O uint32_t*)0x40090000U)
#define REG_USART0_MR              (*(__IO uint32_t*)0x40090004U)
#define REG_USART0_IER             (*(__O uint32_t*)0x40090008U)
#define REG_USART0_IDR             (*(__O uint32_t*)0x4009000CU)
#define REG_USART0_IMR             (*(__I uint32_t*)0x40090010U)
#define REG_USART0_CSR             (*(__I uint32_t*)0x40090014U)
#define REG_USART0_RHR             (*(__I uint32_t*)0x40090018U)
#define REG_USART0_THR             (*(__O uint32_t*)0x4009001CU)
#define REG_USART0_BRGR            (*(__IO uint32_t*)0x40090020U)
#define REG_USART0_RTOR            (*(__IO uint32_t*)0x40090024U)
#define REG_USART0_TTGR            (*(__IO uint32_t*)0x40090028U)
#define REG_USART0_FIDI            (*(__IO uint32_t*)0x40090040U)
#define REG_USART0_NER             (*(__I uint32_t*)0x40090044U)
#define REG_USART0_IF              (*(__IO uint32_t*)0x4009004CU)
#define REG_USART0_MAN             (*(__IO uint32_t*)0x40090050U)
#define REG_USART0_WPMR            (*(__IO uint32_t*)0x400900E4U)
#define REG_USART0_WPSR            (*(__I uint32_t*)0x400900E8U)
#define REG_USART0_RPR             (*(__IO uint32_t*)0x40090100U)
#define REG_USART0_RCR             (*(__IO uint32_t*)0x40090104U)
#define REG_USART0_TPR             (*(__IO uint32_t*)0x40090108U)
#define REG_USART0_TCR             (*(__IO uint32_t*)0x4009010CU)
#define REG_USART0_RNPR            (*(__IO uint32_t*)0x40090110U)
#define REG_USART0_RNCR            (*(__IO uint32_t*)0x40090114U)
#define REG_USART0_TNPR            (*(__IO uint32_t*)0x40090118U)
#define REG_USART0_TNCR            (*(__IO uint32_t*)0x4009011CU)
#define REG_USART0_PTCR            (*(__O uint32_t*)0x40090120U)
#define REG_USART0_PTSR            (*(__I uint32_t*)0x40090124U)

#endif /* _SAM3U4E_USART0_INSTANCE_ */
