/**
 * Instance header for USART2 on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */
#ifndef _SAM3U4E_USART2_INSTANCE_
#define _SAM3U4E_USART2_INSTANCE_

#define REG_USART2_CR              (*(__O uint32_t*)0x40098000U)
#define REG_USART2_MR              (*(__IO uint32_t*)0x40098004U)
#define REG_USART2_IER             (*(__O uint32_t*)0x40098008U)
#define REG_USART2_IDR             (*(__O uint32_t*)0x4009800CU)
#define REG_USART2_IMR             (*(__I uint32_t*)0x40098010U)
#define REG_USART2_CSR             (*(__I uint32_t*)0x40098014U)
#define REG_USART2_RHR             (*(__I uint32_t*)0x40098018U)
#define REG_USART2_THR             (*(__O uint32_t*)0x4009801CU)
#define REG_USART2_BRGR            (*(__IO uint32_t*)0x40098020U)
#define REG_USART2_RTOR            (*(__IO uint32_t*)0x40098024U)
#define REG_USART2_TTGR            (*(__IO uint32_t*)0x40098028U)
#define REG_USART2_FIDI            (*(__IO uint32_t*)0x40098040U)
#define REG_USART2_NER             (*(__I uint32_t*)0x40098044U)
#define REG_USART2_IF              (*(__IO uint32_t*)0x4009804CU)
#define REG_USART2_MAN             (*(__IO uint32_t*)0x40098050U)
#define REG_USART2_WPMR            (*(__IO uint32_t*)0x400980E4U)
#define REG_USART2_WPSR            (*(__I uint32_t*)0x400980E8U)
#define REG_USART2_RPR             (*(__IO uint32_t*)0x40098100U)
#define REG_USART2_RCR             (*(__IO uint32_t*)0x40098104U)
#define REG_USART2_TPR             (*(__IO uint32_t*)0x40098108U)
#define REG_USART2_TCR             (*(__IO uint32_t*)0x4009810CU)
#define REG_USART2_RNPR            (*(__IO uint32_t*)0x40098110U)
#define REG_USART2_RNCR            (*(__IO uint32_t*)0x40098114U)
#define REG_USART2_TNPR            (*(__IO uint32_t*)0x40098118U)
#define REG_USART2_TNCR            (*(__IO uint32_t*)0x4009811CU)
#define REG_USART2_PTCR            (*(__O uint32_t*)0x40098120U)
#define REG_USART2_PTSR            (*(__I uint32_t*)0x40098124U)

#endif /* _SAM3U4E_USART2_INSTANCE_ */
