#!/usr/bin/env python3
"""
Generate the CMSIS `instance/` headers for the AT91SAM3U4E.

PlatformIO's framework-cmsis-atmel package ships the SAM3U `component/` and
`pio/` headers but omits `instance/`, which `sam3u4e.h` includes
unconditionally. Without them the device header will not even parse, so this
script derives the missing headers from what the package *does* provide:

  - peripheral base addresses, from the "Base Address" defines in sam3u4e.h
  - register names, offsets and access qualifiers, from the peripheral structs
    in component/*.h

Register macros are instance-qualified the way stock CMSIS does it
(REG_PIOA_PER, not REG_PIO_PER), so instances that share a struct type -
PIOA/PIOB/PIOC, the four USARTs, EFC0/EFC1 - do not collide.

Marlin's own code uses the struct pointers (PIOA->PIO_SODR), not these macros;
they exist so the vendor header resolves and stays usable.

Usage (from the repo root):
    python3 buildroot/share/scripts/gen_sam3u_instance_headers.py

Re-run this if the framework-cmsis-atmel package is updated.
"""

import os
import re
import sys

CMSIS = os.path.expanduser(
    "~/.platformio/packages/framework-cmsis-atmel/CMSIS/Device/ATMEL/sam3u/include")
OUT = os.path.join("Marlin", "src", "HAL", "SAM3U", "include", "instance")

ACCESS = {"IO": "__IO", "I": "__I", "O": "__O"}

HEADER_DOC = """/**
 * Instance header for {name} on the AT91SAM3U4E.
 *
 * PlatformIO's framework-cmsis-atmel package ships the SAM3U component/ and
 * pio/ headers but omits instance/, which sam3u4e.h includes unconditionally.
 * These headers define only the REG_* convenience macros; the peripheral struct
 * pointers this HAL actually uses (PIOA->PIO_SODR and friends) come from
 * component/. Register names are instance-qualified, as in stock CMSIS, so
 * instances sharing a struct type (PIOA/PIOB/PIOC, the USARTs) do not collide.
 *
 * Generated by buildroot/share/scripts/gen_sam3u_instance_headers.py
 */"""


def main():
    if not os.path.isdir(CMSIS):
        sys.exit("SAM3U CMSIS headers not found at %s\n"
                 "Build the 4pi environment once so PlatformIO installs "
                 "framework-cmsis-atmel." % CMSIS)

    os.makedirs(OUT, exist_ok=True)
    dev = open(os.path.join(CMSIS, "sam3u4e.h")).read()

    # Instance -> base address (the plain-integer form of the define)
    bases = {m.group(1): int(m.group(2), 16) for m in re.finditer(
        r'^#define (\w+)\s+\(0x([0-9A-Fa-f]+)U\)\s*/\*\*<.*?Base Address', dev, re.M)}

    # Instance -> component struct type (the pointer-cast form)
    comp_of = {m.group(1): m.group(2) for m in re.finditer(
        r'^#define (\w+)\s+\(\(\s*(\w+)\s*\*\)0x[0-9A-Fa-f]+U\)', dev, re.M)}

    instances = re.findall(r'#include "instance/(\w+)\.h"', dev)

    comp_dir = os.path.join(CMSIS, "component")
    comp_txt = [open(os.path.join(comp_dir, fn)).read() for fn in os.listdir(comp_dir)]

    def regs_for(struct_type):
        """[(field, offset, access, array_len)] for a component struct, in order."""
        for txt in comp_txt:
            m = re.search(r'typedef struct \{(.*?)\} ' + re.escape(struct_type) + r';', txt, re.S)
            if not m:
                continue
            out = []
            for line in m.group(1).splitlines():
                r = re.match(r'\s*__(IO|I|O)\s+uint32_t\s+(\w+)(\[(\d+)\])?;'
                             r'\s*/\*\*<[^)]*Offset:\s*(0x[0-9A-Fa-f]+)\)', line)
                if r:
                    out.append((r.group(2), int(r.group(5), 16), r.group(1),
                                int(r.group(4)) if r.group(4) else 0))
            return out
        return None

    for inst in instances:
        name = inst.upper()
        struct_type, base = comp_of.get(name), bases.get(name)
        lines = [HEADER_DOC.format(name=name),
                 "#ifndef _SAM3U4E_%s_INSTANCE_" % name,
                 "#define _SAM3U4E_%s_INSTANCE_" % name, ""]

        regs = regs_for(struct_type) if struct_type else None
        if regs and base is not None:
            for field, off, acc, count in regs:
                # Drop the struct's own prefix, qualify with the instance name
                short = field.split("_", 1)[1] if "_" in field else field
                macro = "REG_%s_%s" % (name, short)
                addr = base + off
                if count:
                    lines.append("#define %-26s (*(%s uint32_t(*)[%d])0x%08XU)"
                                 % (macro, ACCESS[acc], count, addr))
                else:
                    lines.append("#define %-26s (*(%s uint32_t*)0x%08XU)"
                                 % (macro, ACCESS[acc], addr))
        else:
            lines.append("/* No register layout available for this instance in component/. */")

        lines += ["", "#endif /* _SAM3U4E_%s_INSTANCE_ */" % name]
        open(os.path.join(OUT, inst + ".h"), "w").write("\n".join(lines) + "\n")

    # A collision would silently shadow a register, so fail loudly instead
    seen, dupes = {}, []
    for fn in os.listdir(OUT):
        for m in re.finditer(r'^#define (REG_\w+)', open(os.path.join(OUT, fn)).read(), re.M):
            if m.group(1) in seen:
                dupes.append("%s in both %s and %s" % (m.group(1), seen[m.group(1)], fn))
            seen[m.group(1)] = fn

    print("Wrote %d instance headers (%d register macros) to %s" % (len(instances), len(seen), OUT))
    if dupes:
        sys.exit("Colliding macros:\n  " + "\n  ".join(dupes))


if __name__ == "__main__":
    main()
