name: ✨ Request a feature
description: Request a new Marlin Firmware feature
title: "[FR] (feature summary)"
labels: 'T: Feature Request'
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please use one of the [support links](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

  - type: markdown
    attributes:
      value: >
        **Thank you for requesting a new Marlin Firmware feature!**

        ## Before Requesting a Feature

        - Read and understand Marlin's [Code of Conduct](https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md). You are expected to comply with it, including treating everyone with respect.

        - Check the latest [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see if the feature already exists.

        - Before you proceed with your request, please consider if it is necessary to make it into a firmware feature, or if it may be better suited for a slicer or host feature.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear description of the problem (e.g., "I need X but Marlin can't do it [...]").

  - type: textarea
    attributes:
      label: Are you looking for hardware support?
      description: Tell us the printer, board, or peripheral that needs support.

  - type: textarea
    attributes:
      label: Describe the feature you want
      description: A clear description of the feature and how you think it should work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
