//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef reprap_h //don't do multiple includes of this file
#define reprap_h

#include <avr/pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define reprapWIDTH 	60	//Width in pixels
#define reprapHEIGHT 	64	//Height in pixels
#define reprapBYTEWIDTH 	8	//Width in bytes

//extern const rom unsigned char reprapbmp[]; //Microchip C18
//extern const unsigned char code reprapbmp[]; //Keil
//extern const unsigned char reprapbmp[]; //SDCC

extern prog_uchar reprapbmp[]; //AVR-GCC, WinAVR

#endif //reprap_h
