#ifndef CONFIG_STORE_H
#define CONFIG_STORE_H

#include "Configuration.h"

// EEPPROM addresses
#define EEPROMADR_VER 0 //char[4]
#define EEPROMADR_AXIS_STEPS_PER_UNIT 4 //float[4]
#define EEPROMADR_AXIS_STEPS_PER_UNIT_X 4 //float
#define EEPROMADR_AXIS_STEPS_PER_UNIT_Y 8 //float
#define EEPROMADR_AXIS_STEPS_PER_UNIT_Z 12 //float
#define EEPROMADR_AXIS_STEPS_PER_UNIT_E 16 //float
#define EEPROMADR_MAX_FEEDRATE 20 //float[4]
#define EEPROMADR_MAX_FEEDRATE_X 20 //float
#define EEPROMADR_MAX_FEEDRATE_Y 24 //float
#define EEPROMADR_MAX_FEEDRATE_Z 28 //float
#define EEPROMADR_MAX_FEEDRATE_E 32 //float
#define EEPROMADR_MAX_ACCELERATION 36 //float[4]
#define EEPROMADR_MAX_ACCELERATION_X 36 //float
#define EEPROMADR_MAX_ACCELERATION_Y 40 //float
#define EEPROMADR_MAX_ACCELERATION_Z 44 //float
#define EEPROMADR_MAX_ACCELERATION_E 48 //float
#define EEPROMADR_ACCELERATION 52 //float
#define EEPROMADR_RETRACT_ACCELERATION 56 //float
#define EEPROMADR_MINIMUMFEEDRATE 60 //float
#define EEPROMADR_MINTRAVELFEEDRATE 64 //float
#define EEPROMADR_MINSEGMENTTIME 68 //long
#define EEPROMADR_MAX_XY_JERK 72 //float
#define EEPROMADR_MAX_Z_JERK 76 //float
#define EEPROMADR_MAX_E_JERK 80 //float
#define EEPROMADR_ADD_HOMING 84 //float[3]
#define EEPROMADR_ADD_HOMING_X 84 //float
#define EEPROMADR_ADD_HOMING_Y 88 //float
#define EEPROMADR_ADD_HOMING_Z 92 //float
#define EEPROMADR_ENDSTOP_ADJ 96 //float[3]
#define EEPROMADR_ENDSTOP_ADJ_X 96 //float
#define EEPROMADR_ENDSTOP_ADJ_Y 100 //float
#define EEPROMADR_ENDSTOP_ADJ_Z 104 //float
#define EEPROMADR_DELTA_RADIUS 108 //float
#define EEPROMADR_DELTA_DIAGONAL_ROD 112 //float
#define EEPROMADR_DELTA_SEGMENTS_PER_SECOND 116 //float
#define EEPROMADR_PLAPREHEATHOTENDTEMP 120 //int
#define EEPROMADR_PLAPREHEATHPBTEMP 122 //int
#define EEPROMADR_PLAPREHEATFANSPEED 124 //int
#define EEPROMADR_ABSPREHEATHOTENDTEMP 126 //int
#define EEPROMADR_ABSPREHEATHPBTEMP 128 //int
#define EEPROMADR_ABSPREHEATFANSPEED 130 //int
#define EEPROMADR_ZPROBE_ZOFFSET 132 //float
#define EEPROMADR_KP 136 //float
#define EEPROMADR_KI 140 //float
#define EEPROMADR_KD 144 //float
#define EEPROMADR_BED_KP 148 //float
#define EEPROMADR_BED_KI 152 //float
#define EEPROMADR_BED_KD 156 //float
#define EEPROMADR_LCD_CONTRAST 160 //int
#define EEPROMADR_AXIS_SCALING 162 //float[3]
#define EEPROMADR_AXIS_SCALING_X 162 //float
#define EEPROMADR_AXIS_SCALING_Y 166 //float
#define EEPROMADR_AXIS_SCALING_Z 170 //float
#define EEPROMADR_HYSTERESIS_CORRECTION 174 //float[4]
#define EEPROMADR_HYSTERESIS_CORRECTION 174 //float
#define EEPROMADR_HYSTERESIS_CORRECTION 178 //float
#define EEPROMADR_HYSTERESIS_CORRECTION 182 //float
#define EEPROMADR_HYSTERESIS_CORRECTION 186 //float

void Config_ResetDefault();

#ifndef DISABLE_M503
void Config_PrintSettings();
#else
FORCE_INLINE void Config_PrintSettings() {}
#endif

#ifdef EEPROM_SETTINGS
void Config_StoreSettings();
void Config_RetrieveSettings();
#else
FORCE_INLINE void Config_StoreSettings() {}
FORCE_INLINE void Config_RetrieveSettings() { Config_ResetDefault(); Config_PrintSettings(); }
#endif

#endif//CONFIG_STORE_H
