/**
 * THIS FILE CONTAINS BACKEND AND LOW LEVEL SETTINGS TO MAKE THE FIRMWARE WORK
 * DO NOT MODIFY ANYTHING IN THIS FILE UNLESS YOU ACTUALLY KNOW WHAT YOU ARE DOING
 * OR YOU WILL BREAK THE FIRMWARE.
 */
#pragma once

#define CONFIGURATION_BACKEND_H_VERSION 020006


/**
 * General Firmware Settings
 */

#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE

#define HOST_KEEPALIVE_FEATURE
#define DEFAULT_KEEPALIVE_INTERVAL 2
#if DISABLED(SPACE_SAVER)
  #define BUSY_WHILE_HEATING
#endif

#define EEPROM_SETTINGS
#if ENABLED(SPACE_SAVER)
  #define DISABLE_M503
#endif
#define EEPROM_CHITCHAT
#define EEPROM_BOOT_SILENT
#if DISABLED(SPACE_SAVER)
  #define EEPROM_AUTO_INIT
#endif

#define PREHEAT_1_LABEL       "PLA"
#define PREHEAT_1_TEMP_HOTEND 200
#define PREHEAT_1_TEMP_BED     60
#define PREHEAT_1_FAN_SPEED     0

#define PREHEAT_2_LABEL       "ABS"
#define PREHEAT_2_TEMP_HOTEND 240
#define PREHEAT_2_TEMP_BED    100
#define PREHEAT_2_FAN_SPEED     0 // Value from 0 to 255

#define NOZZLE_PARK_FEATURE
#if ENABLED(NOZZLE_PARK_FEATURE)
  #define NOZZLE_PARK_POINT { (X_MAX_POS - 15), 15, 10 }
  #define NOZZLE_PARK_XY_FEEDRATE 100  
  #define NOZZLE_PARK_Z_FEEDRATE 5  
#endif

/**
 * LCD General Settings
 */

#define DISPLAY_CHARSET_HD44780 JAPANESE
#define LCD_INFO_SCREEN_STYLE 0
#define DISABLE_REDUCED_ACCURACY_WARNING
#define INDIVIDUAL_AXIS_HOMING_MENU

/**
 * Misc features and settings
 */

#define PRINTJOB_TIMER_AUTOSTART

#if DISABLED(NO_SDCARD)
  #define SDSUPPORT
#endif

#if DISABLED(SPEAKER_KILL)
  #define SPEAKER
#endif

#if ENABLED(FAN_FIX)
  #define FAN_SOFT_PWM
  #define SOFT_PWM_SCALE 1
#else
  #define SOFT_PWM_SCALE 0
#endif

/**
 * ABL Probe Settings
 */

#if ENABLED(ABL_ENABLE)

  #if DISABLED(BLTOUCH)
    #define FIX_MOUNTED_PROBE
  #endif

  #if ENABLED(SLOWER_PROBE_MOVES) || ENABLED(TH3D_EZ300) || ENABLED(TIM_AM8)
    #define XY_PROBE_SPEED 8000
  #else
    #if ENABLED(EZABL_SUPERFASTPROBE)
      #define XY_PROBE_SPEED 16000
    #else
      #define XY_PROBE_SPEED 12000
    #endif
  #endif

  #define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z
  #define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)  
  #if ENABLED(FIX_MOUNTED_PROBE) && DISABLED(HEATERS_ON_DURING_PROBING)
    #define PROBING_HEATERS_OFF   
  #endif

  #define MULTIPLE_PROBING 2

  #if ENABLED(BLTOUCH)
    #define Z_CLEARANCE_DEPLOY_PROBE   12
    #define Z_CLEARANCE_BETWEEN_PROBES 8
    #define Z_CLEARANCE_MULTI_PROBE    8
    #define ENDSTOPPULLUP_ZMIN
    #define ENDSTOPPULLUP_ZMIN_PROBE
  #elif ENABLED(EZABL_SUPERFASTPROBE)
    #define Z_CLEARANCE_DEPLOY_PROBE   1
    #define Z_CLEARANCE_BETWEEN_PROBES 2
    #define Z_CLEARANCE_MULTI_PROBE    1
  #else
    #define Z_CLEARANCE_DEPLOY_PROBE   5
    #define Z_CLEARANCE_BETWEEN_PROBES 3
    #define Z_CLEARANCE_MULTI_PROBE    3
  #endif

  #define Z_PROBE_OFFSET_RANGE_MIN    -5
  #define Z_PROBE_OFFSET_RANGE_MAX     1
  #define Z_MIN_PROBE_REPEATABILITY_TEST
  #define Z_AFTER_PROBING              5
  #define Z_PROBE_LOW_POINT           -2

  #define AUTO_BED_LEVELING_BILINEAR

  #define Z_SAFE_HOMING
  #define Z_SAFE_HOMING_X_POINT ((X_BED_SIZE) / 2)
  #define Z_SAFE_HOMING_Y_POINT ((Y_BED_SIZE) / 2)
  
  #if ENABLED(BLTOUCH)
    #undef Z_MIN_PROBE_ENDSTOP_INVERTING
    #define Z_MIN_PROBE_ENDSTOP_INVERTING false
    #undef Z_MIN_ENDSTOP_INVERTING
    #define Z_MIN_ENDSTOP_INVERTING false
  #else
    #undef Z_MIN_PROBE_ENDSTOP_INVERTING
    #define Z_MIN_PROBE_ENDSTOP_INVERTING true
    #undef Z_MIN_ENDSTOP_INVERTING
    #define Z_MIN_ENDSTOP_INVERTING true
  #endif

#endif