/**
 * German
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */
#ifndef LANGUAGE_DE_H
#define LANGUAGE_DE_H

#define WELCOME_MSG                         MACHINE_NAME " Bereit."
#define MSG_SD_INSERTED                     "SDKarte erkannt"
#define MSG_SD_REMOVED                      "SDKarte entfernt"
#define MSG_MAIN                            "Hauptauswahl"
#define MSG_AUTOSTART                       "Autostart"
#define MSG_DISABLE_STEPPERS                "Motoren Aus"
#define MSG_AUTO_HOME                       "Auto Home"
#define MSG_SET_HOME_OFFSETS                "Setze Home hier"
#define MSG_SET_ORIGIN                      "Setze Null hier"
#define MSG_PREHEAT_PLA                     "Vorheizen PLA"
#define MSG_PREHEAT_PLA0                    "Vorheizen PLA 1"
#define MSG_PREHEAT_PLA1                    "Vorheizen PLA 2"
#define MSG_PREHEAT_PLA2                    "Vorheizen PLA 3"
#define MSG_PREHEAT_PLA3                    "Vorheizen PLA 4"
#define MSG_PREHEAT_PLA0123                  "Vorh. PLA Alle"
#define MSG_PREHEAT_PLA_BEDONLY             "Vorh. PLA Bett"
#define MSG_PREHEAT_PLA_SETTINGS            "Vorh. PLA Einst."
#define MSG_PREHEAT_ABS                     "Vorheizen ABS"
#define MSG_PREHEAT_ABS0                    "Vorheizen ABS 1"
#define MSG_PREHEAT_ABS1                    "Vorheizen ABS 2"
#define MSG_PREHEAT_ABS2                    "Vorheizen ABS 3"
#define MSG_PREHEAT_ABS3                    "Vorheizen ABS 4"
#define MSG_PREHEAT_ABS0123                  "Vorh. ABS Alle"
#define MSG_PREHEAT_ABS_BEDONLY             "Vorh. ABS Bett"
#define MSG_PREHEAT_ABS_SETTINGS            "Vorh. ABS Einst."
#define MSG_COOLDOWN                        "Heizungen Aus"
#define MSG_SWITCH_PS_ON                    "Netzteil Aus"
#define MSG_SWITCH_PS_OFF                   "Netzteil Ein"
#define MSG_EXTRUDE                         "Extrudiere"
#define MSG_RETRACT                         "Retract"
#define MSG_MOVE_AXIS                       "Achse bewegen"
#define MSG_MOVE_X                          "X bewegen"
#define MSG_MOVE_Y                          "Y bewegen"
#define MSG_MOVE_Z                          "Z bewegen"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_E1                         "Extruder 2"
#define MSG_MOVE_E2                         "Extruder 3"
#define MSG_MOVE_E3                         "Extruder 4"
#define MSG_MOVE_01MM                       "0.1 mm bewegen"
#define MSG_MOVE_1MM                        "1   mm bewegen"
#define MSG_MOVE_10MM                       "10  mm bewegen"
#define MSG_SPEED                           "Geschwindigkeit"
#define MSG_NOZZLE                          "Duese"
#define MSG_NOZZLE1                         "Duese 2"
#define MSG_NOZZLE2                         "Duese 3"
#define MSG_NOZZLE3                         "Duese 4"
#define MSG_BED                             "Bett"
#define MSG_FAN_SPEED                       "Luftleistung"
#define MSG_FLOW                            "Fluss"
#define MSG_FLOW0                           "Fluss 0"
#define MSG_FLOW1                           "Fluss 1"
#define MSG_FLOW2                           "Fluss 2"
#define MSG_FLOW3                           "Fluss 3"
#define MSG_CONTROL                         "Einstellungen"
#define MSG_MIN                             "\002 Min"
#define MSG_MAX                             "\002 Max"
#define MSG_FACTOR                          "\002 Faktor"
#define MSG_AUTOTEMP                        "AutoTemp"
#define MSG_ON                              "Ein"
#define MSG_OFF                             "Aus"
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_PID_P1                          "PID-P E2"
#define MSG_PID_I1                          "PID-I E2"
#define MSG_PID_D1                          "PID-D E2"
#define MSG_PID_C1                          "PID-C E2"
#define MSG_PID_P2                          "PID-P E3"
#define MSG_PID_I2                          "PID-I E3"
#define MSG_PID_D2                          "PID-D E3"
#define MSG_PID_C2                          "PID-C E3"
#define MSG_PID_P3                          "PID-P E4"
#define MSG_PID_I3                          "PID-I E4"
#define MSG_PID_D3                          "PID-D E4"
#define MSG_PID_C3                          "PID-C E4"
#define MSG_ACC                             "Beschleunigung"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-Retract"
#define MSG_XSTEPS                          "Xsteps/mm"
#define MSG_YSTEPS                          "Ysteps/mm"
#define MSG_ZSTEPS                          "Zsteps/mm"
#define MSG_ESTEPS                          "Esteps/mm"
#define MSG_TEMPERATURE                     "Temperatur"
#define MSG_MOTION                          "Bewegung"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Fil. Durchm. 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Durchm. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Durchm. 3"
#define MSG_FILAMENT_SIZE_EXTRUDER_3        "Fil. Durchm. 4"
#define MSG_CONTRAST                        "LCD Kontrast"
#define MSG_STORE_EPROM                     "EPROM speichern"
#define MSG_LOAD_EPROM                      "EPROM laden"
#define MSG_RESTORE_FAILSAFE                "Standardkonfig."
#define MSG_REFRESH                         "Aktualisieren"
#define MSG_WATCH                           "Status"
#define MSG_PREPARE                         "Vorbereitung"
#define MSG_TUNE                            "Justierung"
#define MSG_PAUSE_PRINT                     "Druck pausieren"
#define MSG_RESUME_PRINT                    "Druck fortsetzen"
#define MSG_STOP_PRINT                      "Druck stoppen"
#define MSG_CARD_MENU                       "SDKarte"
#define MSG_NO_CARD                         "Keine SDKarte"
#define MSG_DWELL                           "Warten..."
#define MSG_USERWAIT                        "Warte auf Nutzer"
#define MSG_RESUMING                        "Setze Druck fort"
#define MSG_PRINT_ABORTED                   "Druck abgebrochen"
#define MSG_NO_MOVE                         "Motoren bereit"
#define MSG_KILLED                          "Weiter mit RESET"
#define MSG_STOPPED                         "GESTOPPT"
#define MSG_CONTROL_RETRACT                 "Retract mm"
#define MSG_CONTROL_RETRACT_SWAP            "F.-Wechs. Retract"
#define MSG_CONTROL_RETRACTF                "Retract  V"
#define MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define MSG_CONTROL_RETRACT_RECOVER         "UnRet +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "F.-Wechs. UnRet+"
#define MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define MSG_AUTORETRACT                     "AutoRetract"
#define MSG_FILAMENTCHANGE                  "Filament wechseln"
#define MSG_INIT_SDCARD                     "Init. SDKarte"
#define MSG_CNG_SDCARD                      "Austausch SDKarte"
#define MSG_ZPROBE_OUT                      "Z-Sch. neben Bett"
#define MSG_POSITION_UNKNOWN                "Home X/Y vor Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop Abbruch"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Kalibrieren"
    #define MSG_DELTA_CALIBRATE_X           "Kalibriere X"
    #define MSG_DELTA_CALIBRATE_Y           "Kalibriere Y"
    #define MSG_DELTA_CALIBRATE_Z           "Kalibriere Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Kalibriere Mitte"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_DE_H
