/* Generated by ../../buildroot/share/fonts/uxggenpages.sh */
/* This file is generated automatically, any changes to the file may be REPLACED by future processing. */
/* Please turn to the tools call this script to change the contents! */

#include <u8g.h>

const u8g_fntpgm_uint8_t fontpage_1_243_243[32] U8G_FONT_SECTION("fontpage_1_243_243") = {
  0x00,0x17,0x13,0x00,0xFD,0x00,0x00,0x00,0x00,0x00,0xF3,0xF3,0x00,0x09,0x00,0x00,
  0x00,0x05,0x09,0x09,0x06,0x00,0x00,0x10,0x20,0x00,0x70,0x88,0x88,0x88,0x88,0x70
  };

#define FONTDATA_ITEM(page, begin, end, data) {page, begin, end, NUM_ARRAY(data), data}
static const uxg_fontinfo_t g_fontinfo[] PROGMEM = {
    FONTDATA_ITEM(1, 243, 243, fontpage_1_243_243),
};
