
# define the C compiler to use
CXX = g++

# define any compile-time flags
CXX_FLAGS = -Wall -static -g #-O2

# define the executable file 
BIN = calc

# define the C source files
SRCS = src/module/planner.cpp src/module/calc.cpp

OBJS = $(SRCS:.cpp=.o)

DEPS = $(OBJS:%.o=%.d)

$(BIN): $(OBJS)
	$(CXX) $(CXX_FLAGS) $^ -o $@

-include $(DEPS)

%.o: %.cpp
	$(CXX) $(CXX_FLAGS) -MMD -c $< -o $@

.PHONY: clean

clean:
	$(RM) $(OBJS) $(BIN) $(DEPS)

