#!/usr/bin/env python3
'''
genTFTdigits.py

Generate the tiny digits-only font used by TFT Color UI to label dense UBL mesh
maps (see HAS_TFT_TINY_FONT in lcd/tft/ui_common.h). It covers only the
characters needed for Z values: '+' through '9' (",", "/" are left out).

Glyphs are rendered with the same pipeline as genTFTfont.py (NotoSans Medium,
2bpp antialiased, blank columns and top rows trimmed) and written in the base
font format (unifont_t header, then glyph_t + bitmap per character, NO_GLYPH
(0xFF) for unused codes), like the NotoSans_Medium_ASCII_* files.

Requires: freetype-py  (pip install freetype-py)

Usage (from the Marlin repository root):
  buildroot/share/fonts/genTFTdigits.py [--px 13]
'''

import argparse, importlib.util
from pathlib import Path

SCRIPTDIR = Path(__file__).resolve().parent
REPO      = SCRIPTDIR.parents[2]
FONTDATA  = REPO / 'Marlin/src/lcd/tft/fontdata'

spec = importlib.util.spec_from_file_location('genTFTfont', SCRIPTDIR / 'genTFTfont.py')
gen = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gen)

CHARS = '+-.0123456789'
FIRST, LAST = 0x2B, 0x39    # '+' .. '9'

def main():
  ap = argparse.ArgumentParser(description='Generate the TFT tiny digits font')
  ap.add_argument('--px', type=int, default=13, help='FreeType pixel size (default 13)')
  args = ap.parse_args()

  gen.FAMILIES['NotoSans']['sizes']['digits'] = (args.px, 1)
  r = gen.Renderer('NotoSans', 'digits')
  glyphs = { ord(c): r.render(c) for c in CHARS }

  tops = [ gen.s8(g[5]) + g[1] for g in glyphs.values() if g[1] ]
  bots = [ gen.s8(g[5]) for g in glyphs.values() if g[1] ]
  ascent, descent = max(tops), min(bots)
  cap = glyphs[ord('0')][1]   # Digit height stands in for capital 'A' height

  body, size = [], 8
  for u in range(FIRST, LAST + 1):
    if u in glyphs:
      body.append(f'  // 0x{u:04x}  {chr(u)}\n  ' + ','.join(str(v) for v in glyphs[u]) + ',\n')
      size += len(glyphs[u])
    else:
      body.append(f'  // 0x{u:04x}  {chr(u)} (unused)\n  255,\n')
      size += 1

  name = 'NotoSans_Medium_Digits'
  out = FONTDATA / 'NotoSans' / f'{name}.cpp'
  hdr = [0x82, cap, FIRST & 0xFF, FIRST >> 8, LAST & 0xFF, LAST >> 8, gen.u8(ascent), gen.u8(descent)]
  text = (
    LICENSE +
    '\n// Tiny digits for UBL mesh map labels. Generated by buildroot/share/fonts/genTFTdigits.py\n'
    '\n#include "../../../../inc/MarlinConfigPre.h"\n'
    '\n#if ALL(TFT_COLOR_UI, AUTO_BED_LEVELING_UBL)\n'
    '  #include "../../ui_common.h"   // HAS_TFT_TINY_FONT depends on the layout\n'
    '#endif\n'
    '\n#if HAS_TFT_TINY_FONT\n'
    f'\n// NotoSans Medium Digits {args.px}pt, digit height: {cap}px, range: 0x{FIRST:04x}-0x{LAST:04x}\n'
    f'extern const uint8_t {name}[{size}] = {{\n'
    '  ' + ','.join(str(v) for v in hdr) + ', // unifont_t\n' +
    ''.join(body) +
    '};\n'
    '\n#endif // HAS_TFT_TINY_FONT\n'
  )
  out.write_text(text, encoding='utf-8')
  print(f'{out.relative_to(REPO)}: {size} bytes, ascent {ascent}, descent {descent}')

LICENSE = '''/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2026 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
'''

if __name__ == '__main__':
  main()
