#
# comment-pr.yml
# Add a comment to any PR directed to a release branch
#

name: PR Bad Target

on:
  pull_request:
    branches:
    - 1.0.x
    - 1.1.x
    - 2.0.x

jobs:
  bad_target:

    name: PR Bad Target
    runs-on: ubuntu-latest

    steps:
    - uses: simonlingoogle/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: bad-target.md

    - uses: superbrothers/close-pull-request@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
