#
# comment-pr.yml
# Add a comment to any PR directed to a release branch
#

name: PR Bad Target

on:
  pull_request:
    branches:
    - 1.0.x
    - 1.1.x
    - 2.0.x

jobs:
  bad_target:

    name: PR Bad Target
    runs-on: ubuntu-latest

    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete-branch: false
          comment: >
            Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases.

            Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

            It may help to set your fork's default branch to `bugfix-2.0.x`.

            See [this page](http://marlinfw.org/docs/development/getting_started_pull_requests.html) for full instructions.
