#
# ci-build-tests.yml
# Do test builds to catch compile errors
#

name: CI - Build Tests

on:
  pull_request:
    branches:
    - bugfix-2.1.x
    - 2.1.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - test/**
    - Marlin/tests/**
    - '**/*.md'
  push:
    branches:
    - bugfix-2.1.x
    - 2.1.x
    - release-*
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - test/**
    - Marlin/tests/**
    - '**/*.md'

jobs:
  test_builds:
    name: Build Test
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-22.04

    env:
      CONFIG_BRANCH: ${{ github.base_ref || github.ref_name }}

    strategy:
      fail-fast: true
      matrix:
        test-platform:

        # AT32
        - WANHAO_0327001
        - EASYTHREED_ET4000_PLUS

    steps:

    - name: Check out the PR
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-build-v1
        restore-keys: |
          ${{ runner.os }}-pip-build-

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio/build
          .pio/libdeps
        key: ${{ runner.os }}-pio-build-v1
        restore-keys: |
          ${{ runner.os }}-pio-build-

    - name: Select Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install PlatformIO
      run: |
        pip install -U platformio
        pio upgrade --dev
        pio pkg update --global

    - name: Install Simulator dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-net-dev
        sudo apt-get install libglm-dev

    - name: Run ${{ matrix.test-platform }} Tests
      run: |
        make tests-single-ci TEST_TARGET=${{ matrix.test-platform }}
