#
# close-stale.yml
# Close open issues after a period of inactivity
#

name: Close Stale Issues

on:
  schedule:
  - cron: "22 1 * * *"

jobs:
  stale:
    name: Close Stale Issues
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label / comment or this will be closed in 5 days.'
        days-before-stale: 30
        days-before-close: 5
        stale-issue-label: 'stale-closing-soon'
        exempt-issue-labels: 'T: Feature Request'
