name: Build Configs on Commits

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  Build-Default:
    name: Build Default Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      id: build_configs
      run: |
        pio run
        mkdir temp
        mv .pio/build/STM32G0B1RE_btt/*.bin temp/firmware.bin
      env:
        BOARD: ${{ matrix.board }}
        VERSION: ${{ env.RELEASE_VERSION }}
    - uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ env.RELEASE_VERSION }}.bin
        path: temp/firmware.bin

  