#
# lock-closed.yml
# Lock closed issues after a period of inactivity
#

name: Lock Closed Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1/13 * * *'

permissions:
  issues: write

jobs:
  lock:
    name: Lock Closed Issues
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5
      with:
        github-token: ${{ github.token }}
        process-only: 'issues'
        issue-inactive-days: '60'
        exclude-issue-created-before: ''
        exclude-any-issue-labels: 'no-locking'
        add-issue-labels: ''
        issue-comment: >
          This issue has been automatically locked since there
          has not been any recent activity after it was closed.
          Please open a new issue for related bugs.
        issue-lock-reason: ''
