#
# unlock-reopened.yml
# Unlock an issue whenever it is re-opened
#

name: "Unlock reopened issue"

on:
  issues:
    types: [reopened]

permissions:
  issues: write

jobs:
  unlock:
    name: Unlock Reopened
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-22.04

    steps:
    - name: Unlock Reopened Issue
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      with:
        script: |
          if (!context.payload.issue.locked) return;
          await github.rest.issues.unlock({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
